### ISSUE TITLE
add json response to /identifications/:login.json

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1005]
I think this is for use in the new profile screen on Android, right @budowski?

**Comment by budowski** [comment]
Awesome, yes, it's used by the new profile screen - thanks!

**Comment by kueda** [comment]
K, this is up at http://www.inaturalist.org/identifications/kueda.json. Let me know if you want/need some associate records loaded (like taxon and observation).

**Comment by budowski** [comment]
Awesome, thanks!
Basically, I'll need some extra info (otherwise, I'll have to call additional APIs per result) - if you look at the [design](https://github.com/inaturalist/iNaturalistAndroid/issues/161) (under "Identifications Tab"), we'll need these as well:

1. Observation current species guess (hopefully in the form of preferred_common_name - meaning, this endpoint would have to support a 'locale=es' parameter).
2. Observation photo URL
3. The taxon name (preferred_common_name) of the user's identification
4. iconic_taxon_name for the observation (in case of no photo, and also used to display the appropriate icon used while the observation photo is being loaded)

**Comment by kueda** [comment]
Ok, well all those things are there now, but it's a bit slow, especially for users with a lot of identifications like me, but it should be fine for most people. This endpoint is the rails app so you're going to get rails-ish responses instead of the node-ish responses that include `preferred_common_name`, but you should be able to use the `default_name` to do the same thing.

**Comment by budowski** [comment]
Awesome, thanks!
