### ISSUE TITLE
Graph uploads over time segmented by platform (at least Web, iOS, Android)

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#1089]
It might be helpful to separate observations with photos vs observations without, but maybe not.

@pleary mentioned in Slack that this could be a candidate for the stats page.

Thanks!

**Comment by carrieseltzer** [comment]
I'd love to see this! Could be really insightful to see trends. Would you split out country portals, mobile, and lump everything else using the API since most (all?) of them would be dwarfed by website and mobile?

**Comment by pleary** [comment]
I've added two charts to http://www.inaturalist.org/stats to graph daily and cumulative obs by major platform (web, ios, android, other). Didn't do any breakdown by photos or by site (inaturalist.org is responsible for about 78%, naturalista about 9% and naturewatch 8%). I think I'll close this since the basic requirement is met. Feel free to open others about specific requests if you have them
