### ISSUE TITLE
Add a project name/icon to the Observation search page if filtering by project.

### ISSUE THREAD

**Issue by shuetrim** [inaturalist/inaturalist#1170]
The observation search page is currently displaying the project id or slug in the filters menu (which only displays if you click through the green badge). I suggest that the icon and name should be displayed on the observation search page without opening the filters menu, in a manner similar to the approach used for place.

**Comment by loarie** [comment]
So just to make sure I understand, you want to modify the project filter UI on obs-search so that instead of displaying this:
<img width="803" alt="screen shot 2016-10-06 at 2 50 13 pm" src="https://cloud.githubusercontent.com/assets/598026/19172280/e2ad8adc-8bd5-11e6-902c-cdf512cd08d5.png">
or this:
<img width="803" alt="screen shot 2016-10-06 at 2 50 02 pm" src="https://cloud.githubusercontent.com/assets/598026/19172283/e5593b46-8bd5-11e6-982f-95ffba4c95a8.png">
it displays something like this?
<img width="1198" alt="screen shot 2016-10-06 at 2 56 15 pm" src="https://cloud.githubusercontent.com/assets/598026/19172276/db6b92fa-8bd5-11e6-9bd8-b6da6c6f7dd4.png">
That seems fine to me - thoughts @pleary / @kueda ? Subsequent steps would be getting design support from @joellebel (what I pasted in was not meant to be a design)

**Comment by shuetrim** [comment]
I like the idea you are putting forward but am wanting to go even further.  Specifically, I am suggesting that the icon and project name would be displayed on the OSP even when the filter menu were closed. My weak attempts at screenshot art are attached to show the idea more clearly.

Current view with a project filter:
![before](https://cloud.githubusercontent.com/assets/6021925/19172986/889863c8-8c70-11e6-8d71-6df9de8a9197.png)

Something like the suggested look with a project filter (change highlighted within the pink circle).

![after](https://cloud.githubusercontent.com/assets/6021925/19172985/886ab478-8c70-11e6-957d-3914751dcbec.png)

**Comment by loarie** [comment]
Oh ok - got it. I'd personally be fine with that. Not sure what other folks think

**Comment by joellebel** [comment]
Didn't want you guys to think I missed this. Just formulating my response... This touches on a larger issue regarding filters I've been working on in the background. More to come...

**Comment by shuetrim** [comment]
Looking forward to seeing what you have been working on. Some very cool
things could be done in the filtering space but the balance between UI
complexity and useful functionality is hard in the space.

**Comment by joellebel** [comment]
Right now it's difficult to always know what filters are active. A solution I've been thinking about for awhile would be to show all active filters as "labels". You can find an example of this when searching transactions on Mint.com. Here's a screenshot...

* In this example the "labels" are "garage" and "business card holder" which can be removed by clicking the "X". 

![image](https://cloud.githubusercontent.com/assets/11527994/19293361/57d7eaea-8fd8-11e6-8299-220040270560.png)

## What that might look like on iNat
So that might look something like this in Obs Search...
![image](https://cloud.githubusercontent.com/assets/11527994/19293504/d13d04f0-8fd9-11e6-99ba-9f9209f64166.png)


I think it would be best from a user and probably development standpoint to come up with a more comprehensive solution for search obs filters as opposed to custom solution for projects. I also, am in the process of re-working this screen slightly to accommodate more elements and would like to hold off on any changes (especially custom ones) at the moment. 

@shuetrim Can you tell us more about your use case? For example, are you trying to send folks to this screen to give them a nice presentation of project observations? Perhaps, I can come up with an alternative solution.

**Comment by shuetrim** [comment]
In general, I like your suggestion. 

I agree that you want to come up with a more comprehensive solution rather than just dealing with project filters. I originally was thinking about the problem in a [broader sense](https://github.com/inaturalist/inaturalist/issues/1169) and I agree that it would be good to put the details of the active filters in front of people when they encounter the page.  

The underlying issue for the users I have been working over the last month has been that, at least in the early stages of the learning curve, they would traverse from the project page to the observations page and be unsure if they were still seeing content just for the project or for some other set of criteria. They would also not quite know what selection criteria were implied by having the project as a filter. They wanted to stay within the relatively small world of the project and were unsure about whether they had stepped beyond it to the mass of data on iNat.  The site has so many different ways of slicing and dicing data that it can get a bit confusing, at least at first. Being able to easily keep track of what data filtration is being applied would assist. This particularly impacts on the observation search page but may apply elsewhere. 

Working through that issue for people interested in a specific project led naturally to other filters and how visible they were.

For now, I do not think a custom solution for projects is warranted. Rather I am agreeing with you that it would be good to have filter choices visible without needing to open the filter selection menu.

I like the label suggestion but worry that it would not fit if you had a project filter, 2-3 taxonomy filters a place filter and a filter requiring all observations to have photos, etc. 

If  filtering choices were more tightly integrated into the way that the page was titled and annotated, much like has been done today for the place filter, then these space constraints might be less binding. That comes at a price, leaving you with inconsistency of filter presentation and it makes it harder to remove (or toggle on and off) filters at a single click.

Perhaps a better way to relieve congestion might be to use the project icon at the start of the project filter label and truncate or omit the project name if the name is longer than a predetermined length. Appropriate icons might make other filter labels smaller also.

**Comment by joellebel** [comment]
@shuetrim Yes, space is constraint in the area to the left of the tabs. Thus, I'm in the process of re-working this screen slightly to accommodate more elements.

Here's a quick interim solution which may help things a bit....


![image](https://cloud.githubusercontent.com/assets/11527994/19363076/d637e898-913d-11e6-85e0-3769af572b65.png)

However, I know when we've tried to put thumbnail images inside fields (like the above mock up) it's been a challenge getting it working on all major browsers. Therefore, I leave it up to the devs to determine the priority on this one.

**Comment by shuetrim** [comment]
@joellebel looking forward to seeing what you come up with - and thanks for the attention on this issue.

Regards

Geoff S

**Comment by joellebel** [comment]
@shuetrim No problem. Thanks!

**Comment by loarie** [comment]
@kueda why did you close this - I thought @shuetrim was planning on implementing this based on @joellebel's designs

**Comment by kueda** [comment]
@shuetrim proposed a very specific change to address the problem of not knowing what project the obs search page is filtering by. My reading of the above is that Joelle has a proposal for a different, more general change that would address the larger problem of users not knowing what filters are being applied in obs search, which to my mind merits a different issue.  I think Joelle's approach is better and I see no reason to introduce project-specific UI to this page.

**Comment by loarie** [comment]
got it - @joellebel are you going to open a new issue for your proposal?

**Comment by joellebel** [comment]
@loarie @kueda Yes. Will make a new issue for my proposal, but probably won't be for a bit. I would first like to solidify our plans for the header and main nav to get a better sense of how search will work throughout the entire site. (We've talked about a universal search in the past, but never really came to a final conclusion.) Also, want to explore fixed vs fluid layout issues which may affect how these new search filters will be displayed. ...and some other higher level things before circling back to this.

**Comment by shuetrim** [comment]
That approach suits well from my perspective.

Thanks all.

Geoff Shuetrim

**Comment by markmcgrouther** [comment]
Hi all,
I know I am entering this discussion very late.  I'm excited to see these issues being discussed.  Agreed, a global change would assist everyone rather than changes tailored to a particular Project.  Clearly displaying search filters would be terrific. That leads into our request for colour, shape, pattern filters and tags, but that's another issue ... :)
Thank you,
Mark

**Comment by joellebel** [comment]
Ok. Great. Seems we all agree that filters warrant a larger and separate issue so I shall close this one.
