### ISSUE TITLE
Incorrect community ID for flowering plants

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1182]
As Jakob pointed out in the Google group (https://groups.google.com/forum/#!topic/inaturalist/OuMXvLgs5oY), some observations that should have flowering plants as CID are instead showing the CID as vascular plants. Screenshot below from http://www.inaturalist.org/observations/4402013

<img width="860" alt="screen shot 2016-10-25 at 9 54 14 am" src="https://cloud.githubusercontent.com/assets/7501183/19689019/f813a6e0-9a99-11e6-8b5e-52252cae5394.png">

**Comment by kueda** [comment]
The root of the problem here is that Tracheophyta and  Magnoliophyta are both listed as phyla, even though one is nested inside of the other and Tracheophyta isn't really considered a phylum by anyone. I can fix this by calling Tracheophyta a clade and manually mucking with its rank level, though it feels a bit messy. Would that satisfy you and Jakob?

**Comment by carrieseltzer** [comment]
Ah ha, I see what you mean. I don't have strong feelings about how it is resolved if the end result is expected behavior of CIDs (i.e. going to the finest level of agreement).

**Comment by kueda** [comment]
Ok. Should be fixed. Holler if you see it happening again.
