### ISSUE TITLE
require ssl

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1191]
I think this is long overdue, and @billfitzgerald just brought it up, so let's start the conversation. I think this would mean

1. Require SSL for all web traffic, redirect all http requests to https equivalents
1. Use HSTS directives ([maybe Rails does this by default](http://ieftimov.com/rails-tls-hsts-cookies)?)
1. Ensure we're serving secure cookies
1. Try to notify all Rails API users that they have 3 months to start using HTTPS before we shut it down
1. Same for the node API, support SSL, notify users. Would we need a new version?
1. Figure out how to use SSL with S3 assets so we don't get mixed content warnings

Implications

* Fill in please!

**Comment by pleary** [comment]
1-4. Sounds good
5. The API already does SSL https://api.inaturalist.org/v1/observations/50 , and we can setup an http -> https redirect in the nginx load balancer
6. I didn't realize there is a URL that will give https assets https://s3.amazonaws.com/static.inaturalist.org/photos/4954438/original.jpg . Other URLs don't work I think because our bucket name has dots in it. I read a few things about S3 and SSL, and it's looking to me like setting it up through CloudFront will be the easiest way to do it. We might have even had that set up at one point on one of the AWS accounts.

We could set up a CouldFront distribution for the above asset URL, get an SSL certificate for static.inaturalist.org, upload that to CloudFront, and point static.inaturalist.org to CloudFront. Something like this http://billpatrianakos.me/blog/2015/08/28/use-a-custom-domain-and-ssl-certificate-with-amazon-cloudfront/

Sounds like there are some possible implications for mobile devices, browser compatibility in general, with some SSL setups so we should just test thoroughly. Other than that, seems like the right thing to do

**Comment by mjon** [comment]
I got an email yesterday from one of the NatureWatch NZ users about the difficulties they're having getting a widget to work on an external https website (compare https://www.funnz.org.nz and http://www.funnz.org.nz). 

I'm not sure how much this is caused by the naturewatch.org.nz domain name of the URLs in the widget. I've asked them to swap out that for the inat equivalents with https and see if it works. It might not given the content warnings I'm seeing from the photos when I try out iNat on https.

Regardless, getting everything running properly on https will be helpful. Thanks for looking into this.

Jon (Sullivan)

**Comment by pleary** [comment]
I thought I'd made a lot of progress on this, but looking at the bullet points maybe not.

(6) is done now. We're now serving content through CloudFront rather than S3 directly. We have a 1 year SSL certificate from NameCheap for static.inaturalist.org which was uploaded to AWS and attached to the CloudFront distribution. This gives us valid https for assets, for example https://static.inaturalist.org/photos/4954438/original.jpg

The API and site have already supported HTTPS requests for some time. As of today, most asset URLs returned by the API are for their HTTPS equivalents (EOL images are the known exception since they do not yet support HTTPS). And as of today, the website is using HTTPS for just about everything it can as well, so most pages (without EOL images) should be fully secure as far as the browser is concerned.

(1) No attempt yet to require HTTPS or redirect from non-secure to secure. (2,3) Still not entirely sure what these are - I'll try to figure out how to confirm we're doing them. (4,5) No moves yet on notifying anyone, creating a end-of-life timeline for non-secure requests, or versioning the API

@mjon The widget might work now if using https://www.inaturalist.org requests. The domain http://naturewatch.org.nz/ does not accept HTTPS requests because it does not have an SSL key. That's something that needs to be purchased through various vendors (we use Comodo SSL via NameCheap), and validated by the owner of the domain. If we had a validated SSL key for that domain, we could apply it on our end and enable HTTPS requests for naturewatch.org.nz

**Comment by mjon** [comment]
Excellent. Thanks for the update Patrick. That sounds like great progress. I'll check with everyone here and see if they're happy purchasing an SSL key for naturewatch.org.nz.

**Comment by kueda** [comment]
@pleary, are we at a point where we can try 1 at least?

**Comment by pleary** [comment]
Yep I think we can move forward with it. Want me to start looking at the nginx redirect rules? Sounds like we want it for www.inaturalist.org, what about api.inaturalist.org, or tiles.* ?

**Comment by kueda** [comment]
Let's start with enforcing SSL just for web traffic, so just www.inaturalist.org and not api or tiles for now.
