### ISSUE TITLE
GBIF.eml startdate set to 0206

### ISSUE THREAD

**Issue by MortenHofft** [inaturalist/inaturalist#1248]
The eml shared through GBIF have a temporal coverage 0206-2016
http://api.gbif.org/v1/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7/document

https://github.com/inaturalist/inaturalist/blob/c802eb54cc177ada73296eec2a1ca53ea46df61b/app/views/observations/gbif.eml.erb#L59

I'm guessing that isn't intended?

Thanks

**Comment by carrieseltzer** [comment]
I noticed that the other day too, and I think it came from an observation with the date entered incorrectly, but that observation is no longer included or the date was corrected (as far as I can tell).

**Comment by kueda** [comment]
This is due to an observation with a bad date, in this case http://www.inaturalist.org/observations/3842896. The way to deal with this is to find the observation and use the Data Quality Assessment to vote that the date is inaccurate. That will remove it from the Research Grade pool and the next time we generate the DwC-A that observation won't be included and the date range will not include that super early date. Whether or not GBIF correctly re-indexes the archive is up to them.

You could also be proactive about date issues by searching for observations sorted by date observed, e.g. http://www.inaturalist.org/observations?order=asc&order_by=observed_on&place_id=any&quality_grade=research&subview=table. Most of them are people inappropriately posting photos that are not their own work, some are legit observations from 20-30 years ago, and some are like this one, just erroneous dates.

**Comment by MortenHofft** [comment]
Thank you for your detailed response. I have marked the data as inaccurate.
