### ISSUE TITLE
Observation Detail Page Redesign

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1270]
We didn't go through with the functional spec process for some reason, but the overall goal is to get the obs detail page inline with our emerging design standards while supporting new features like Annotations and identification categories, hopefully with minimal loss of existing functionality. A lot of design effort has gone into communicating the more confusing aspects of quality grade and the community ID, which will hopefully help people understand how they work.

**Mock / Visual Spec:** http://www.thinkmoredesign.com/inat/Specs/Web/Observation_Detail/Observation_Detail_v01_r04/

**Comment by joellebel** [comment]
@pleary and @kueda 

Updated the specs with the following:

* Projects Ob Fields
* Ob Fields
* IDs with comments
* Fixed headings in right column so they are all 18px now

**Comment by joellebel** [comment]
# Date Wrap
Change font-size to 13px and add bullet between date and time
![image](https://cloud.githubusercontent.com/assets/11527994/23926857/d77b31e8-08d3-11e7-91d5-b3dc1e064229.png)

# Accuracy Not Provided State
I know I flipflopped on this, but I think this is the most explicit... (we'll have to widen the containing div of the modal)

![image](https://cloud.githubusercontent.com/assets/11527994/23927864/9e75545e-08d9-11e7-84c8-66bde0e04598.png)


# Date and Time Empty State

![image](https://cloud.githubusercontent.com/assets/11527994/23962458/63fb5598-096b-11e7-89d9-debdf3495f7a.png)

# Faves Typo

"joelle, kueda, pleary and 1 others faved this observation" "Others" should be singular for this instance.

**Comment by joellebel** [comment]
# Flagging Treatments

"Role" is used to indicate the level of permissions an iNat user has. There are 3:

1. Admin
2. Curator
3. User


# No flag - View for all roles

![image](https://cloud.githubusercontent.com/assets/11527994/23969279/1ab081e8-0983-11e7-9e3e-13fa2532df8c.png)

* There is also no flag at the top obviously.

# Flagged as Spam - User View

Going with the current implementation...

![image](https://cloud.githubusercontent.com/assets/11527994/23971168/14857182-098a-11e7-8591-3697a005305e.png)


# Flagged as Offensive/Inappropriate or Other - User View

## Header
![image](https://cloud.githubusercontent.com/assets/11527994/23971706/42e64784-098c-11e7-91a2-0395ab08ec3a.png)

* Here's the text so you can easily copy and paste it: 

Flagged as inappropriate This observation has been flagged and is no longer publicly visible. You can see it because you created it, or you are a site curator. If you think this is a mistake, please contact us.


## Data Quality Section

![image](https://cloud.githubusercontent.com/assets/11527994/23971774/90e80242-098c-11e7-8f13-2e49a147893a.png)

* Tapping "Add/Edit Flags" opens the current modal for adding and removing flags. This modal...

![image](https://cloud.githubusercontent.com/assets/11527994/23971841/d5247ecc-098c-11e7-8249-34674e1df3bd.png)





------------------------------------------------------------------------------------------


# Flagged as Offensive/Inappropriate or Other - Admin, Curator View

* This header is the same, but I changed the "Add/Edit Flags" link to "Manage Flags" which will take you to the existing flags page for that observation where you can see more details, resolve or delete flags. 

![image](https://cloud.githubusercontent.com/assets/11527994/23972109/c848b442-098d-11e7-9b08-23eec3ba0f8e.png)

* Again, just changed the link to "Manage Flags" which takes you to the existing flags page. 

![image](https://cloud.githubusercontent.com/assets/11527994/23972213/2887c528-098e-11e7-8f45-7f9a09b52389.png)

------------------------------------------------------------------------------------

# The What's Needed to Achieve Research Grade List

When there is a flag, the flag line item shows up in the list. See below...

![image](https://cloud.githubusercontent.com/assets/11527994/23972273/5f9ec264-098e-11e7-86a6-38c0db1a7917.png)

**Comment by joellebel** [comment]
Forgot to mention all the red flagging boxes get the same bootstrap alert box treatment.

**Comment by joellebel** [comment]
# Flagging Continued...

Currently we DO allow regular users to see all the flags on an ob that's been flagged as Offensive/Inappropriate or Other. So for those instances (when there are flags on an ob from other users we can either remove this functionality or do something like this...

![image](https://cloud.githubusercontent.com/assets/11527994/23973123/ef6f4834-0991-11e7-9a9e-e2196e84fc42.png)


I've just added a "View all flags" link which takes you to the flags page. 

No opinion, either way.

**Comment by joellebel** [comment]
# Flagging Modal

Also tidied up this modal so it's a little more clear....

![image](https://cloud.githubusercontent.com/assets/11527994/23973780/ef6db57a-0994-11e7-9657-b9252e765e26.png)

**Comment by joellebel** [comment]
#  Icons for "Evidence of organism" and "Recent evidence"

I'm thinking a dna strand for "Evidence of organism". It's not a fontawesome icon so I'll have to make an svg for it. Also, thinking about a clock for "Recent evidence". It's "fa-clock-o"

![image](https://cloud.githubusercontent.com/assets/11527994/23974235/741f5dda-0997-11e7-924f-912ac17e355b.png)

Any thoughts?

**Comment by joellebel** [comment]
# Community can improve question

* Notice I changed the order of the table so the species level is right above the improvement question since there are circumstances when they're related. 


# Genus Level

![image](https://cloud.githubusercontent.com/assets/11527994/23974997/ad7feb7c-099b-11e7-993b-911971fbf80a.png)




# Family Level


![image](https://cloud.githubusercontent.com/assets/11527994/23974918/25973224-099b-11e7-91dc-78ff1756c831.png)

# Unchecked state

* Note: value with more votes is bold
* Value with no votes doesn't show vote count
* This is how it would look if you haven't checked a box

![image](https://cloud.githubusercontent.com/assets/11527994/23975055/ec9d16ea-099b-11e7-813b-a3dbe2a8b87c.png)


# Checked State

![image](https://cloud.githubusercontent.com/assets/11527994/23975117/399286c4-099c-11e7-9abc-9a6e824eca89.png)


# Showing User Votes

Clicking on the vote counts (for example, "3 votes") shows a popup with the list of voters as it does in the data quality table.

**Comment by joellebel** [comment]
# Community ID Opt-Out

# Direction 1: Simply

* Note: the info icon links to the current "About" modal.

### Opted in (Viewing your ob)

![image](https://cloud.githubusercontent.com/assets/11527994/23975485/460d51e8-099e-11e7-84ea-a46589aad7d0.png)

### Opted Out (Viewing your ob)

![image](https://cloud.githubusercontent.com/assets/11527994/23975503/645b29ea-099e-11e7-9971-95151b35a684.png)


### Opted Out  (Viewing another's ob)

![image](https://cloud.githubusercontent.com/assets/11527994/24018439/1789d860-0a51-11e7-9613-cb750c509fb4.png)


# Info OnClick Info Modal

![image](https://cloud.githubusercontent.com/assets/11527994/24018681/256acf7e-0a52-11e7-9fa9-5283d6f3e365.png)





# Direction 2: More Explicit

### Opted in (Viewing your ob)

* The info icon opens the current "About" modal

![image](https://cloud.githubusercontent.com/assets/11527994/24019626/fb8266e6-0a55-11e7-8c98-f1bb47c06f6c.png)

### Opted out (Viewing your ob)

![image](https://cloud.githubusercontent.com/assets/11527994/24019637/06911e4c-0a56-11e7-861b-cae7402cf694.png)

* The opt in and edit settings links function as they currently do
* The yellow box is the standard bootstrap alert box but the text is center-aligned.
* The info icon next to "(User has opted out of Community ID)" opens the same info modal as illustrated in Direction 1


I like the more explicit version, but am a little concerned unknowing folks may feel like you're suppose to reject the CID if it's the not the same as yours. We could always put a warning or explanation in there, that this is to be used only when you feel strongly.

**Comment by joellebel** [comment]
# Project Settings Dropdown

![image](https://cloud.githubusercontent.com/assets/11527994/24054126/57f83dc2-0af8-11e7-91e1-e5430703fc65.png)


* Uses standard bootstrap dropdown menu
* The info text under the the checkbox utilizes the "text-muted" muted class
* Bootstrap has the text at 12px so I've increased it all to 14px because Whitney is hard to read at 12px
* All functionality works the same as it does now.

**Comment by joellebel** [comment]
# Observation Field Links

![image](https://cloud.githubusercontent.com/assets/11527994/24067559/b709c2a2-0b3b-11e7-8eb8-81d6d866ac97.png)

**Comment by joellebel** [comment]
Just a heads up I updated the above Observation Field Links modal with the latest design based on feedback from last week.

**Comment by kueda** [comment]
Re: CID opt in/out, I think we should go with "Direction 2: More Explicit". Definitely the clearest, and most closely matches the current functionality. Personally I think always having the ability to opt in our out implied by "Direction 1: Simply" would be useful, but it's also more opaque.

**Comment by joellebel** [comment]
Sounds good to me!

**Comment by joellebel** [comment]
# Conservation Establishment Badging

Let me know your thoughts... (I basically have recycled what we have now)

## Example of an Endangered / Endemic Taxon

* Badge only appears next to page title and CID
* Using the current color scheme

![image](https://cloud.githubusercontent.com/assets/11527994/24125804/bbe28bda-0d87-11e7-9a7a-905a0eb52ebd.png)

### Info Popup onClick

#### Conservation State

![image](https://cloud.githubusercontent.com/assets/11527994/24125925/6163c740-0d88-11e7-9669-cdb9b89eb6c6.png)

#### Establishment State

![image](https://cloud.githubusercontent.com/assets/11527994/24126048/1cec62a6-0d89-11e7-96a2-1256bee28540.png)


* Note: I like making the popup backgrounds the same color as the badge so when you're clicking on them it's clear which one you're clicking on. @pleary let me know though if it requires an unreasonable amount of CSSing though. I can be convinced to use the standard popups.

**Comment by joellebel** [comment]
@pleary Just a note, I'm basing the popup base styles off this... http://getbootstrap.com/javascript/#popovers-examples and then adding iNat colors on top.

**Comment by joellebel** [comment]
# Research Grade List "OR" Statement

Will add this to the spec, but wanted to share it here. (Also, don't mind the fact that the table data is inconsistent with the Research Grade list. I just wanted to show how the text works)

![image](https://cloud.githubusercontent.com/assets/11527994/24127956/d7795f96-0d95-11e7-9e1f-6c21ce175859.png)

**Comment by joellebel** [comment]
# Copyright and Photo Info Link Rehash

I've made the image slightly smaller, made the icons smaller and changed them a bit.

We concluded using the CC icons found here: https://creativecommons.org/about/downloads/  is probably best. Each photo should show its corresponding CC icon.

* Note: The info icon is 16px and the CC icon is only 14px. This is so they have the same height. 



![image](https://cloud.githubusercontent.com/assets/11527994/24161091/b5e06916-0e20-11e7-90ee-54d1c400a732.png)

**Comment by joellebel** [comment]
@pleary the "wild" icon and the "dna" icon svgs are on dropbox here: Design > Web > Observation Detail

The DNA icon will need an attribution somewhere on the site. Here's a link to it... https://thenounproject.com/term/dna/375187/

The "wild" icon doesn't need an attribution.

I tried to model the dimensions of the fontawesome icons, but it's not an exact science. I might have to make adjustments after looking at it. I think that's all the icons I owe you at the moment.

**Comment by alexshepard** [comment]
On Safari.

1. I go to `http://www.inaturalist.org/observations/6173274?show2`
2. The observation page includes a working map view
3.  I then go someplace else (it doesn't matter where)
4. I then use the browser back button to return to `http://www.inaturalist.org/observations/6173274?show2`
5. The map view now shows "location unknown"

This doesn't seem to happen on Chrome.
