### ISSUE TITLE
Flickr photos nor wikipedia article does not come to place page

### ISSUE THREAD

**Issue by haukkovaara** [inaturalist/inaturalist#1286]
I added  few days ago this place:
https://www.inaturalist.org/places/vallonjarvi

I also uploaded a photo from Vallonjärvi to Flickr:
https://www.flickr.com/photos/129067810@N06/31839946324/in/dateposted-public/

And created a wiki description of the place:
https://en.wikipedia.org/wiki/Vallonjärvi

But no photo from Flickr nor the Wikipedia text appers in iNaturalist page.

Looks like a major bug...

**Comment by kueda** [comment]
I don't think there's a bug here. Your wikipedia page is showing. Keep in mind that the name of the place must match a page on Wikipedia. Also for towns and counties (or their equivalent administrative levels in countries outside the US), we use the `display_name` when looking up the Wikipedia page, since there's more chance of collision with identically named places in other locations. Sometimes it's necessary to make a redirect page on Wikipedia, e.g. if your iNat place is named `Vallonjarvi` but the Wikipedia page is named `Vallonjärvi`, a redirect page on Wikipedia would send iNat searching for the correct page.

Flickr photos need to be licensed for re-use (e.g. Creative Commons, Public Domain, etc), tagged `landscape`, and have coordinates near your place for them to show up. We also omit photos with tags like `honeymoon` or `birthday` because they've caused problems with unhelpful photos showing up on the place pages in the past.  I think the only reason your Flickr photo isn't showing up is because it isn't tagged `landscape`.

On a higher level, place pages really don't get a lot of traffic, so I wouldn't worry too much about what does and doesn't show up there, unless there's some kind of inappropriate content to deal with.
