### ISSUE TITLE
CR2 aren't valid photos for iNat Photos

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#1297]
See for example: http://www.inaturalist.org/photos/2151166
also 2151169, 2151159, 2151175

NB - CR2 are Canon Raw files, so these are technically photos.

**Comment by kueda** [comment]
Tried to replicate with the uploader, the old obs form, and a custom script using the API, but no dice. Followed up with the one user who made all the photos you reported to see if he has any addition info.

**Comment by kueda** [comment]
Well, I can't replicate this. I reached out to the person who added the files you cited and he said this:

> Almost certainly I used the batch upload tool on the web site. The Dates Added are only a few seconds apart. And it must have been the old version of the tool, since they were added in 2015. My usual workflow was: I selected my best photo from several observations and uploaded them at once with the batch upload tool. Probably in these observations, that was the jpeg. Then I revisited each observation one at a time and added the second photo, using the "Add more photos" link under the photo. I must have added the .cr2 version instead of the jpeg version at that point and didn't catch it. Maybe it showed the "processing..." notice and I didn't bother to refresh it later.

Soo... I'm hoping this was a problem that has since been fixed. This person also tried to follow his own steps and was unable to add a new CR2 file. I'm going to close for now, but if you notice new photos like this, please re-open.
