### ISSUE TITLE
taxon.taxon_ancestors_as_ancestor not set for newly created taxa - breaking atlases

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1303]
Atlases use `taxon_ancestors_as_ancestor` to create atlas_presence_places https://github.com/inaturalist/inaturalist/blob/master/app/models/atlas.rb#L34
but apparently that isn't populated on taxa create (AncestryDenormalizer.denormalize) 
which means that if someone creates a taxon, then creates an atlas, they cannot add atlas_presence_places e.g. http://www.inaturalist.org/atlases/2042

**Comment by kueda** [comment]
`TaxonAncestor` records never get created in response to user actions, they just get re-created daily. We could add them when a taxon is created, but I'm assuming @pleary didn't do that for a reason. Thoughts, Patrick?

**Comment by pleary** [comment]
The only reason something like this wasn't implemented is because we haven't used the denormalized ancestries much and it just hasn't really come up. I created #389 over 2 years ago to capture this feature, and it took until now for it to be an actual problem.

I'm all for getting this done, to whatever extent we need. For example it sounds like we want to make denormalized ancestries for new taxa, but maybe getting everything synced after taxon changes isn't really needed right now and can wait for the daily full rebuild.

**Comment by kueda** [comment]
Cool. I'll get on it.
