### ISSUE TITLE
Attemping to upload this KML results in "Sorry that doesn't exist"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1319]
A user says she gets the Mole error page when uploading [this KML](https://www.dropbox.com/s/z417b1gbyuvknb8/Waterton_Biosphere_Reserve%20KML%202015.kml?dl=0). I was able to replicate.

**Comment by kueda** [comment]
For the record, I'm pretty sure the problem here was that there were several polygons that overlapped... I think. We actually have a step right before the boundary gets saved to the database that attempts to remove those overlaps, but I think that KML was triggering something earlier on that was choking on the overlaps.

Best advice to people like this is to upload a KML with only one polygon. If you see multiple "layers" in Google Earth then you're doing it wrong.
