### ISSUE TITLE
possible to create numeric login with facebook sign in?

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1337]
User 454615 had `177` as their login, which causes problems. Their name is `유한경`, so this might be some kind of unicode issue with creating account via Facebook. See Cassi's help@inat message, "observations by numerically-named user goes to that #observation page"

**Comment by boucur** [comment]
User ID 651625 appears to have 206 as their login.

**Comment by loarie** [comment]
https://www.inaturalist.org/users/1152363 has a login of "819". I can confirm that this is causing issues for iNat users with ids matching these logins (e.g. user number 819 is seeing user 1152363's icon instead of their own in the iOS app)

**Comment by pleary** [comment]
This should be fixed for 3rd party logins. The issue was we were getting names from third parties that had no ascii characters in them, and when we stripped non-ascii characters before looking up the name, we ended up with empty strings. We then looked for the login, appended an incrementing integer to the end until we found a unique login, resulting in users with integer logins.

The fix here prepends `naturalist` when the candidate name is empty, resulting in logins like `naturalist1`, `naturalist2`, etc. All existing instances of integer logins have been updated
