### ISSUE TITLE
searching for "Arge" does not show the right taxon as the first result

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1402]
Try to add an identification of http://www.inaturalist.org/taxa/129425-Arge to an observation. For me it doesn't even show up in the list of results, even though it's the first result at http://api.inaturalist.org/v1/taxa/autocomplete?q=Arge

**Comment by pleary** [comment]
this is fixed in 9216ac2a for the legacy Rails API, and in inaturalist/iNaturalistAPI@eab1f716 for the node API. I updated `names.exact` to use the `keyword` type in ES5, but that's case sensitive. I added a new field to the index (bc9cdb04) that uses the `keyword_analyzer` like we had in ES2, and now the methods are using that field
