### ISSUE TITLE
No mapping found for [identifications.created_at]

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1414]
**When I click at "ID's" link (/identifications/user) on homepage of a logged user, I get the error:**

![screenshot from 2017-07-19 16-42-55](https://user-images.githubusercontent.com/1500146/28396615-fd2a7f08-6cd2-11e7-98b4-37c9c1359f86.png)

**I set up the database and  loaded the schema.**
**What could be causing this?**
**The log is:**

 Processing by IdentificationsController#by_login as HTML
   Parameters: {"login"=>"jlsnlcd"}
   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
   User: jlsnlcd 1
   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE (lower(login) = 'jlsnlcd') LIMIT 1
   Observation Search (13.1ms) {index: "development_observations", type: "observation", body: {query: {constant_score: {query: {bool: {must: [{bool: {should: [{nested: {path: "non_owner_ids", query: {bool: {must: [{term: {:"non_owner_ids.user.id"=>1}}]}}}}, {nested: {path: "identifications", query: {bool: {must: [{term: {:"identifications.user.id"=>1}}, {term: {:"identifications.own_observation"=>false}}]}}}}]}}]}}}}, sort: [{:"non_owner_ids.created_at"=>{order: "desc", mode: "max", nested_path: "non_owner_ids", nested_filter: {term: {:"non_owner_ids.user.id"=>1}}}}, {:"identifications.created_at"=>{order: "desc", mode: "max", nested_path: "identifications", nested_filter: {term: {:"identifications.user.id"=>1}}}}], size: 30, from: 0}}

 Completed 500 Internal Server Error GET /identifications/jlsnlcd in 20ms (ActiveRecord: 1.2ms | Elasticsearch: 13.1ms)
 ** [Airbrake] Notice was not sent due to configuration:         
   Environment Monitored? false         
   API key set? true
 
 Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [identifications.created_at] in order to sort on","index_uuid":"MSOrbVrpTV6xRTxuatrspg","index":"development_observations"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"development_observations","node":"d9Me0ZTiT9OA1YxBn-z0Xw","reason":{"type":"query_shard_exception","reason":"No mapping found for [identifications.created_at] in order to sort on","index_uuid":"MSOrbVrpTV6xRTxuatrspg","index":"development_observations"}}]},"status":400}):
   app/controllers/identifications_controller.rb:113:in `by_login'
   app/controllers/application_controller.rb:184:in `block in set_time_zone'
   app/controllers/application_controller.rb:182:in `set_time_zone'
   config/initializers/logstasher_catch_all_errors.rb:8:in `call'

**Comment by pleary** [comment]
There was a commit recently which modified the observations Elasticsearch index. The migration is https://github.com/inaturalist/inaturalist/blob/master/db/migrate/20170710150124_add_to_observations_index.rb . We moved from indexing `non_owner_ids` to indexing `identifications`. The migration defines the special mappings, but not standard ones like date, which `identifications.created_at` is.

I'm not sure what your setup is, but you're getting the error because you don't have any `identifications` docs in Elasticsearch with a `created_at field`, i.e. no IDs are indexed. One way or another you need that mapping to exist. We can add `identifications.created_at` to the initial mapping at https://github.com/inaturalist/inaturalist/blob/master/app/es_indices/observation_index.rb , which would only be applied if you rebuilt the Observations index. Otherwise you could index an ID, or just PUT the `identifications.created` at mapping manually.

If you're running a setup that already has Observations indexed in Elasticsearch, you'll need to re-index them after running the above migration

**Comment by pleary** [comment]
@jailsonleocadio Did this help?

**Comment by jailsonleocadio** [comment]
Yes, this really helped me. Thank you!
