### ISSUE TITLE
New header with search

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1530]
Stub, but something in line with https://docs.google.com/document/d/1cBn7LgQ__U4zMMlqrhlAuESiSo5--Gzery13Fft6FpM/edit

**Comment by loarie** [comment]
Is this just universal search or a whole header redesign. If the latter can we get the language switcher and the donate button considered in the designs (and if not in the header than a plan for where else?)

**Comment by kueda** [comment]
Please go to https://docs.google.com/document/d/1cBn7LgQ__U4zMMlqrhlAuESiSo5--Gzery13Fft6FpM/edit#heading=h.ucw3a48zy20e for feature discussion. I want this issue to be just about implementation.

**Comment by kueda** [comment]
Designs ready at https://docs.google.com/document/d/1gaoqFoR9GYrD0VhCcW34edju_CWqARxG8WjjO21T4Wg/edit#heading=h.ktedkm6vnwu0 (see comments for agreed-on directions).

**Comment by joellebel** [comment]
# Design Punch List

- [ ] There’s extra space beneath “Identify” when it gets sucked up into the More menu
- [ ] Is it possible to make the collapsed Upload button more of perfect circle?
- [ ] Upload button fixes: Here's a screenshot for reference
![image](https://user-images.githubusercontent.com/11527994/39454440-22add0de-4c90-11e8-9e8c-d53dbdddb970.png)
- "Upload" font-size is 13px
-  a.btn 4px 10px 3px 10px
- Give the whole button a margin-right of 15px (currently it's 20px)

- [ ] Search button (magnifying glass) needs to be #333 to match the rest of the iconography
- [ ] Please make search magnifying glass font-size: 20px
- [ ] Please make sure all elements in the header are vertically middle aligned

Here's how the refined version looks for reference:

one sec.. my screenshotting isn't working

**Comment by joellebel** [comment]
# Search Results Page Punch List
Here's a screenshot for visual reference... 
![image](https://user-images.githubusercontent.com/11527994/39724295-3bf65a4e-51fd-11e8-9c88-abd1441bb60b.png)


## Search Results Page List

- [ ] If you want to go with a taxa thumbnail that matches the height of the blurb, there needs to be 8px of more white space between each result. This will help the eye to digest things better since folks mostly skim results pages and rarely read blurbs. This will also help folks not miss non-taxa results when looking at All results because currently location blurbs are smaller. 

- [ ] The thumbnail needs to be 66x66 if it's going to line up perfectly with the blurb. 
- [ ] The taxa thumbnail needs a 2pt corner radius and a border of 1px #DDD. This will make it match the ob detail screen

- [ ]  The location icon needs to top align with it's corresponding blurb and be 50px so it lines up with the height of its blurb

- [ ] The user profile needs to be 66x66 and have a 1px solid #DDD border (Sorry for the change in border size. (made a mistake earlier)

 - [ ] Empty user profiles should say "No description." like so...
![image](https://user-images.githubusercontent.com/11527994/39727958-9f57e916-5209-11e8-9a6d-15de61f24458.png)

- [ ] Not sure how the project thumbnails/icons are being rendered, but can you make sure their total height and width including borders is 67x67

## Autocomplete Dropdown List

-  [ ] Give profile thumb and default icon 1px solid #DDD border 
- [ ] Give taxa thumb 1px corner radius and 1px solid #DDD border 
- [ ] Make iconic taxa white and put in #AAA box (same size as taxa thumbnail). Give box 1px corner radius and 1px solid #DDD border 
 - [ ] Make location icon inat green
- [ ] Make project default icon same as it is on the search results screen but the overall size is the same as taxa thumbs/icons
 - [ ] Make the project thumb the same overall size is the same as taxa thumbs/icons

**Comment by kueda** [comment]
> Can the Your Observations H1 read "Your Observations" for consistency

I'm going to veto this. It's not a separate page, it's just Obs Search, and I don't want to add any more dynamic functionality to Obs Search before it switches over to React. Also, do you really want to change the h1 every time someone clicks the "Your Observations" checkbox?

Everything else should be on gorilla shortly.

**Comment by joellebel** [comment]
It would also be nice if projects and taxa without a description said "No description." too. Not a biggie though.
