### ISSUE TITLE
Add 'descendant rank' to complete taxa

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1535]
Add a 'descendant rank' to complete taxa. e.g. Crotaphytidae is complete to species, but Proteaceae is complete to genus.

Only display 'x of y', and wanted/discoveries only display if descendant rank is sp or finer (but still display as species - ie continue rolling ssp up to sp and only allowing nodes coarser than sp to be complete)

**Comment by loarie** [comment]
Looking good - I found 2 issues:
1. if taxon.complete_rank != NULL it looks like the  'x of y' and wanted/discoveries are only displayed if taxon.complete_rank is finer than species. These should display if taxon.complete_rank is species or finer

2. the 'All species added to the database (Info)' decoration on the taxonomy tab currently only displays as above. Can we instead have it always display when taxon.complete = true, and generalize it so that it says (** indicate edits I made): 
'All **#{taxon.complete_rank}** added to the database (Info)' -> 'About Complete Taxa: 
"Complete" taxa have all of their descendant, extant **#{taxon.complete_rank}** present in the site's database. When a taxon is complete **to species**, we can say how many of its species have been observed and how many still need to be observed. Counts of species for "complete" taxa do not include "uncountable" species like extinct species or inactive species concepts, and they only include species, not **infraspecific** taxa.'

**Comment by kueda** [comment]
> if taxon.complete_rank != NULL it looks like the 'x of y' and wanted/discoveries are only displayed if taxon.complete_rank is finer than species. 

Before we were only showing "TOTAL SPECIES OBSERVED" when the rank of the taxon was higher than species, b/c it doesn't make sense to say that for a species, since it does not itself contain any species. Similarly, it doesn't make sense to show that for a descendant of a taxon with `complete_rank` set to something other than species, b/c if complete_rank is genus, then the set of species is not complete (instead the set of genera is), and you said you didn't really care about a count of the complete descendants, hence the source of my initial confusion with this issue. Is that not the case? If not, what do you want to show when, say, a superfamily is complete and its `complete_rank` is genus and you view a family in that superfamily? If the `complete_rank` is subspecies, so you want to show a count of subspecies observed when you view a species?

**Comment by loarie** [comment]
I agree with the above. The issue I was referring to occurs when the complete taxon is at rank species. 

To reproduce -
1. note that https://www.inaturalist.org/taxa/20978-Amphibia which is complete on amphibia shows the x of y etc. 
2. go to staging and add complete_rank of species to https://staging.inaturalist.org/taxa/20978-Amphibia (should already be there until staging gets updated)
3. note that x of y disappears from https://staging.inaturalist.org/taxa/20978-Amphibia
4. alter complete_rank to ssp
5. note that x of y reappears on https://staging.inaturalist.org/taxa/20978-Amphibia

x of y should appear in step 3 right?

Everything else is working as I had envisioned.

**Comment by loarie** [comment]
this looks great!
