### ISSUE TITLE
In user's Observations page, have Sort by Species/Taxon Name only use scientific name

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1566]
Currently sorting by Species/Taxon Name in a user's observations page results in some jumbles because whatever is stored in the observation "species_guess" field is what's used for sorting. 

@pleary suggests "locking down sort by name to the taxon scientific name, and removing species_guess entirely." I think that's probably the best way to go and would hopfully result in a things sorted correctly.

**Comment by pleary** [comment]
There's discussion of this a couple years ago starting at this comment https://github.com/inaturalist/inaturalist/issues/540#issuecomment-98795301 . We removed the sort by name option from the drop down, but missed the table header which I think is the only place to sort by name.

Unfortunately we can't implement this right now because `observation.taxon.name` is indexed as a text field in Elasticsearch and you can only sort on keyword fields. So we'd need to re-index all observations to get it to work right, which is a very large task these days.

I actually vote for remedying our previous oversight, and remove the taxon sort option on that user observation view. I think its the only place we allow a taxon name sort, and clearly its a broken feature. We also have plans to redesign that page to bring it more in line with regular obs search.

**Comment by kueda** [comment]
+1 for what Patrick said.

**Comment by pleary** [comment]
The taxon name sort option was removed from that page in #1661
