### ISSUE TITLE
Remove automatic capitalization from common names on Taxon pages

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1586]
Currently our policy is that common names of plants should not be capitalized, yet on taxon pages common names are automatically capitalized for display, eg https://www.inaturalist.org/taxa/58732-Toxicodendron-radicans The big title common name and the common in the taxonomic tree on top both capitalize it as Eastern poison ivy but the common name is all lowercase.

**Comment by boucur** [comment]
Just a note that the names auto-capitalize to sentence case on almost all pages/features that have an updated design since 2016, e.g.

main /observation page, individual observation pages, identify, suggested an ID dropdown search results

but NOT on:

user's main observation page, calendars, /taxa, [main search result hub](https://www.inaturalist.org/taxa/search?utf8=%E2%9C%93&q=plants), lists, places, etc.

**Comment by tiwane** [comment]
Closing due to the desire to go in the opposite direction... https://github.com/inaturalist/inaturalist/issues/1669
