### ISSUE TITLE
Project Curator unable to add required observation fields when adding own observation to project

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1600]
User bryonlichtenhan is a curator for [this project](https://www.inaturalist.org/projects/sky-island-wildlife-tracking-program), and said that until today (1/9/17) he and his fellow curators hadn't had any issues adding observations (and fields) to the the project. Now, when adding either via iOS or web, they get this error:

![image1](https://user-images.githubusercontent.com/15896181/34750383-a60ea5f2-f55b-11e7-9ff5-d306ee1eafcf.png)

I was able to replicate on the web, I got the error after clicking "Add" for the first required field:

<img width="673" alt="screen shot 2018-01-09 at 3 46 26 pm" src="https://user-images.githubusercontent.com/15896181/34750404-bc607ba0-f55b-11e7-8e93-ed747777030b.png">

They said the same error was happening for [their other project](https://www.inaturalist.org/projects/sky-island-nature-watch) as well.

**Comment by tiwane** [comment]
Hmm, [this GG thread](https://groups.google.com/forum/#!topic/inaturalist/Fro7hb3eJQQ) looks like it's related. The OP here says he never chose "Curators" for the Preferred observation fields by setting, it just changed. Is that possible?

**Comment by kueda** [comment]
When I'm signed in as bryonlichtenhan, I can add observations to the "Sky Island Wildlife Tracking Program" project by clicking "Add Observations" on the project page and on the observation detail page. In the uploader, I get an error about it not being able to add to the project, but I think that's expected behavior. Can't speak to the iOS situation, but I can't seem to replicate this on the website. Am I missing something?

**Comment by kueda** [comment]
Any update on this Tony or can we close? And no, to my knowledge it's not possible for your  "Preferred observation fields by" setting to just change on its own.

**Comment by tiwane** [comment]
No one's written in about it lately. I think it can be closed for now.
