### ISSUE TITLE
Disagreements not showing up as such on the CID chart

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1614]
e.g. https://www.inaturalist.org/observations/1775782
<img width="1018" alt="screen shot 2018-01-15 at 1 50 03 am" src="https://user-images.githubusercontent.com/598026/34936485-70eb5c64-f996-11e7-9d88-ef1bb217115a.png">

Also doesn't seem to be showing up in the CID popup.

**Comment by kueda** [comment]
Color in the CID chart is meant to indicate maverick / not-maverick status, and your ID of Genus Junonia is not a maverick. Would you prefer the rule be "red if maverick OR (disagreement AND previous_observation_taxon == community taxon)"? @joellebel do you have a problem with using red in this way to represent an identification that has no red in the main ID / comments section?

**Comment by loarie** [comment]
would it be less controversial to add a new color to represent ancestor IDs? Or even exclude them from the CID graphic?

**Comment by kueda** [comment]
Personally I'm ok making them red, as they are another kind of ID that kind of counts against the CID. Thoughts, @joellebel?

**Comment by joellebel** [comment]
Yes. Making them red sounds good to me. However, if we really wanted to distinguish Maverick and Disagreement, we could do something like this...

![image](https://user-images.githubusercontent.com/11527994/35073405-80eba7d2-fb9d-11e7-951f-5cfd42e211b2.png)

In this graph, the Disagreement red and pink striped.

**Comment by joellebel** [comment]
Like how important is it to show the difference? I think it might be pretty important to hyper identifiers.

**Comment by kueda** [comment]
Not sure it's important, just wanted to check in b/c a red bar meant one thing before and we're proposing that it mean something different.

**Comment by joellebel** [comment]
Just realized... for utmost clarity, if we go with the pin stripe, either of these treatments of the ID would be more successful and consistent...


![image](https://user-images.githubusercontent.com/11527994/35074005-a034f73a-fba0-11e7-9556-a2d6fc49da35.png)


@kueda did we put the disagreement text in the footer of the ID because we were worried about space? Can't remember.

**Comment by kueda** [comment]
Yes, we went with a footer b/c of space concerns, since the taxon name can be very long and the header can have things like ident category and maybe vision status in the future. I'd prefer to avoid pin-striping the footer since it makes disagreements like a problem, so I guess I'll just go with a red bar for both in the chart. Mavericks kind of are problematic, but disagreements are encouraged (by me, at least).

**Comment by joellebel** [comment]
k
