### ISSUE TITLE
Descendent ID not changing Observation Label

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1623]
[This observation](https://www.inaturalist.org/observations/5301202) should have the observation label of Dicranaceae, but alas the observation label is Byropsida.

<img width="686" alt="screen shot 2018-01-18 at 1 53 04 pm" src="https://user-images.githubusercontent.com/15896181/35123423-f60f3c36-fc56-11e7-934e-6b9d0f5230e2.png">

**Comment by kueda** [comment]
Kind of complicated. Currently, when you disagree with a taxon, we assume you are saying "this is not that taxon or anything between what I'm suggesting and that taxon." So in this case, zookanthos's ID counts as a disagreement with Leucobryum glaucum, Genus Leucobryum, and family Dicranaceae. The reason for this is that we are supposed to ID at the lowest level we can, and if zookanthos thought this *could* have been in Dicranaceae, they should have added an ID of Dicranaceae and not something unnecessarily coarse like Bryopsida.

I realize that's really not obvious and perhaps not desirable. Looking at my tests, I think I made it that way to deal with this situation:

ID 1: Homo sapiens
ID 2: Homo sapiens
ID 3: Family Homonidae disagrees this is Homo sapiens
ID 4: Family Homonidae

If we assume that ID 3 is *only* a disagreement with Homo sapiens and not an implied disagreement with Genus Homo, the Observation Taxon will shift to Genus Homo, because it has two implied votes (IDs 1 and 2) and no disagreements. That seemed weird to me because it means that disagreements don't shift the taxon to the most conservative proposed taxon but rather sort of pulls the taxon a little away from the the thing that was disagreed with.

I don't have strong feelings here, though, so I'm happy to change it. @loarie, opinions?

**Comment by loarie** [comment]
I agree there could be weirdness on both ends (ie only pulling away a bit when the user intended to coarsen all the way, but also the opposite which is what happened here).

If you made the change to pull away a bit, will
1: Armadillium
2; Armadillium vulgare
3: Oniscidea (not Armadillium vulgare)

result in an observation label of Oniscidea or Armadillium?

**Comment by kueda** [comment]
With the change that would result in Genus Armadillidium, since it has two implied votes and no disagreements.

**Comment by loarie** [comment]
those seem to be equally unideal edge cases. My vote would be to leave things the way they are to:

1) avoid having to change things
2) err on the side of caution when its unclear exactly whats being disagreed with

but I don't feel strongly if others do

**Comment by tiwane** [comment]
Sounds good to me, Scott.

**Comment by kueda** [comment]
Works for me.
