### ISSUE TITLE
Observation should be RG, perhaps bug with explicit diagreement?

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1649]
https://www.inaturalist.org/observations/9636151

**Comment by kueda** [comment]
The problem here is that dziomber's ID of Asteraceae counts as a disagreement with Genus Arnoglossum and everything in the hierarchy between that and Asteraceae, including Asteroideae which includes  Eupatorium altissimum. That was a move of debatable wisdom on my part. It prevents the kind of whack-a-mole situation where someone uploads a blurry pic of a bird and identifies it as a condor and you back them up to Aves, then they add an equally unjustified but different species-level ID, but it leads to confusing situations like this one. I don't really think I have a preference, but maybe the harm here is greater than the whack-a-mole situation. Thoughts?

**Comment by kueda** [comment]
I will take no feedback as an acceptance of the status quo, though I still don't have much of a preference. If anyone develops one, please re-open.
