### ISSUE TITLE
Observations.dwc api return 404 for pages over 334

### ISSUE THREAD

**Issue by sadeghim** [inaturalist/inaturalist#1656]
Copied from inaturalist/iNaturalistAPI#125 :

Hi,

I am harvesting Australian observations using the observations API and returns 404 for pages over 334 and it doesn't matter what page size I choose. Here are the api calls:

https://www.inaturalist.org/observations.dwc?page=334&max=10&place_id=6744
https://www.inaturalist.org/observations.dwc?page=334&max=100&place_id=6744
https://www.inaturalist.org/observations.dwc?page=334&max=200&place_id=6744

To more clarify my use case: 

I get the number of entries using https://www.inaturalist.org/observations.json?place_id=6744 API and x-total-entries header field then calculate the number of pages by taking the page size into account.

if I call above url as json api instead of dwc (https://www.inaturalist.org/observations.json?page=334&max=10&place_id=6744)I will get following error:

`{
    "error": "Internal Server Error"
}`

**Comment by pleary** [comment]
We could probably use some better error handling here. In essence - we do not allow paging the results of a query past 10,000 results. This is a side effect of the configuration of Elasticsearch which has a max_result_window to prevent high memory usage for high page numbers (see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). Ideally we'd catch that error and tell the user why they can't see more results.

The way to avoid this is to create new searches, as opposed to paging through the results of a single search.  If you're not tied to the response formats of the above APIs, I'd recommend you use the API at https://api.inaturalist.org . I'd make a call like https://api.inaturalist.org/v1/observations?place_id=6744&per_page=100&order_by=id&order=asc, get the last ID of the result set, then continue making calls like https://api.inaturalist.org/v1/observations?place_id=6744&per_page=5&id_above=5000000 using the `id_above` parameter with the last ID of the previous set. Since these are new searches and not pages of a single search, there is no limit to the number of observations you can fetch with this approach
