### ISSUE TITLE
observation.taxon not set correctly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1682]
With [this observation](https://www.inaturalist.org/observations/6520438), the Obs ID is S. valerandi, but the CID is S. parviflorus. Perhaps something got weirded by the taxon swap?

**Comment by loarie** [comment]
https://www.inaturalist.org/observations/6520438 seems to now be working properly (ie RG at S. parviflorus). Was this fixed or did it fix itself?

**Comment by tiwane** [comment]
It was "fixed" I think by wdvanhem's ID. Prior to that the observation.taxon was S. valerandi.

**Comment by loarie** [comment]
Thanks tony, 
I spent some time investigating the situation pre wdvanhem's ID

I think it could be fixed by changing 
https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L1584 to 
```i.taxon_change_id.nil? && i.disagreement == false && i.previous_observation_taxon && i.previous_observation_taxon.ancestor_ids.include?( id_taxon.id ) && !i.taxon.ancestor_ids.include?( id_taxon.id )```
ie conservative_non_disagreements must:
1. not be from taxon_changes AND 
2. not be disagreements AND
3. have previous taxa AND
4. previous taxon must be descendants of the taxon AND 
5. must not be descendants of the taxon

seems sensible with https://staging.inaturalist.org/observations/6520438 and https://staging.inaturalist.org/observations/10220495 at least
let me try to get my local instance current so I can investigate more
