### ISSUE TITLE
Revise projects/index

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1722]
Design is Project Overview C at http://inaturalist.github.io/design/Specs/Web/Projects_Overview/index.html. Probably no need for React, this can be vanilla Bootstrap. Ditch carousels if they're a challenge.

**Comment by joellebel** [comment]
Let me put a spec together. Will do after header.

**Comment by kueda** [comment]
I don't think that's necessary unless you think there's something confusing about "Project Overview C"

**Comment by joellebel** [comment]
# Here's a to-do list for the Projects Index page:

- [ ] Borders Fix: Please make these borders 1px solid #DDD and remove drop shadow from the white band/section below the banner so it looks like this:
![image](https://user-images.githubusercontent.com/11527994/39214649-09d50aca-47ca-11e8-8864-cbb97d3498dd.png)

instead of this:
![image](https://user-images.githubusercontent.com/11527994/39214711-3b49e5a8-47ca-11e8-9a46-ae1cc67f6022.png)

- [ ] Change "Submit" to "Go" for consistency. Plus, "Submit" seems really outdated. 

- [ ] Add a "Followed Projects" section the under "Joined Projects" in the Manage Your Projects dropdown. Give it the same style as Joined Projects with the same limit of projects. This might make for a long list, but I think this is easiest solution atm since we may make joined and following the same. (based on today's discussion in #UX)


- [ ] Limit banner carousel to *3* new style projects only; The carousel is getting too lengthy. 

- [ ] Please double check that titles do not show up on carousel banners for projects that have elected not to show a title. 

- [ ] Recently Active Projects: Can this be projects sorted by latest journal post? Limit to 8. Can be either new or old projects

- [ ] Can projects without a banner pull the same banner/About box bg color they are using for their project. Trying to prevent this:
![image](https://user-images.githubusercontent.com/11527994/39215712-bb687634-47cd-11e8-937f-f1160b8b4d67.png)

 

# Nice to haves

- [ ] It would be nice if the projects that were featured in the Featured section did not show up in the banner carousel

# Question 

- Is there a way to ensure CNC will always show up first in the rotating banner for the time being? If not, then maybe we should just feature

**Comment by joellebel** [comment]
Oh and the most important!

- [ ] Give banner section the same CSS as the project page so banner should fit correctly.
