### ISSUE TITLE
Change "o'clock" capitalization

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1743]
Via bouteloua:

Currently "o'clock" is [capitalized as "o'Clock"](https://www.inaturalist.org/taxa/search?utf8=%E2%9C%93&q=o%27clock) which looks pretty lame. would it be possible to have it display as "O'clock"?

**Comment by kueda** [comment]
As far as I can tell there is no standard for how to capitalize contractions like this. Since there's no clear standard and we don't capitalize the word "of" when it's not in a contraction (e.g. "Grass of Parnassus") and we don't capitalize contractions in other languages (e.g. "Pigeon d'Eversmann"), I don't see why we should make a special exception for "of" in a contraction in English.
