### ISSUE TITLE
Mentioning Users in Observation Comments

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#179]
Often people don't know how to ID an observation but they know someone who might. 

I propose functionality that would recognize the @login notation in observation comments as a mention. This would render the notation as a hyperlink to a users profile within the comment while subscribing the mentioned user to the observation and generating an update that would appear in their dashboard similar to:
![screen shot 2013-11-27 at 12 02 00 pm](https://f.cloud.github.com/assets/598026/1634669/f6e8ccf0-579e-11e3-87c2-8a96d0287f9e.png)

Implementation (from Ken-ichi's comment below):

Create a plugin that allows any model to have a text field with mentions, so that we can write code like this:

```
class Comment < ActiveRecord::Base
  mentions_in :body
end
```

`mentions_in :attribute_name` should add an `after_save` callback that creates a delayed job to perform the mention scan. The mention scan should look through the record attribute for instances of `@username` and for each user, create an Update for which the resource is the record. So if Jenn mentions kueda in a comment 123, then the Update looks like

```
subscriber: kueda
resource: comment 123
```

The existing `has_subscribers` module behaves a lot like this and should be a good starting point. Mentioning could then be integrated into a variety of models, definitely Comment and Identification, but also Observation and Post.

If you're working on this and you're not Ken-ichi, please do all your work in your own fork and in a separate branch called "mentions."

**Comment by kueda** [comment]
FWIW, I tried writing a Joel-style functional spec for this to get in the habit: https://docs.google.com/document/d/10jBSjRvVL_85kdn_05NynyhPaGMt0T0jeJZpRozNWSk/edit?usp=sharing

Feel free to comment on that. I thought it was a useful exercise, so maybe in the future we can start using functional specs for hashing out new feature ideas and github issues for technical specs.

@snidge, we might need to build blocking in the future, but I'd prefer to try it more open at first to see if that's really a problem. Similarly I think project- or social circle-specific limitations would just decrease adoption.

**Comment by kueda** [comment]
Current status is on staging, and it's looking good. Some remaining things:

- [ ]  mentions in update emails should show the context like the dashboard does. Right now it just says something like "Comment mention"
- [ ] make @username links go to `/people/:login` instead of `/users/:id`
- [ ] updating mentionable text with a mention doesn't seem to generate an update for the mentioned user, e.g. if I make a comment, then edit it and add @pleary, @pleary doesn't get an update

**Comment by carrieseltzer** [comment]
This is great and I just wanted to add that I think working #359 (condensing nav bar notifications) into this would be awesome and help keep power users from being overwhelmed by mentions. I can imagine how quickly the notifications could balloon if ids, comments, and mentions are all triggering individual notifications.

**Comment by pleary** [comment]
The above tasks are mostly done. At this point I could use a final word on what we want the dashboard and emails to look like. I'm still playing around with how the Update is created (what is the resource and what is the notifier), and that largely depends on how we will display updates. Maybe @kueda and @joellebel you could take a look at the end of https://docs.google.com/document/d/10jBSjRvVL_85kdn_05NynyhPaGMt0T0jeJZpRozNWSk/edit?usp=sharing and make your recommendations. We currently have these kinds of mentions:
 - mention in Observation description
 - mention in Observation's comment
 - mention in Observation's identification remarks
 - mention in Post

I have a few more detail questions. On the dashboard, most items have a gear icon in the top right of each update asking to unsubscribe, but mentions are different in that we have two user settings to manage them. I have disabled the gear icon, but we could use it and just have it say something like 'go to your settings to manage mentions'.

If a user is mentioned in a comment, and the comment is later edited to remove the user's mention, should we delete the updates created the first time? (we do the opposite - if a comment doesn't mention a user and later is edited to mention a user, the user will then get updates)

What do we do about repeated updates? @alexshepard noted that I can mention someone in a comment their own observation, and they'll get an update about the comment and an update about the mention. Should one take priority? Or should we continue to show both. Maybe a better example is a post from a user you follow that mentions you. You'll get both updates, but the latter will display the user mention with some context rather than the first paragraph.

Similar to this, can I mention the same user in several different comments on the same ticket? I can see a valid use for this - I mention someone and they come and change something. A little later on I get new evidence or something and mention the person to get their attention again for the new detail - which could warrant two separate updates.

**Comment by kueda** [comment]
> At this point I could use a final word on what we want the dashboard and emails to look like.

I think I prefer the alternative at the end of the spec: mentioning user icon on the left, snippet of text including the mention as the main body of the update, and a small preview of the observation for mentions in comments and IDs. @joellebel , thoughts from UX perspective?

> I have a few more detail questions. On the dashboard, most items have a gear icon in the top right of each update asking to unsubscribe, but mentions are different in that we have two user settings to manage them. I have disabled the gear icon, but we could use it and just have it say something like 'go to your settings to manage mentions'.

Having the gear show a link to http://www.inaturalist.org/users/edit seems ideal to me. Let's do that.

> If a user is mentioned in a comment, and the comment is later edited to remove the user's mention, should we delete the updates created the first time? (we do the opposite - if a comment doesn't mention a user and later is edited to mention a user, the user will then get updates)

Hm, I feel like we should, thought that sounds really annoying to do. I guess the main problem is when you have an unviewed update that someone mentioned you, then you click through to see it and there's no mention, or the snipped of the text on the dashboard doesn't show the mention. Yeah, I guess we should delete them.

> What do we do about repeated updates? @alexshepard noted that I can mention someone in a comment their own observation, and they'll get an update about the comment and an update about the mention. Should one take priority? Or should we continue to show both. Maybe a better example is a post from a user you follow that mentions you. You'll get both updates, but the latter will display the user mention with some context rather than the first paragraph.

Hm again. For activity updates like comments, IDs, and mentions, I feel like we should not show duplicates and mentions should get the lowest priority, so if Alex comments on my observation and mentions me, I should get an update about the comment, not the mention. For content updates like observations and posts, I feel like we should show duplicates, so if I follow Alex and he posts and observation that mentions me, I will get the mention update in the header AND the observation update on my dashboard.

> Similar to this, can I mention the same user in several different comments on the same ticket? I can see a valid use for this - I mention someone and they come and change something. A little later on I get new evidence or something and mention the person to get their attention again for the new detail - which could warrant two separate updates.

Yes, I think we should generate one update per mentioned user per mentionable record, so if I leave 2 comments on an observation and mention Alex in each, he should get 2 updates. If I leave one comment and mention Alex twice in that single comment, he should get 1 update.

**Comment by pleary** [comment]
OK I think these things are pretty much done
 - The gear icon now links to users/edit for mentions
 - Updating something to remove a mention removes updates associated with that mention
 - We'll not generate a mention update if we've already generated another update for comments and identifications
 - But for observations and posts, we will generate multiple updates
 - A user can be mentioned more than once in different aspects of an object (obs description and comment for example)
 - The presentation of updates in the dashboard and emails seem ok, but could use some double checking

The last thing to check might be the new setting in users/edit. There are two ways to modify updates and I'm not sure if it's entirely clear as it is (the wording could at least be updated)

**Comment by kueda** [comment]
My only remaining recommendations would be to remove the label "Receive Activity Notifications From Mentions" from the settings (seems redundant), change the label on the checkbox to "Notify me of mentions (e.g. @username)", and translate that label into English and Spanish (latter using Google Translate). Otherwise I think this looks good to go.

**Comment by joellebel** [comment]
If the main goal of the mention snippet is giving a quick summary and getting the user to the observation, I'm finding the current format a bit overloaded and unfocused in terms of user direction. Currently, there are links to about 6 different places. Secondly, having the species name link to the observation is inconsistent with how we treat species links throughout the site. Lastly, people's dashboards tend to be pretty unruly, so we want to try and minimize text and extraneous links when we can. 

The most effective snippet would only contain links to the user and the observation... again if the main goal is to get the user to the ob (which it is, right?).

Lastly, the photo of the ob should also be a link to the ob.


### Proposed:

![image](https://cloud.githubusercontent.com/assets/11527994/9922165/3d01147a-5c9a-11e5-9df6-7aaf804afb73.png)


### Current: (for comparison)

![image](https://cloud.githubusercontent.com/assets/11527994/9922160/2cfa607c-5c9a-11e5-9368-ebe6e8217ccb.png)


The idea for gear icon linking to the main settings works for me. 

I haven't looked at the emails yet, but they take on the exact format as the dashboard, no?

**Comment by joellebel** [comment]
After a second glance... I don't think we need the "Posted by Kueda 3 days ago"? It's actually a little confusing. It makes it seem like the mention was posted 3 days ago.

**Comment by kueda** [comment]
I'm fine with trying that layout if Patrick has no objections. IMO, the goal is to get the viewer to the content in which they were mentioned, but I find it helpful to have as much info as possible to know why I should go there. E.g. if you leave a comment on an obs by Patrick that says, "What do you think, @kueda?" and all I see is that text and an image, my mental response will be "About what?" That's incentive to click through, but it's also annoying when I know the software could automatically answer that question for me. Anyway, not something that bothers me that much, just trying to explain myself.

I agree the "Posted by" should probably go.

**Comment by pleary** [comment]
Account settings updated:

<img width="270" alt="screen shot 2015-09-17 at 1 15 09 pm" src="https://cloud.githubusercontent.com/assets/48566/9940692/52b3d802-5d3f-11e5-8468-91fc2abdfe5c.png">
<img width="317" alt="screen shot 2015-09-17 at 1 15 32 pm" src="https://cloud.githubusercontent.com/assets/48566/9940693/552636f2-5d3f-11e5-8319-5241d1d720bc.png">
====
I've removed the "posted by..." and shuffled around the icons a bit to match what we currently have. Here is a mention in a comment, mention in an ID, and a display of a traditional ID (it has a mention but shown as a regular ID):

<img width="606" alt="screen shot 2015-09-17 at 1 22 42 pm" src="https://cloud.githubusercontent.com/assets/48566/9940703/61bb78dc-5d3f-11e5-9493-f9bb85a6ec8e.png">
====
And a post:
<img width="586" alt="screen shot 2015-09-17 at 1 27 16 pm" src="https://cloud.githubusercontent.com/assets/48566/9940801/d6f37eec-5d3f-11e5-8b2c-159629c950cd.png">

**Comment by joellebel** [comment]
A lot better!
