### ISSUE TITLE
Posting user to site_id = 2 returns an email in english, rather than site default language

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1825]
If I post a user as follows:
```
payload = {
  :client_id => app_id,
  :client_secret => app_secret,
  :code => auth_code,
  :redirect_uri => redirect_uri,
  :grant_type => "authorization_code"
}
response = RestClient.post("#{site}/oauth/token", payload)
token = JSON.parse(response)["access_token"]
headers = {"Authorization" => "Bearer #{token}"}

username = 'testscot1111'
email = 'testscot1111@gmail.com'
password = 'testscot1111'
site_id = 2

results = RestClient.post("#{site}/users.json?inat_site_id=#{site_id}", {"user[login]" =>
username, "user[email]" => email, "user[site_id]" => site_id, "user[password]" => password,
"user[password_confirmation]" => password}, headers)
puts "created https://www.inaturalist.org/users/#{JSON.parse(results)["id"]}"
```
I get the following email which is in english rather than Spanish (the default language of site_id 2)
<img width="627" alt="screen shot 2018-06-20 at 4 06 17 pm" src="https://user-images.githubusercontent.com/598026/41689462-8977f79e-74a5-11e8-8543-89ca7b38009b.png">

**Comment by kueda** [comment]
The problem here was a bit unexpected: when you authenticate as a user, and then try to create a user, the default locale is that of the authenticated user instead of the site, so your new users were actually inheriting your locale. Users should not be able to create new users, so I'm going to make it generate an error when you try to do that, but the solution for your script is to remove all that stuff  about getting an oauth token and including in the http headers.
