### ISSUE TITLE
Resource Owner Password Credentials Flow does not work any more?

### ISSUE THREAD

**Issue by ptgamr** [inaturalist/inaturalist#1864]
I follow Resource Owner Password Credentials Flow in this guide but it seems not working for me: https://www.inaturalist.org/pages/api+reference#authorization_code_flow

I received some sort of token like this

```
POST https://www.inaturalist.org/oauth/token

{
    "access_token": "ffaa8aeba7bf0357100987fexxxxxxxxxxxxxxxxx",
    "token_type": "bearer",
    "scope": "write",
    "created_at": 1533035451
}
```

When I'm requesting an auth required API, it just simply return me 500, without any error saying what's wrong.

```
GET /v1/users/edit HTTP/1.1
Host: api.inaturalist.org
Content-Type: application/json
Authorization: Bearer "the____above_____token"
Cache-Control: no-cache

{
    "error": "Error",
    "status": 500
}

```

I might missed something, if that is the case would be great if somebody could point me out.

Thanks

**Comment by pleary** [comment]
If you look at the documentation at http://api.inaturalist.org/v1/docs/#!/Users/put_users_id you'll see the route in the new API to edit a user is PUT `/v1/users/:id`, not `/v1/users/edit`. I just made a test call and it worked for me. I used the JWT authentication token https://www.inaturalist.org/users/api_token instead of the oauth Bearer token, but in theory either should work. My call was something like this:

```
curl -XPUT api.inaturalist.org/v1/users/:id -H "Authorization: __YOUR_JWT__" -d '{
  "user": {
    "description": "Testing"
  }
}'
```
