### ISSUE TITLE
Add a "no results for _____" to Search Results page if there are no exact hits

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1868]
via bouteloua:

The search results page will show results that are close to what the search term was, which may be confusing. For example, before the genus Viettealna was added to iNat, this was the results page:

![image](https://user-images.githubusercontent.com/15896181/43501834-6184a2e6-950c-11e8-8191-04793999a5a5.png)

Adding a large "no results for Viettealna" above the suggested results would make it more straightforward that the search term itself had no match.

**Comment by kueda** [comment]
While I'm not convinced this is desirable, I'm also not entirely sure this is possible. Is the intent to make this *only* work for taxa? What do we do when search returns a taxon b/c it matched an outdated name, or a common name that you don't see by default? For example, if I search for "oregon myrtle" I see a taxon named "California Bay" b/c that's the common name in California, and there's no mention of Oregon myrtle. Do we show the "no results" notice then even though there clearly is a result?

IMO, we should just not do this.

**Comment by boucur** [comment]
Could be for any type of thing, not just taxa.

I personally wouldn't mind if the "no results found for [search query]" alert did _not_ display when it's matching on "hidden" information like the common name Oregon myrtle.

But ideally, and this is really a separate issue/suggestion, the search results would hint at why it's matching on Oregon myrtle in the first place, e.g.:
**search: oregon myrtle**
instead of the text:
> "Umbellularia californica is a large hardwood tree native to coastal forests of California, as well as to coastal forests extending into Oregon. It is endemic to the California Floristic Province. It is the sole species in the genus Umbellularia."

it might clarify why it's in the results by including and bolding the search query text like:

> "Umbellularia californica is a large hardwood tree native to coastal forests of California, as well as to coastal forests extending into Oregon....Common Names: California bay, California bay laurel, **Oregon myrtle**, pepperwood...

<a href="https://www.google.com/search?rlz=1C1GGRV_enUS751US753&ei=qryNW-CWBaSwjwTE_YAI&q=%22oregon+myrtle%22&oq=%22oregon+myrtle%22&gs_l=psy-ab.3..0l2j0i10l7j0.166538.168590..168741...0.0..0.80.933.15......0....1..gws-wiz.......0i71j0i131j0i67.p3YJ9gNKvn4">Here's how Google handles it</a> in their snippet from the WP page:
> "Umbellularia californica is a large hardwood tree native to coastal forests of California, as well ... In Oregon, this tree is known as **Oregon myrtle**, while in California it is called California bay laurel, which may be shortened to California bay or ..."

**Comment by kueda** [comment]
IMO, term highlighting is addressing part of the issue here, and it's not entirely clear to me if we even can know when there was no exact match, so I'm going to close.

**Comment by boucur** [comment]
The term highlighting is great to have and I agree, a reasonable alternative to a "no exact results for _____" message if that's not possible. But it looks like it's currently highlighting some non-matching text. 

Example: https://www.inaturalist.org/search?q=bouteloia
There are no actual results for "bouteloia" but it highlights fuzzy matches "bouteloua", "Bouteldja, ET, DZ", t"boutelier", and "Boutelou".
