### ISSUE TITLE
Can't select text in uploader obs description field in Firefox

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2091]
When using the uploader, if one types text in the desciption field on an observation's card and then tries to select the text, it is not possible in Firefox. Text _can_ be selected on the left-hand side of the page, however. 

Here's a console shot, in case it helps:

![image](https://user-images.githubusercontent.com/15896181/50403911-72bc4100-0757-11e9-8973-021424b250ce.png)

**Comment by kueda** [comment]
This is a known bug with firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1189486. [This solution](https://stackoverflow.com/questions/21680363/prevent-drag-event-to-interfere-with-input-elements-in-firefox-using-html5-drag) won't work for us because the `react-dnd` lib doesn't really grant us control over the `draggable` attribute.

**Comment by tiwane** [comment]
Bummer.
