### ISSUE TITLE
Subscribe to places available in Explore

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2148]
I'd love to be able to add to my feed locations that are available in the Explore view. However it seems that the subscribe option in the dashboard only exposes a subset of locations (for example I can filter by location "Gamboa, Panama" in Explore, but can't subscribe to it). I don't know if this is a bug that can be fixed or a known limitation because the two functionalities are served by different backends.

**Comment by kueda** [comment]
We decided to base the main place search on Explore on the Google Places API, which is pretty close to what you get when you search for a place on Google Maps. It's really good in that it has a ton of places so you'll almost always find what you're looking for and be able to zoom the map into that general area, but it's not quite the same as iNat places because we can't get access to the actual shape of the place from Google. For example, when you search for "washington monument" you get observations from a rectangle around the Washington monument, because that rectangle is the only thing we can get from Google. If we only relied on Google for places, it would be impossible to search for observations from California without getting almost all the observations from Nevada as well. So the Google thing is convenient for Explore searches, but it wouldn't be adequate for subscriptions, which our users tend to expect to be pretty geographically precise, e.g. people want to subscribe to plants from California without having to get everything from Nevada too.

**Comment by dartar** [comment]
@kueda thanks for the explanation and additional context. Makes sense. I wonder if there’s any other source of shapefiles you could use to increase the number of subscribable places. OSM has this list but I don’t know about their quality or coverage: https://wiki.openstreetmap.org/wiki/Shapefiles

Somebody who would definitely know is @nyurik

**Comment by kueda** [comment]
Places create a lot of technical (lots of re-indexing) and social (lots of complaining) burden for us, so even if we *could* get perfect borders for every known place, I don't know if we'd want to take a different approach than our current one, i.e. just let very motivated individuals create places if they want to.
