### ISSUE TITLE
Some D. aurantiacus obs retain RG status even with a CID at section level

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2160]
EG:

https://www.inaturalist.org/observations/14406011
https://www.inaturalist.org/observations/14111138

**Comment by kueda** [comment]
I wasn't able to replicate this in tests, so my best guess is that something went haywire when these changes were processing, e.g. a prematurely finished delayed job or something. I went through and reset the community taxon on all obs of Diplacus, which updated 137 observations, and also reset the identification categorization, since a bunch were incorrectly marked as "maverick."
