### ISSUE TITLE
Add place as an option when adding a new common name

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2254]
Currently, if one adds a new common name, one has to save the name then edit it in order to associate it with a place. Can we add the place association tool to the name creation page?

**Comment by carrieseltzer** [comment]
This came up in discussion in Merida, and again with onboarding ArgentiNat. Seems like it should be a minor change to add the places option on creation, instead of just when edited. 

![Screen Shot 2019-11-18 at 9 31 23 PM](https://user-images.githubusercontent.com/7501183/69111297-26eb4800-0a4b-11ea-8340-8b813781668a.png)

**Comment by boucur** [comment]
Just linking back to the feature request so it can be marked solved when this is implemented: https://forum.inaturalist.org/t/add-places-section-to-new-common-name-page/3008

**Comment by tiwane** [comment]
Looks good on staging.
