### ISSUE TITLE
Adding translation validators on Translatewiki.net 

### ISSUE THREAD

**Issue by Abijeet** [inaturalist/inaturalist#2333]
Greetings,

I work with Niklas on the @translatewiki team. 

We've recently developed a new validator framework that block translators from saving translations that have errors. Errors vary based on the project and have to be configured accordingly. 

Based on past discussions [[1](https://github.com/inaturalist/inaturalist/pull/2212#discussion_r271447917)], we've identified iNaturalist as a project to test the new validator framework with.

**What validations do translations need?** 

Translatable strings often contain markup that should be retained as-is in the translation. Typing that markup can be slow and difficult because special characters are common. Translatewiki can provide translators a button clicking on which inserts the piece of markup into the translation to the current cursor position. In addition, if a translation is missing that specific markup, Translatewiki can either warn the translator or simply reject the translation, since such markup is usually mandatory to display the messages properly to the end user.

We've analyzed the strings present in the project and have come up with the following insertables,

1. Regex to match strings like -  `%{user}`, `%{max}` 
   - Should translators be shown a warning or blocked from saving translations that have these markup's missing?
   - Should the regex be case sensitive?
2. Regex to match plurals like - `{{PLURAL|one=1 photo|%{count} photos}}` - Translations should have `{{PLURAL|` and end with `}}`. We convert the plurals into this format during import.
   - Should translators be allowed to save translations that do not have these?
3. Regex to match strings like - `&abc;`, `&raquo;`
   - Should translators be shown a warning or blocked from saving translations that have these markup's missing?
   - Should the regex be case sensitive?

The plan is that if the English text has any of these strings, than the translation must contain them too. If it is not present, the translator will not be able to save the translation. We can also make it so that the translator is just warned but is still allowed to save the translation.

Have we covered all the possible markup values? Please let us know if we can move forward with this and if you have any other inputs.

**Comment by Abijeet** [comment]
WIP patch - https://gerrit.wikimedia.org/r/c/translatewiki/+/523725

**Comment by kueda** [comment]
> 1. Regex to match strings like -  `%{user}`, `%{max}` 
>    - Should translators be shown a warning or blocked from saving translations that have these markup's missing?

Not sure what you mean here. When the source file (`en.yml`) has a variable like `%{user}` but the translation does not, the translator should get a warning. If the translation has a variable that the source string does not, the translator should be blocked from adding that translation.

>    - Should the regex be case sensitive?

Yes, all variable names in our translations are lowercase and underscored.

> 2. Regex to match plurals like - `{{PLURAL|one=1 photo|%{count} photos}}` - Translations should have `{{PLURAL|` and end with `}}`. We convert the plurals into this format during import.
>    - Should translators be allowed to save translations that do not have these?

The format you use internally doesn't concern me, but I am concerned about the format you *export* and commit to github. `{{PLURAL|one=1 photo|%{count} photos}}` is not a format that works for us. We need the yaml to look like

```yaml
x_photos:
  one: 1 photo
  other: %{count} photos
```

Also, if there is a plural, we need both `one` and `other` keys. Missing either of those will result in an error, so we filter out all plural translations that lack `one` or `other`.

> 3. Regex to match strings like - `&abc;`, `&raquo;`
>    - Should translators be shown a warning or blocked from saving translations that have these markup's missing?
>    - Should the regex be case sensitive?

HTML entities should match the source string, so if the string in `en.yml` is `Foo &abc;` then the translation should be `Bar &abc;`, and if the source string is `Foo abc` then the translation should be `Bar abc`. Attempts to add or remove HTML entities should be considered errors.

**Comment by Abijeet** [comment]
Hi @kueda 

Thanks for your inputs. We will keep this in mind when developing the validators.

**Comment by Abijeet** [comment]
Hi @kueda 

> HTML entities should match the source string, so if the string in en.yml is Foo &abc; then the translation should be Bar &abc;, and if the source string is Foo abc then the translation should be Bar abc. Attempts to add or remove HTML entities should be considered errors.

I was discussing this with Niklas, and he mentioned, 

Possibly we don't want to enforce this or treat it as errors. Some translators might prefer using the unicode symbols here.

There are also some uses of hex-entities such as `&#58;`

**Comment by verdy-p** [comment]
one caveat is that such plural rule does not work when you don't specify the numeric value to test: there are various messages where there are several conditional plurals in the same text, but not the same number applies to all of them. So the PLURAL markup has to be used several times in the message, and then we need to specify which value is tested.
In Mediawiki the syntax is:
`{{PLURAL:value|1=singular text|other text}}`
But the selectors before the equal sign is not necessarily a number (1 here) it should be symbolic
`{{PLURAL:value|one=singular text|other=other text}}`
For example:
`%{count} {{PLURAL:%{count}|one=image|other=images}}`
so that the singular will also apply correctly depending on the language (e.g. in French, zero to one is singular, as well as negative values from -1 to 0; plural is for absolute values larger than 1; in English, singular is only used for the absolute integer value 1.
For example:
`{{PLURAL:%{count}|one=une image|2=deux images|other=plusieurs images}}`

If a fews cases, even in languages that only have two number classes (designated as "singular" and "plural" though their meaning is language-dependant), there's a need to specifialize translations for specific values (like 2), so number class are useful as selectors, and can be optionally completed by exact numeric values (or sometimes by ranges).

CLDR defines number classes more consistently using symbolic assignments too; depending on languages there may be more than 2 number classes (singular, dual, paucal, plural... sometimes more for partitive like fractions and non-integer values), and they are defined in a language-specific ordered set: one, two, few, many, other (all languages have a "other" number class used as the default, we then define conditional plurals in translations)

We need a consistant way to mark translations that use conditional "plural" rules (actually number classes) with correct selectors, and a way to specify the numeric value to test (as it cannot be guessed from the content of the message as there's not necessary any inclusion of the number itself in the translated branches: an API cannot guess which value to test for correctly selecting the correct conditional branch.

I much prefer the MediaWiki syntax which is clearer, as long as it supports the common CLDR number classes. As well the default/other text should be explicitly tagged: there's a known problem when the content of a translated branch containts an equal sign, notably with HTML attributes markup like:

`{{PLURAL:%{count}|one=<span class="value">une</span> image|2=<span class="value">deux</span> images|other=<span class="value">plusieurs</span> images}}`

if you suppress the explicit selectors (marked by the "=" sign) and just assume that the branches are just listed in implicit order (1, 2..., other) this does not work as expected:
`{{PLURAL:%{count}|<span class="value">une</span> image|<span class="value">deux</span> images|<span class="value">plusieurs</span> images}}`
because a parser will detect multiple branches having dummy selectors (here they are all identical and are `<span class`, so the whole PLURAL rule stops working): explicit tagging of branches is then highly recommended (and even required in wellknown cases for some languages that require additional markup even if it's not needed in English, for example with several non-Latin complex scripts, including hieroglyphs, or markup needed for correct typography like superscripted abbreviation marks in French, or markup needed for BiDi)

**Comment by verdy-p** [comment]
"attempts to remove or add standard HTML entities"
No this is not an error, as long as the translation itself is intended for HTML, as this is canonically equivalent. Now is it is intended for Mediawiki markup, there is the frequent need to insert some entities to replace the implicit Mediawiki markup when the actual character is wanted (e.g. `&#58;`instead of `:` anywhere inside a line starting by a ";" mediawiki markup.
What is important is to know and track the target language parser that will use the translated item, so that their requirements are met, and the equivalences are properly recognized.
Unfortunately, there are lot of translations in translatewiki which do not specify correctly which language parser will be used to load the translations (HTML, MediaWiki, plain-text/no parser, C, C++, PHP, Lua, Javascript/JSON) and this also affects how placeholders will be recognized.

**Comment by nemobis** [comment]
https://translatewiki.net/wiki/Thread:Support/iNaturalist_Leaving_Translatewiki

**Comment by Abijeet** [comment]
As per,
> https://translatewiki.net/wiki/Thread:Support/iNaturalist_Leaving_Translatewiki
