### ISSUE TITLE
Can't add synonym to taxon if one's language is English

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2364]
Trying to add a synonym (a not currently accepted scientific name) to a taxon, if your locale is English, results in this error:

![image](https://user-images.githubusercontent.com/15896181/62989454-da192500-bdfc-11e9-9885-37590ba2af55.png)

Change to another locale (I've tried Spanish and French) and the synonym is accepted. I believe this only affects "regular" users (not staff, curators, site admins).

**Comment by kueda** [comment]
The deviation from intended behavior here is that users in non-English locales can add what looks like a scientific name but is actually just a name in a weird lexicon that is "scientific names" translated into their own locale, e.g. if you do this in Spanish, you add a name in the "Nombres Científicos" which is not actually the same as "Scientific Names."

I can fix that, but it sounds like you're also lobbying to allow non-curators the ability to add scientific names. Is that the case? I'd prefer not to to that since I just foresee it as a way non-curators will try to circumvent our taxonomy.

**Comment by tiwane** [comment]
I wasn't aware of that. The users said they had been able to add synonyms while their locale was EN until a few days ago, so it sounded like a bug. Did something change?

Otherwise, I agree that non-curators shouldn't add scientific names.
