### ISSUE TITLE
New Collection Project Data Quality - Edit screen shows only RG checked, but actual requirement is "any"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2412]
1. Create a new collection project.
2. For Data Quality only RG is checked:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/15896181/65566091-b4f0f980-df06-11e9-99ab-042a6ace7bce.png">
3. Create the project, but don't touch the Data Quality section.
4. Project requirements shows "any"
<img width="366" alt="image" src="https://user-images.githubusercontent.com/15896181/65566133-d3ef8b80-df06-11e9-9b96-d445e0ecadfe.png">
eg https://www.inaturalist.org/projects/test-test-test

Can we mark RG and Needs ID by default (https://github.com/inaturalist/inaturalist/issues/2204) and make sure they are applied to the project?

**Comment by kueda** [comment]
@tiwane, there's a fix for this on gorilla right now if you want to test it. The underlying problem was that the form was showing Research Grade as checked by default, but that choice wasn't getting saved unless you changed the Quality Grade preference. I fixed that so now the choices on the form should actually get applied even if you don't fiddle with it, and the Requirements should match that choice. However, there are presumably some projects out there who thought they were set up to include only RG obs but are actually including all obs. Not sure what you want to do about that. IMO, leave them be, since we can't really distinguish between people who chose to have no quality grade filters and people who accepted the default.

**Comment by tiwane** [comment]
This is looking good on Gorilla. Agreed we can leave current projects be.
