### ISSUE TITLE
Local installation problems

### ISSUE THREAD

**Issue by benkeen** [inaturalist/inaturalist#2479]
Hi! I've been trying to get the inaturalist app installed locally, but no luck just yet.

Most of it worked fine: localhost:3000 boots up and I see the site, the node API is running on 4000 (though it complains about redis - didn't see any instructions on getting that going), and elasticsearch is running on port 9200. However I can't seem to create a user and populate it with dummy data. Running the following command doesn't create a user in the `inaturalist_development` table (presumably that's where it should end up?) so a later call to load the dummy observation data complains there's no user defined.

```ruby
rails r "User.create( login: 'testerson', password: 'test', password_confirmation: 'test', email: 'test@test.com' )"
/Users/benkeen/.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/benkeen/.rvm/gems/ruby-2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
```

No errors to speak of. Any tips on how to debug? I'm a front-end guy and not familiar with ruby. 

Also, if it's relevant, the only other problem I noticed was that attempting to populate the data (e.g. `rails r tools/import_natural_earth_countries.rb`) throws a bunch of "Place geometry can't be blank" errors when trying to add each row, so maybe I screwed something else up with the setup. 

```
[INFO] Working on shp...
[INFO] 		Made new place: <Place id: , name: Sierra Leone, admin_level: , place_type_name: Country, lat: 8.4515380859, lng: -11.7879394531, parent_id: >
[ERROR] 	Place invalid: Place geometry can't be blank
```

**Comment by kueda** [comment]
Hm, try doing the same thing in a console: use `rails c` and call `User.create!(...)` from there. I'm pretty sure you're running into the validation that the password has to be 6 chars or more, but rails r isn't showing it to you b/c it's just returning an invalid user and closing out. Using `create!` vs `create` will force it to raise exceptions for the validation errors. You could also do something like

```ruby
u = User.create(...)
puts u.valid? ? "yay, it is valid" : u.errors
```

Little bit weird that the API is complaining about redis, but I think you just need to install it and run `redis-server` (I'm on a Mac and use homebrew so this would be `brew install redis`). The only part of the API that depends on this are the computer vision endpoints, which aren't going to work without the model anyway (which we don't publish at present).

For the Natural Earth script, looks like there was a bug, should be fixed in my last commit. Not... entirely sure that script ever really worked properly, but I think it will now.

**Comment by benkeen** [comment]
Brilliant, thanks so much @kueda! Yes, the password being too short was the problem. The user + data has been populated. Happy to put in a quick PR tonight to tweak the doc. I still don't see anything returned in the UI from the observation request, but I can troubleshoot that tonight.

Regarding Redis, it was just throwing some errors when running `node app.js`. Installing it & running the server works just fine. 

Thanks again! I look forward to tinkering with this tonight.
