### ISSUE TITLE
Add functionality to unfollow one's own observation

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2501]
From: https://forum.inaturalist.org/t/create-a-way-to-unfollow-ones-own-observations/103

One is subscribe to one's own observations automatically, and there's no easy way to unfollow one's own observation. Some users don't want notifications for new ssp IDs and such, so they're requesting that the same "Follow" button be added to their own observations. I would say let's put it to the left of the blue Edit buttons, but am open to other suggestions. It should also only show the unfollow observation option, not the user following option.

![image](https://user-images.githubusercontent.com/15896181/70191719-8cc40a80-16ae-11ea-8a4e-59e128896150.png)

**Comment by pleary** [comment]
I'm not sure how to accomplish this. People can subscribe to others' content, but there is no actual subscription to one's own observations. Rather the code will just alert the observer for relevant actions. We don't have the concept of an "unsubscription", and since users aren't "subscribed" to their own content there is no subscription to be removed.

I guess we could add a `preference` to observations that say don't alert the observer when new content is added. We also need more detail as to what this would do. Sounds like they don't want notifications on IDs, but would the user still get notifications comments on the observation? Mentions?

**Comment by tiwane** [comment]
I think the impetus behind this request was mainly to not be notified of subspecies IDs. Withe notifications revamp, that won't be necessary so I'll close this.
