### ISSUE TITLE
"Joined" date on profile page can sometimes display as after the last active date 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2524]
From: https://forum.inaturalist.org/t/date-joined-is-after-date-last-active/169

eg ![image](https://user-images.githubusercontent.com/15896181/71057595-14c7fc80-2112-11ea-8ea4-25b6b6f40028.png)

I assume this is because the date joined is dependent on the user's time zone setting?

**Comment by pleary** [comment]
The problem here is the `last_active` field on users is a date field, whereas the `created_at` field is a time field. That means when we record last_active, we're doing a timezone conversion before recording, using the TZ of the current user. But when we display the created info, we do conversion on the fly to the TZ of the viewing user.

What I've done for now is add a defensive check and if the date active would be before the date joined, just show the date joined instead. So the issue described here shouldn't pop up anymore.

Another option would be to change `last_active` to a time field. If we do that we might want to consider only exposing that as a date in things like the API, so we don't expose precise information about when people are using the site.

**Comment by tiwane** [comment]
OK, thanks.

**Comment by pleary** [comment]
I haven't heard any more reports about this, so I'll just close it. If we see it again we can do the more thorough fix changing field datatypes
