### ISSUE TITLE
JSON pages showing old favicon, at least in Chrome

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2570]
eg https://www.inaturalist.org/observations/38010454.json

<img width="344" alt="image" src="https://user-images.githubusercontent.com/15896181/73207172-19140c00-40f9-11ea-94ff-7456618987b9.png">

Doesn't show any favicon in FF.

**Comment by kueda** [comment]
Note that this matters very much, but I assume this is due to the `favicon.ico` we have, which indeed should probably get updated, but that raises the related question of why I don't see a favicon for https://naturalista.mx/observations/38021399.json

**Comment by pleary** [comment]
I looked into this a little and there appear to be a few separate issues. Firefox is failing to show the favicon due to an issue with the Content-Security-Policy, and problem I've only seen in FF. For whatever reason it is applying a different CSP behavior for .json requests than other requests, and as a result is blocking the favicon loading on URLs like https://www.inaturalist.org/observations/38010454.json. Chrome, Brave, and Safari seem to render the favicon at the URL without issue.

However they do not show the favicon at https://naturalista.mx/observations/38021399.json for a few compounding reasons. Firstly we do not redirect .json requests based on domain or HTTPS reasons, I believe due to a concern the mobile apps, and if I recall Android specifically, would not be able to follow the redirect chain. If this is not the case, or can be resolved in the app, we should stop making this exception and redirect all requests all the time regardless of their request method or extension.

But since we are currently making this exception, https://naturalista.mx/observations/38021399.json will be loaded at that URL even though https://naturalista.mx is not the preferred domain for that site. When the browser checks for the favicon for that domain, it'll request https://naturalista.mx/favicon.ico which _will_ be redirected to the preferred domain because it does not have a .json extension. The redirect happens by first going through http://www.naturalista.mx due to how we set up redirects (redirect happens after SSL termination and at that time we do not know the original request was using HTTPS). Seems like that hop through the non-SSL URL http://www.naturalista.mx is causing the favicon not to load due a security issue. This is something you wouldn't see on a normal web page because the redirect to the proper domain would happen before the favicon was requested by the browser, and because we have HTTP headers in pages where we control the content which point to the preferred favicon URL.

Finally, and an issue distinct from all of this, we should update https://www.inaturalist.org/favicon.ico to the new logo, or create a new default one browsers could pick up if we can't specify it in an HTTP header and remove that is currently there. And we might consider changing how that URL resolves so partner sites can have their own site logos at this URL that is checked by default by browsers - e.g. https://www.naturalista.mx/favicon.ico would preferably return the icon for the Naturalista site.

I'll fix the favicon for the https://api.inaturalist.org/
