### ISSUE TITLE
Add option to associate a network site with an EEZ in addition to a primary place

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2572]
Currently, sites are affiliated with only a single place. For purposes of data sharing with network members, observations from the EEZ should also be included. Therefore, each site should be able to have an affiliated EEZ in addition to the "Place". 

Data sharing with network members means all of the observations within those bounds, including:
-true coordinates where `geoprivacy` = `obscured` or `private` only for users affiliated with the network member
-true coordinates where `taxon_geoprivacy` = `obscured` or `private` if geoprivacy = open or null. 

e.g. iNaturalist.ca uses `place_id=6712` for the land area but should also be associated with "Canada EEZ" (`place_id=131560`): https://www.inaturalist.org/places/canada-eez

**Comment by kueda** [comment]
Addendum: we will also need to update `export_site_data.rb` so it takes this additional place into account when exporting data. We do *not* need to change `export_site_archive.rb`, because this additional data is not required when creating an archive a member takes with them when they leave the network.
