### ISSUE TITLE
Collection projects - if months are part of the project requirements, they're not shown on the project page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2646]
From: https://forum.inaturalist.org/t/collection-filter-for-months-not-displayed-on-project-about-page/5479

eg https://www.inaturalist.org/projects/aetagragda I've chosen Jan, Feb, March, April as project requirements, but those are not displayed on the project page:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/15896181/79300654-348ee780-7e9c-11ea-9d0f-4f8e39e9e84a.png">

**Comment by boucur** [comment]
Since it's preeetty related, can I just roll this related issue into this one?

The start is Jan 1, 2020 and end is Dec 31, 2020, but the year isn't displaying here:
https://www.inaturalist.org/projects/the-sidewalk-botanist-scavenger-hunt-2020

![image](https://user-images.githubusercontent.com/4712407/79513640-f1eb1d80-8009-11ea-8d1f-b4c3c0d48462.png)
