### ISSUE TITLE
Don't include inactive taxa in Compare results

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2647]
When using Compare and basing the results on checklists or observations, we show inactive taxa as options. Let's show only active taxa.

**Comment by cmcheatle** [comment]
What's the purpose of leaving inactive taxa on checklists at all ? As opposed to excluding them from the display, is there a reason not to simply remove them from checklists.

The only possible reason I can see is to support observations with a single ID which is an inactive taxa but stuck there because the user has opted out of community ID's and taxa update ID changes, and the user wants their checklist to show the inactive one, and do we really need to defer to that use case ?

**Comment by kueda** [comment]
Should have been fixed in https://github.com/inaturalist/iNaturalistAPI/commit/f46feab19c4d3bcaae898d00f041729fb21ab8b8
