### ISSUE TITLE
place name geoprivacy

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#265]
I recently changed it so the manually entered place names for obs with private or obscured coordinates won't show up on observation pages, and obs lists (e.g. http://www.inaturalist.org/observations/kueda), but this is mostly a gesture, since they will still show up on calendar views (e.g. http://www.inaturalist.org/calendar/kueda/2014/5/18), and they can still be searched for by anyone (e.g. if you enter "Park X" as the place name for an obscured observation, it will still turn up in searches for "Park X"). These things can be addressed, but I think they might be overkill. At least for the search issue, there's still nothing we can do to stop people from entering "Park X" in other text fields like the tags or the description.

Is it worth addressing these issues? I'm loath to proceed along this path b/c frankly these are all half to quarter measures. If you add a bunch of obs from a place including a few obscured ones, it's kind of easy to figure out roughly where the obscured ones were, unless the rest of your obs are spread out over a very wide geographic area.

**Comment by loarie** [comment]
Just to add to the threatened species management improvement list (in addition to 1 & 2 in my comment above) a third: (3) round date of threatened obs to day or month (to make it harder to interpolate positions from other observations taken immediately before/after) has been mentioned in the google group

**Comment by naturalistcharlie** [comment]
Sorry I missed the other email... agreed on rounding of date. Also on
rounding of coords... for instance I have to manually obscure stuff from
our property because it isn't very big and i observe hundreds of things
here... I am not the most paranoid person but it seems like with so many
observations it would be really easy to find where I live otherwise. So I
manually place each one at an intersection in the town where we live so
that we are within the uncertainty buffer which is not ideal.

On Wed, Feb 25, 2015 at 7:35 PM, Scott Loarie <notifications@github.com>
wrote:

> Just to add to the threatened species management improvement list (in
> addition to 1 & 2 in my comment above) a third: (3) round date of
> threatened obs to day or month (to make it harder to interpolate positions
> from other observations taken immediately before/after) has been mentioned
> in the google group
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/265#issuecomment-76097636>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
FYI, we are now storing the original `place_guess` and the obscured `place_guess` separately. I still need to make some changes to get the node API to use this new data.
