### ISSUE TITLE
Don't include observations in search results for "with photo" filter if all of the observation's photos are flagged as copyright infringement

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2657]
From https://forum.inaturalist.org/t/filter-copyright-infringement-as-no-photo/11348

Not sure if it's possible, but it when searching for observations that have a photo (eg https://www.inaturalist.org/observations?photos&place_id=any), can we not display observations for which all their photos have been flagged as copyright infringement?

**Comment by kueda** [comment]
Hm, looks like we're using the `photos_count` attribute in the in the observations index to do that, so we could

1. Only set that to the number of photos without unresolved copyright infringement flags, reindex all observations with photos with unresolved copyright infringement flags, and live with the fact that this number is basically inaccurate in the index, e.g. never be able to use ES to look up all observations with photos regardless of copyright status, or
1. Add a separate attribute like `visible_photos_count` which is the number of all photos the obs has that do not have unresolved copyright infringement flags and re-index *all* observations

@pleary do you have a preference, or another alternative?

**Comment by pleary** [comment]
Neither option is all that great, but I think we can get away with 1 and I guess I prefer that. It'll be a little confusing since there is an attribute on observations in the DB `observation_photos_count`, which we're not using to populate the ES index but still they're likely to be the same now. And as you say we'll still be limited to using photos_count to only consider photos w/o flags. But that's the only way we're using that count now anyway. We're also stripping out photos_count from API response so we won't be affecting API users.

If we wanted to add a new attribute, I think I'd prefer it to be something like `flagged_photos_count` so we only have to re-index obs w/ flagged photos and not all obs with photos.

**Comment by kueda** [comment]
`flagged_photos_count` sounds tempting, wouldn't that mean we'd need to use a potentially expensive script filter to support the `photos=true` param, e.g. "show me obs where photos_count - flagged_photos_count == 0"?

**Comment by pleary** [comment]
yep. We could probably formulate it so we'd only need to run a script on obs which flagged photos `(photos_count > 0 AND (flagged_photos_count === 0 OR *script*)`. Another not great option. I suppose if we're planning on rebuilding the obs index at some point then my concern with indexing could be moot. Reindexing is just such a pain I don't really want to do it just for this.

I still prefer option 1 since we use photos_count for only one thing - searching for obs with photos w/o consideration for who's searching. I am not too worried about potential future searches - if we want to add new features we can add new fields or rehash this discussion then

**Comment by tiwane** [comment]
IMO this isn't a big issue, so if the solution isn't great, might be worth it.
