### ISSUE TITLE
TaxonNames exist without taxa

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2730]
**Describe the bug**
This is not good:
```
2.6.5 :015 > TaxonName.where( "taxon_id is null" ).count
 => 3104 
```
It's causing a crash on `TaxonNamesController#edit` when the name has a synonym that is missing a taxon. Some of these records were created in July 2020 so it's definitely a current, active bug.

**To Reproduce**
Go to https://www.inaturalist.org/taxon_names/1372094/edit, or if that's been fixed, search for TaxonName records with no taxon.

**Expected behavior**
TaxonNames should always have a taxon

**Comment by loarie** [comment]
@kueda this is happening because if a name provider doesn't return a rank ratatosk fills in species if its a binomial but other wise sets it to nil
https://github.com/inaturalist/inaturalist/blob/main/lib/ratatosk/lib/ratatosk/name_providers/eol.rb#L228
we now validate that taxon records have ranks to save so when ratatosk saves the taxon_name and the associated taxon it creates the taxon_name saves but the accompanying taxon fails the validation and does not.

Can I fix this by setting the missing rank to "subspecies" if its a trinomial to catch some of these cases and otherwise bailing if there's no rank? (ie not saving the taxon name or the taxon?)

**Comment by loarie** [comment]
Ok this branch fixes this for EOL as described above. I can't reproduce this bug with CoL etc and all the recent cases are coming from EOL so I suspect this change for just handling EOL external names is sufficient to fix this. https://github.com/inaturalist/inaturalist/tree/issue_2730_fix
