### ISSUE TITLE
Adding ID to a "unknown" obs with withdrawn ID makes your ID a disagreement to withdrawn ID

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2751]
From https://forum.inaturalist.org/t/disagreeing-with-a-withdrawn-id-doesnt-change-it-from-unknown/7964

1. Find an "unknown" obs that has a withdrawn ID (or create one).
2. Add an ID to it.
3. Your ID is added, then is changed to a disagreeing ID.

![image](https://user-images.githubusercontent.com/15896181/88710846-0f7d5800-d0cc-11ea-848b-d60cd6193a3b.png)

If original ID is deleted, the second ID is still a disagreeing one.

![image](https://user-images.githubusercontent.com/15896181/88711000-54a18a00-d0cc-11ea-90b2-320b67449f74.png)

**Comment by todtb** [comment]
Looks like a few things going on here:

- [ ] An identification added to an observation without any current identifications should not be a disagreement

- [ ] Deleting an identification should update any other identification that was in disagreement to no longer be disagreements

#2769 Addresses the first

**Comment by kueda** [comment]
While #2769 seems harmless and sensibly defensive, I'm pretty sure the more serious problem is at https://github.com/inaturalist/inaturalist/blob/main/app/models/identification.rb#L182, where we are trying to handle the situation when you are disagreeing with yourself and you are the only identifier, i.e. when there may not be a `probable_taxon` or a `community_taxon`. I think what's needed there is an additional test that covers the case where you are identifying an obs with one withdrawn identification by another user, and then those lines that look up a previous identification need to only look up the previous identifications by the user who is adding the *current* identification.

> Deleting an identification should update any other identification that was in disagreement to no longer be disagreements

I'm not entirely sure what this means. Could you provide a concrete example of when this seems appropriate? In my mind, deleting an identification should never change the disagreement state of other identifications. Identifications aren't really disagreements with other identifications. They are statements of what taxon the user thinks the observation depicts, and the disagreement is with another *taxon*, so if I say it's a flying fish and not a pickleweed, no one else's identification should change that statement.

**Comment by todtb** [comment]
> While #2769 seems harmless and sensibly defensive, I'm pretty sure the more serious problem is at https://github.com/inaturalist/inaturalist/blob/main/app/models/identification.rb#L182, where we are trying to handle the situation when you are disagreeing with yourself and you are the only identifier, i.e. when there may not be a `probable_taxon` or a `community_taxon`. I think what's needed there is an additional test that covers the case where you are identifying an obs with one withdrawn identification by another user, and then those lines that look up a previous identification need to only look up the previous identifications by the user who is adding the _current_ identification.

So I'm reading L182-184 to say: Find the most recent identification (current preferred). If that exists, set the `previous_observation_taxon_id` to match, otherwise set it to the observation's `taxon_id` (which may be null).

Nothing (right now) explicitly says to find the most recent Identification by the identifying user. Are you thinking we want to have `previous_observation_taxon_id` only reflect the taxa that the creator of the Identification has previously suggested?

> I'm not entirely sure what this means. Could you provide a concrete example of when this seems appropriate? In my mind, deleting an identification should never change the disagreement state of other identifications. Identifications aren't really disagreements with other identifications. They are statements of what taxon the user thinks the observation depicts, and the disagreement is with another _taxon_, so if I say it's a flying fish and not a pickleweed, no one else's identification should change that statement.

Yeah, it wasn't worded great. My thinking was as follows: Take an observation with no identifications. If Alice suggests pickleweed, and then Bob suggests flying fish, Bob's identification is in disagreement with pickleweed. If Alice withdraws pickleweed, then Bob's identification is no longer disagreeing with anything. However, I can see how leaving the `disagreement` boolean as true would provide some historical context.

**Comment by kueda** [comment]
> Are you thinking we want to have previous_observation_taxon_id only reflect the taxa that the creator of the Identification has previously suggested?

Only in the situation where there is no `observation.taxon` (aka the `probable_taxon`). That's what https://github.com/inaturalist/inaturalist/blob/8ec1f2ffd4f10cde558292277a79dfd62c8b1c8a/app/models/identification.rb#L180-L185 is currently trying to do, but I think it's currently broken b/c it's not looking for the *identifier*'s previous ident, just any previous ident.

> though I may have misunderstood what we are trying to accomplish.

Perhaps @tiwane can clarify, but my read is that the original bug is that a new identification is getting counted as a disagreement even if the single prior identification has been withdrawn at the time the new ident gets created. That seems like a bug to me b/c you're basically identifying an unidentified observation at that point. Someone else expressed an opinion but then withdrew it, so you're not disagreeing with anything.

However, if the prior identification was not withdrawn (was current), then you *are* disagreeing with something, and that statement should persist even if the original identification was withdrawn or deleted, both for record-keeping and because it still provides useful information in determining the community ID, e.g. if people in the future come back with more picklweed identifications.

**Comment by todtb** [comment]
Ok, I think we share the same understanding of the original issues.

- [x] An identification added to an observation without any current identifications should not be a disagreement
Fixed by #2769

- [ ] ~Deleting an identification should update any other identification that was in disagreement to no longer be disagreements~
We will leave the historic record of disagreement. With the fix above it should only be a true disagreement that occurred, even if the original identification it disagreed with was withdrawn.

As for the additional issue:

If we can address it simply by adding a `user_id` check to lines 182 and 183 (`&& i.user_id == user_id`), I'll add that in, otherwise should we break it off into a separate issue?

**Comment by tiwane** [comment]
> Perhaps @tiwane can clarify, but my read is that the original bug is that a new identification is getting counted as a disagreement even if the single prior identification has been withdrawn at the time the new ident gets created. 

Yes, to me that's the bug here. I added the second part ("If original ID is deleted...") just as a further detail, in case it was helpful in debugging, I should have been more clear about that.

**Comment by kueda** [comment]
> If we can address it simply by adding a user_id check to lines 182 and 183 (&& i.user_id == user_id), I'll add that in

Yup, that's what I'm proposing. Hopefully all specs will pass with that.
