### ISSUE TITLE
observations/{id} API returns project_ids list as empty

### ISSUE THREAD

**Issue by yugimani** [inaturalist/inaturalist#2807]
`curl -X GET --header 'Accept: application/json' 'https://api.inaturalist.org/v1/observations/{id}'`

GET observations endpoint doesn't seem to return the project_ids property correctly. Is it somehow always returning an empty list?

Tried 4 observations from 2 different projects, but the project_ids list is returned as empty.

**Comment by jwidness** [comment]
Please report potential bugs on the [forum](https://forum.inaturalist.org/) rather than github.  
In this case, the project_ids list only contains ids for Traditional projects, not Collection projects, so without knowing the observations or the projects involved, it's impossible to confirm your report.  Opening a topic on the forum and giving specific details will allow us to investigate.

**Comment by yugimani** [comment]
> 
> 
> Please report potential bugs on the [forum](https://forum.inaturalist.org/) rather than github.
> In this case, the project_ids list only contains ids for Traditional projects, not Collection projects, so without knowing the observations or the projects involved, it's impossible to confirm your report. Opening a topic on the forum and giving specific details will allow us to investigate.

Just checked and confirmed that both projects of interest were indeed `"project_type": "collection"`. 
If this is expected behavior of project_ids field, then we can close this issue.
