### ISSUE TITLE
Some links on /people result in a whale shark

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2810]
From: https://forum.inaturalist.org/t/whaleshark-when-clicking-on-observations-in-leaderboards/16493

Clicking on "observations" or "identifications" below any user on https://www.inaturalist.org/people results in a whale shark.

Clicking on "observations" on a page like https://www.inaturalist.org/people/leaderboard/2020/7 results in a whale shark.

However, choosing a single day (eg https://www.inaturalist.org/observations?on=2020-07-04&user_id=alexis_orion) works.

**Comment by todtb** [comment]
I can start looking into this @tiwane. Maybe something with the params, do you have an example of one that works?

**Comment by boucur** [comment]
I think `on=` now only works with exact dates, so instead of being `on=2020` or `on=2020-09`, it'd need to be `year=2020` and `year=2020&month=9`.

**Comment by todtb** [comment]
Thanks! I'll start looking into it.

**Comment by todtb** [comment]
Hey @kueda, when picking this up I thought it would be a simple date parsing issue with the params, but it looks like after shifting from `by_login` to `index` with user_id param, it works significantly different. 

While I've dug around a little bit and come up with some solutions for making OpenGraph work with partial iso8601 strings, (a year or month of obs), the best approach to the issue I believe needs some Angular knowledge, of which I lack. While I could keep poking at it, since this bug is now affecting many links from 5a3567bc383cb454890e08111370f528bee86dd3, I'd hate to hold up a solution.

If you have an approach in mind, I'd be glad to put it in place, otherwise I think I'll defer the issue to the experts.

**Comment by kueda** [comment]
> the best approach to the issue I believe needs some Angular knowledge

By this do you mean that the UI at, say, https://www.inaturalist.org/observations?on=2015-09, should show the user that they are viewing observations from September 2019? I wouldn't worry about that. For one thing, as long as `params[:on]` is set to something like `2015-09`, the "Exact Date" field should get populated with `2015-09`. On top of that, this kind of date filtering is pretty niche, so if the UI doesn't perfectly reflect the state of the search, I don't think that's a huge deal.

IMO, the priorities here are

1. A spec to ensure that these kinds of date params don't cause obs/index to crash
1. A fairly aggressive `begin` / `rescue` block to prevent any code exclusively dedicated to figuring out values for Open Graph from interfering with the primary purpose of showing observations
1. Translating these kinds of date ranges into reasonable Open Graph values, or, if that's too hard, just omitting the date info from Open Graph values in these cases.

**Comment by todtb** [comment]
I can start putting something together that rescues any exceptions around OG data generation, however I'm not even sure that `index` can currently handle partial iso8601 strings. That seems to be baked into the `by_login` action in a way I'm having trouble _easily_ moving over to `index`. That's because while `by_login` queries AR for and sets `@observations`, `index` seemingly doesn't. I think instead it hits the API via Angular (though I haven't looked to deep into that)

**Comment by kueda** [comment]
Again, I wouldn't worry about any of the obs query / retrieval logic. Yes, the obs/index action in ObservationsController does not actually do any query / retrieval and leaves that to the Angular UI, but I'm pretty sure that UI will handle `on` params like `2015-09`. If it doesn't that's a separate problem.
