### ISSUE TITLE
On Edit Obs Page, Sorting in the Search filters doesn't work

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2848]
From: https://forum.inaturalist.org/t/cant-sort-by-date-observed/17662 I can replicate.

1. Go to an edit obs page like https://www.inaturalist.org/observations/tiwane
2. In the Search, choose `Date Observed` and `Asc` and click Search.
3. Results are shown in Date Added order and the search shows `Date Added` and `Desc`.

Linked to https://github.com/inaturalist/inaturalist/commit/60a83e6d06fefa1d418fe8063bda31c1d40e681e ?

**Comment by todtb** [comment]
Sorry about that @tiwane. I think you're probably right about it being linked to  60a83e6. FWIW clicking the header can still order it correctly in the mean time though of course we need to find a way to have "In the Search, choose Date Observed and Asc and click Search." work as well so it can be combined with other terms.

I will take a look at this if not already fixed by another.

**Comment by tiwane** [comment]
No worries. Thanks!

**Comment by todtb** [comment]
If this is looking good now @tiwane, good to close?

**Comment by tiwane** [comment]
Yup, thanks!
