### ISSUE TITLE
duplicate GBIF observation links

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#2893]
we’re getting some duplicate GBIF observation links on some observations (e.g. https://www.inaturalist.org/observations/1234)
<img width="422" alt="Screen Shot 2020-12-16 at 10 30 28 PM" src="https://user-images.githubusercontent.com/598026/102451961-612c6d80-3fee-11eb-9475-da23d4af2075.png">
because CONABIO seems to be duplicating these in a different dataset but with the same institution code - which is [what we use to find these](https://github.com/inaturalist/inaturalist/blob/main/tools/gbif_observation_links.rb#L48) (e.g. https://www.gbif.org/occurrence/2629024667 vs https://www.gbif.org/occurrence/891058301) Looks like just 3,436 observations have this issue.

Options: 
1.  alter our [observation_links script](https://github.com/inaturalist/inaturalist/blob/main/tools/gbif_observation_links.rb#L48) to pull just from our dataset AND institution_code
2. contact GBIF and CONABIO to learn more whats happening on their end and perhaps see if there's an error thats preventing our institution_code from being unique to our dataset or some other change they could make
3. decorate these GBIF representations differently (e.g. 'your observation is represented in 2 datasets')

I'll contact GBIF to see if I can get more input re: 2

**Comment by loarie** [comment]
Any thoughts on Option 2 here @timrobertson100? Thanks in advance

**Comment by timrobertson100** [comment]
Thanks, @loarie - tricky problem

Firstly, just in case it is not known, GBIF treat occurrenceID as unique within a dataset. The same ID in 2 datasets will result in 2 records in GBIF.

There are always going to be "duplicate" records in GBIF for a variety of reasons (e.g. specimen depositing behavior, and multiple observations, data deposited in multiple DBs). This is why we've started [clustering records](https://www.gbif.org/news/4U1dz8LygQvqIywiRIRpAU/new-data-clustering-feature-aims-to-improve-data-quality-and-reveal-cross-dataset-connections) to link similar records. This specific example does not cluster since there isn't enough overlap in data (e.g. Conabio version misses dates).

On [this search for iNaturalist records that do cluser](https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&advanced=1&is_in_cluster=true) you can see there are actually 191k records which are highly similar (or the same) as records from other datasets. Clustering data is useful because we can start thining about transferring information across records. Examples could be "the iNaturalist community have a new species identification for your specimen" or "there is a DNA sequence for the specimen associated with this observation", or geocoding corrections, measurements, additional images etc.

So I _think_ I would suggest going for option 3. and showing the records do exist in different datasets for the time being.

Additionally, you could call the GBIF API (experimental still) to see if an iNat record clusters with other records. For example Ken-ichi's moth observation on [iNat](https://www.inaturalist.org/observations/1082341) appears in a [cluster on GBIF](https://www.gbif.org/occurrence/1453048679/cluster) linking it to a museum specimen record. This is the equivalent [API call](https://api.gbif.org/v1/occurrence/1453048679/experimental/related/) to retrieve the info.

**Comment by kueda** [comment]
IMO, option 1 (fixing our GBIF obs link script so it queries by dataset instead of institution) is the correct approach for fixing these duplicates on our end. I think it's a bit troubling that the `institutionCode` is not exclusive to a particular institution (i.e. anyone can share an occurrence with GBIF that claims to come from iNaturalist, just like we can share occurrences that claim to be from eBird), but that's GBIF's purview, not ours.

**Comment by timrobertson100** [comment]
You can just use datasetKey if that is your wish. No need to include institution code. 

Tim,

**Comment by kueda** [comment]
FWIW, the data should all be fixed in the database. I think some obs didn't get reindexed so you might still see this in some places, but reindexing the obs should fix it.
