### ISSUE TITLE
Explore: Clicking on "Niger" in Location field takes you to Nigeria

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2911]
1. Type `niger` into the Location field at https://www.inaturalist.org/observations
2. Click on Niger in the search results: 

<img width="379" alt="image" src="https://user-images.githubusercontent.com/15896181/103578538-990b3000-4e8b-11eb-8fbf-e7c5d6cf91a1.png">

3. "Nigeria" is selected https://www.inaturalist.org/observations?place_id=7141

<img width="896" alt="image" src="https://user-images.githubusercontent.com/15896181/103578624-b8a25880-4e8b-11eb-9c45-e89c75459510.png">

**Comment by jwidness** [comment]
The issue is that the Google Maps API is returning "Niger" and the correct bounding box coords, but the iNat places/nearby call is (at least on initial page load) using 0,0 as the reference location: https://api.inaturalist.org/v1/places/nearby?per_page=1&name=niger&swlat=11.69375602781824&swlng=0.1617177028086019&nelat=23.49999968202099&nelng=15.99903393101232&lat=0&lng=0

Nigeria is indeed closer to 0,0 than Niger is and does also contain the search string "niger".

If you move the map to Niger and try the same thing again, you get the expected results.

https://api.inaturalist.org/v1/places/nearby?per_page=1&name=niger&swlat=11.69375602781824&swlng=0.1617177028086019&nelat=23.49999968202099&nelng=15.99903393101232&lat=17.708343583849885&lng=8.081799999999987

![image](https://user-images.githubusercontent.com/13769652/103586820-e602fc80-4eb3-11eb-9515-efff3344cde7.png)

**Comment by jwidness** [comment]
Same problem reported for Punjab, Pakistan vs Punjab, India: https://forum.inaturalist.org/t/selecting-punjab-india-is-showing-punjab-pakistan-in-explore-tab/12704

I think you should be able to use the lat/lng from Google's GetPlaceDetails response as the reference location instead of 0,0.

![image](https://user-images.githubusercontent.com/13769652/125211302-6b0c0b80-e273-11eb-8d60-05f5db4f452b.png)

Which would lead to the places nearby request being https://api.inaturalist.org/v1/places/nearby?per_page=1&name=niger&swlat=11.69375602781824&swlng=0.1617177028086019&nelat=23.49999968202099&nelng=15.99903393101232&lat=17.607789&lng=8.081666 instead of https://api.inaturalist.org/v1/places/nearby?per_page=1&name=niger&swlat=11.69375602781824&swlng=0.1617177028086019&nelat=23.49999968202099&nelng=15.99903393101232&lat=0&lng=0, which gives the correct result of Niger instead of Nigeria.

![image](https://user-images.githubusercontent.com/13769652/125211358-ac9cb680-e273-11eb-9695-4a2a40ffdc78.png)
