### ISSUE TITLE
Non-staff cannot delete deletable flags

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2985]
From https://forum.inaturalist.org/t/impossible-to-delete-flags/21120 I can replicate with my test account.

1. With a non-staff account, flag something.
2. Immediately to the flag's page then delete the flag. 
3. Page changes but the flag still exists.

Staff can still delete flags.

**Comment by kueda** [comment]
I think this was [deliberate](https://github.com/inaturalist/inaturalist/commit/c56fdf9f1b45201ecf3b14ec1202d08e1a47084d#diff-e6a9180b0a89d29e5b77886abc047578fd52c17b6a26fd334ba6d37647526d73R8), perhaps due to [this slack convo](https://inaturalist.slack.com/archives/C02F8QXTU/p1584575316028600). I probably just didn't remove the delete button.

So I guess I'll repeat the question in case your mind has changed: is there ever a good reason to delete a flag?

**Comment by boucur** [comment]
See here https://forum.inaturalist.org/t/delete-withdraw-flags-that-you-created/17153/

**Comment by tiwane** [comment]
Yeah, I mentioned some in the issue I created: https://github.com/inaturalist/inaturalist/issues/2852

**Comment by kueda** [comment]
Ok, so from that issue, the new requirement is that a user can delete a flag if
- [ ] the user created it and no one else has commented on it
- [ ] the user created it and it is unresolved
