### ISSUE TITLE
Compare: selecting Source: Checklist results in internal server error

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3192]
eg https://www.inaturalist.org/observations/14930860 but it happens on all other obs I've tried.

1. On obs show or identify, select "Checklist" for Source.
2. Get Internal Server Error pop-up

<img width="428" alt="image" src="https://user-images.githubusercontent.com/15896181/130823814-804fc988-9c3d-4d0d-b925-93bd5c96a346.png">

**Comment by seanclifford** [comment]
I've had a quick look into this one to see what the cause is. 
I don't have time to pick it up and fix it, and I'm not sure what the correct fix would be without looking into it further, but it looks like it was introduced with dropping taxon_ancestors table (https://github.com/inaturalist/inaturalist/pull/3165)
This is because over in the iNaturalistAPI, `TaxaController.getChecklistSuggestions`  still tries to join on that table when the `taxon_id` param is present.

**Comment by tiwane** [comment]
I can't replicate any longer. I think it's OK to close.
