### ISSUE TITLE
Remove species filter missing on Dynamic life list

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3218]
From https://forum.inaturalist.org/t/remove-species-filter-missing-on-new-taxa-life-list/20628 I can replicate.

1. Go to https://www.inaturalist.org/lifelists/cmcheatle?view=tree&tree_mode=full_taxonomy&taxon_id=51128&place_id=112932
2. If "Species" or "Observations" is selected, there's an x button for removing the species filter:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/15896181/132593419-b708cdcb-f899-4495-b58f-a2c83cf44ebf.png">
3. But if you select "Unobserved Species" that x is gone:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/15896181/132593478-43415be1-6671-4c37-82bd-6e065b008c70.png">

**Comment by pleary** [comment]
For what it's worth - this was originally intentionally left off due to a fear of mine that when removed, it would trigger a very large and slow search for unobserved taxa across a large scope. I recognize that just leaving off the ability to remove the filter was strange, and we could better approach that with a warning message or something else. For now I've just enabled the ability to remove the the species filter from the unobserved species view, and if we get complaints about speed, or find it causes undesired load on the API, we can address that problem more directly in a better way.
