### ISSUE TITLE
Web uploader: AM/PM chooser doesn't change when clicked

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3241]
1. Start a new observation, either with no media or with a photo that has no date/time EXIF.
2. Click on the date/time field in the obs card, then click on the clock icon
3. Click on the AM/PM button
4. If the buttons shows PM, it doesn't change but "AM" is entered in the obs's date/time field

Expected behavior: the button changes from PM to AM.

**Comment by bianavarga** [comment]
@kueda I am interested in helping with iNat development. Can I take a stab at this bug?

**Comment by kueda** [comment]
@bianavarga, that's great! However, this might not be the best issue, b/c I think it might actually get solved as a part of https://github.com/inaturalist/inaturalist/pull/2799. I realize we're a bit light on easy, React-oriented issues at the moment, but maybe you'd like to take a look at one of these?

* https://github.com/inaturalist/inaturalist/issues/2721
* https://github.com/inaturalist/inaturalist/issues/3149
* https://github.com/inaturalist/inaturalist/issues/3043
* https://github.com/inaturalist/inaturalist/issues/2332

Of those, I think #2332 is probably the most straightforward, as long as we can agree to just put a link to Explore there instead of supporting pagination.

Also, if you want to send me a message on iNat with an email address I can invite you to a Slack channel we have set up for volunteer developers, which could be a good place to get help with setting up your development env.

**Comment by seanclifford** [comment]
If my PR #3324 ends up getting merged, this issue will be resolved too.

**Comment by seanclifford** [comment]
I'm not currently working on this issue right now, but here's some more info on what I found when looking at the other issue I linked above - but did not complete as planned.

The AM/PM button does not work as expected on:
- Web uploader / observation card date/time (as described above by Tony)
- Observation page / Date/Time observation field

It works as expected (with slightly different behaviors) on:
- New Project / Date/Time Range
- Web uploader / Left side bar date/time

Sometimes the AM/PM button will close the popup, and sometimes it doesn't.

The code for the datetime control itself resides here: https://github.com/inaturalist/react-bootstrap-datetimepicker

**Comment by pleary** [comment]
This seems to be resolved now for the uploader, both on the time picker for individual observations as well as with the left-hand menu when editing multiple observations, and for the time picker for observation fields on the observation details page
