### ISSUE TITLE
Can't add names in Malayalam

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3300]
From https://forum.inaturalist.org/t/malayalam-lexicon/27654 I can replicate on Staging.

1. Add മാസ്ക് 3 as a new name in Malayalam for https://staging.inaturalist.org/taxa/568993-Strophidia-caudata
2. Get the following error: 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/15896181/140428623-96a0d650-ee7d-4186-a1e4-7c3f7fee138f.png">

**Comment by kueda** [comment]
Probably need to make sure that we allow a lexicon if it exists in another language and is also in English. [This validation](https://github.com/inaturalist/inaturalist/blob/cf3bdf9a3c03c249c420bddd59e40603d8196700/app/models/taxon_name.rb#L499) was intended to prevent people from adding "Français" instead of "French".

**Comment by firosak** [comment]
Sorry i did not get you fully. Let me clarify the issue here again.
Malayalam is the language of Indian state of Kerala. We have added lots of common names in Malayalam so far. We noticed this issue recently. Now i am not able to add any Malayalam word for any taxa under already existing Lexicon "Malayalam". I am able to edit already existing one.
