### ISSUE TITLE
Place chooser recognizes a, A, and á but not Á

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#331]
The place chooser doesn't seem to be able to find places that start with Á such as 'Área de Protección de Flora y Fauna Cuatro Ciénegas'
![screen shot 2014-10-01 at 4 32 39 pm](https://cloud.githubusercontent.com/assets/598026/4484983/4402d6ea-49c3-11e4-9ed1-eaad9efea8cb.png)

**Comment by pleary** [comment]
@loarie looks like this might be working now. Could you confirm?

**Comment by loarie** [comment]
Doesn't look like it - https://www.inaturalist.org/places/66912 has name:
Área de Protección de Flora y Fauna Cuatro Ciénegas
But I can't get the place search to return it

**Comment by pleary** [comment]
Yeah I guess you're right. I was able to search with that character and found this place and rushed to assume it was the same.
![screen shot 2015-02-26 at 6 13 20 pm](https://cloud.githubusercontent.com/assets/48566/6404183/367667dc-bde3-11e4-9054-216687838418.png)

Since this one starts with that same character, there must be some other problem indexing that place name.
