### ISSUE TITLE
plural taxon should be singular

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3511]
this was pointed out to help at inat:
from https://uk.inaturalist.org/taxa/981435-Copelandia-tropica "About tab" automatically generated taxon description (in lieu of Wikipedia)
"Copelandia tropica is a species of fungi with 0 observations"
should be 
"Copelandia tropica is a species of **fungus** with 0 observations"

**Comment by kueda** [comment]
You would need to modify the `taxon_is_a_rank_of_fungi_with_x_observations` translation key. However, all values of these keys assume the iconic taxon is plural, as in "Vulpes is a genus of mammals with 10 observations" or "Asteraceae is a family of plants with 10 observations." I think "Asteraceae is a family of **plant** with 10 observations" sounds awkward because all taxonomic ranks describe collections of individuals, but if you can cite some usage manual that says differently I don't really feel too strongly about changing this very obscure piece of text. If there are different usage rules for different ranks, e.g. "Copelandia tropica is a species of fungus with 0 observations" vs "Agaricus is a genus of fungi" then you'll have to add as many more versions of this translation key as there are ranks (`taxon_is_a_genus_of_fungi_with_x_observations`, `taxon_is_a_species_of_fungi_with_x_observations`, etc.)

**Comment by loarie** [comment]
I agree changing would not clearly be an improvement for the reasons you mention so I think fine to close
