### ISSUE TITLE
Explore: ID badges do not always appear

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3628]
From https://forum.inaturalist.org/t/ident-count-on-identify-page-thumbnails-is-inconsistent-and-count-in-app-is-also-different/8571/

1. Go to https://www.inaturalist.org/observations?locale=en&place_id=any&taxon_id=181465&user_id=mononymous
2. Some observations that are research grade (eg https://www.inaturalist.org/observations/19630973) don't show an ID badge for the second ID.

![image](https://user-images.githubusercontent.com/15896181/214658762-9e358ece-b96a-489d-b852-e7ac0ba8e8b1.png)

As far as I can tell, forcing a reindex via a DQA vote on staging did _not_ cause the badge to appear. Adding an agreeing ID _did_ cause the badge to appear.

**Comment by pleary** [comment]
The reason this ID badge did not appear here is because the observation method [num_identifications_by_others](https://github.com/inaturalist/inaturalist/blob/main/app/models/observation.rb#L1370) was returning a value of 0, because both `num_identification_agreements` and `num_identification_disagreements` were 0. In this case there was some problem because when I ran [update_stats](https://github.com/inaturalist/inaturalist/blob/main/app/models/observation.rb#L2396), it properly set `num_identification_agreements` and thus `num_identifications_by_others` to 1 which added the badge.

Those values are derived from some [somewhat complicated logic](https://github.com/inaturalist/inaturalist/blob/main/app/models/observation.rb#L1776) which I haven't taken the time to fully understand yet.

Before digging too far into it - I should ask what do we _want_ the badge and number to reflect? I assumed it reflected the number of current IDs on the observation from users other than the observer. But some observations have `num_identifications_by_others` equal to 0 even when there are IDs from other users, e.g. https://www.inaturalist.org/observations?id=140082716&subview=grid, and where `update_stats` decides `num_identifications_by_others` should be 0. So for that observation the fact that we're not showing the badge is consistent with how it is currently implemented and not a "bug".

So there is one known problem where some observations have a value of `num_identifications_by_others` that is wrong according to how it should be set by `update_stats`. But for this issue specifically, we first need to know what the badge and number should reflect before we can get a proper fix out

**Comment by tiwane** [comment]
I think the badge and number should reflect the number of IDs made by accounts other than the observer. So for https://www.inaturalist.org/observations/140082716, which has 1 ID by the observer and 2 IDs by other accounts, I think the badge should appear with a 2 next to it.

That being said, the current Android app shows all IDs, including the observer's ID, whereas the current iOS app only shows the number of IDs made by other accounts. @kueda @abhasinat what are we showing in the new mobile app? I think the number should be the same across the platforms.

**Comment by kueda** [comment]
Abhas can correct me but I don't think we've explicitly addressed that in mobile yet. I agree with Tony: it should only show the number of current IDs added by people other than the observer.

**Comment by abhasinat** [comment]
I've designed the new mobile app to do what the android app does– to show total number of ID's, including the observer's ID's. Because it's presented in the context of #IDs, #comments, and quality grade, I think showing total number of ID's (including the user's) is fine. I'm open to discussing this and making a global change across the board– I don't love that these are treated differently in different places.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/44380775/217697362-4c4a49f1-110c-4e05-ae4d-70b7d97aae84.png">
