### ISSUE TITLE
Geoprivacy = obscured not being set

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#363]
I have a feeling this is happening when the community ID changes taxon_id from a non-threatened to threatened taxa as in these examples
http://www.inaturalist.org/observations/237859
http://www.inaturalist.org/observations/35155

**Comment by pleary** [comment]
These two examples are now obscured, and from my testing it seems like geoprivacy is properly getting set/unset when the community ID changes to/from a threatened taxon. Seems like this is resolved

**Comment by naturalistcharlie** [comment]
I know it's in another ticket somewhere too but the obscuring has been
acting a bit odd at times... I had some box elder observations obscure in
vermont with the text saying they are endangered... but they are not
endangered, actually a common weedy native tree here. I can't figure out
how to turn off the auto obscuring since it isn't set to do so in the first
place

On Fri, Sep 25, 2015 at 12:55 PM, Patrick Leary <notifications@github.com>
wrote:

> These two examples are now obscured, and from my testing it seems like
> geoprivacy is properly getting set/unset when the community ID changes
> to/from a threatened taxon. Seems like this is resolved
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/363#issuecomment-143279824>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by loarie** [comment]
ok - lets close and reopen in the off chance its rediscovered

**Comment by pleary** [comment]
Do you have any specific examples Charlie?

**Comment by naturalistcharlie** [comment]
This one is obscuring without me telling it to:
http://www.inaturalist.org/observations/272434
Oddly many of my box elder observations are NOT obscuring even though this
one is.

On Fri, Sep 25, 2015 at 1:31 PM, Patrick Leary <notifications@github.com>
wrote:

> Do you have any specific examples Charlie?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/363#issuecomment-143295761>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by pleary** [comment]
OK. There is a separate ticket for observations getting obscured when none of the current information supports it https://github.com/inaturalist/inaturalist/issues/703. Do you have cases of the opposite - where the taxon itself shows itself threatened and the observation is not obscured? Or the "endangered" case you mentioned?

**Comment by naturalistcharlie** [comment]
No.. sorry, i think i am confusing matters by talking about the wrong issue
here. I have not seen things not obscuring when they should. There are
cases where things have a conservation tag but are not obscured because
they are not set to obscure but that's of course not a bug.

On Fri, Sep 25, 2015 at 1:37 PM, Patrick Leary <notifications@github.com>
wrote:

> OK. There is a separate ticket for observations getting obscured when none
> of the current information supports it #703
> <https://github.com/inaturalist/inaturalist/issues/703>. Do you have
> cases of the opposite - where the taxon itself shows itself threatened and
> the observation is not obscured? Or the "endangered" case you mentioned?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/363#issuecomment-143297599>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
