### ISSUE TITLE
When adding, editing, or deleting a name, require a note

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3727]
Currently, if one edits, adds, or deletes a common name, there is an optional form for explaining one's action:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/15896181/230689977-af4df899-55cf-41a4-9ee4-b9b85b674da1.png">

After discussing improvments/updates to common names and how they're created and dealt with on iNat, Scott, Carrie and I think that requiring an explanation of some kind (preferably citing a source) would require a user to not add or edit names without it having to explain their actions. This will hopefully reduce the number of created-for-iNat names and names from questionable sources, and faciliate conversation and understanding if someone is curious about name's provenance. 

- [x] Change the text in the Note field to "Why are you making this change? Please explain, and cite a source if possible. (Required)"
- [x] If no text is entered, or fewer than 10 characters of text are entered, prevent the change from being saved and display a pop-up that says "You must provide an explanation for your intended change. " with a button below it that says "I understand".
- [x] The Note will be saved in the taxon's history.

**Comment by kueda** [comment]
TaxonNames are already linked to Source records... we just don't expose the Source form as a part of the TaxonName form, nor do we require it. IMO, showing the source form and requiring a source for new names would make it clearer that we are now requiring citations for new names. The audit note is meant to capture why a person made a change, which seems broader than the provenance of the data being added (e.g. I might want to explain that I'm adding a name because the AOU changed the official name of _Cyanocitta stelleri_ *and* provide a full citation to the source of the name).
