### ISSUE TITLE
Editing observation note when on a network site changes map zoom level

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3787]
From https://forum.inaturalist.org/t/unwanted-map-zoom-out-when-editing-observations/42815 I can replicate.

1. Open an observation that has a fairly zoomed in map view while logged into a network site, eg https://inaturalist.ca/observations/169619005

2. Edit observation and add or edit the note. Save changes.

3. Map is now zoomed out. 

This doesn't happen logged into inaturalist.org and editing an observation's note.

**Comment by SK53** [comment]
This also happens on inaturalist.org. 

I've just uploaded a number of observations where, for some reason, DarkTable was reading old EXIF data and exporting those locations rather than the ones on the photos. Only realised after I'd done a few observations.

Originally uploaded observations have lat/lon, but not accuracy and are shown like [this one](https://www.inaturalist.org/observations/176836014) (which I'll avoid editing for a whttps://www.inaturalist.org/observations/176809799hile). This in itself is quite a broad canvas for the observation (which is probably why I didn't spot that they were misplaced), but better than zoom level 1 at a global scale. 

[This observation]() I zoomed out as far as I could and then saved. It has a similar viewport to the above example now. [This](https://www.inaturalist.org/observations/176836045), in contrast, is what an observation where the original co-ordinates are replaced manually looks like. If I carefully zoom in I can get it saved with a [more sensible contextual view](https://www.inaturalist.org/observations/176838649).

To replace the incorrect co-ordinates I'm editing each observation and choosing edit location. I'm copying and pasting co--ordinates from Geosetter, the program i used to assign co-ordinates in the first place. In most cases I'm also setting accuracy to 5 or 10 metres as well. When saved in this form they all default to the zoom level 1 view as shown with https://www.inaturalist.org/observations/176836045.

In general I'd prefer the initial default view on creating an observation to be 1 km across or less. Virtually all of my observations have co-ordinates from GPS and I observe over a smallish area too.

**Comment by pleary** [comment]
I believe this was an intentionally implemented feature. We can remove it though. Observations have an attribute `map_scale` and when you change the zoom of the map on the observations edit page, that value will be updated accordingly, and the map on the observation show page will then reflect the new zoom level. If we don't want the edit page to modify this value anymore, we can do that. It may still get set other places as it is an observation attribute that can be edited.

For the purposes of this ticket, I'll make it so changing the map zoom level on the observations edit page does not modify the observation attribute `map_scale`

**Comment by pleary** [comment]
I didn't find an easy comprehensive fix. The problem is the map auto-zooms to the site bounds on obs edit on a network site, but the map is set to update `map_scale` when the map moves, so that auto-zoom was updating map_scale. What I changed is I added a small delay to when map movement triggers an update to `map_scale`. Hopefully that leaves enough time for the auto-zoom to happen (and not touch `map_scale`), but then have manual map movement update `map_scale` like users are used to.

We might be able to apply a better fix if we get that page working with proper asynchronous Google Maps loading, and we can enable a callback immediately after the map zooms. In the mean time, please reopen if people are still experiencing this.
