### ISSUE TITLE
Sometimes observations are stuck on "Processing..." thumbnail

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#39]
See for example Trachemys scripta ssp. elegans observation under:
http://www.inaturalist.org/observations/kaldari
The image was uploaded about an hour ago and the thumbnail image actually exists:
http://static.inaturalist.org/photos/302164/square.jpg?1366505753
...but it seems that the processing placeholder must be cached in its place. I cleared my local browser cache to make sure it wasn't a local page cache.

**Comment by pleary** [comment]
I tried addressing this in ece52b48550f9765d02ad5e935db64d2178712e1 . We are now using site_id in the cache key, and we weren't using the site ID when clearing the cache. Hopefully this sill allow these "processing" images to be replaced with the proper images as soon as they are available

**Comment by pleary** [comment]
In commit 8f0ee6c3c32c9a00af6c5fbf897ba7d037954f09 I removed all references to the cached observations partials. Since its release, and the fix in a20c98edc916a6ab306713c14509a0867fc5b2c7, performance is looking unchanged compared to running with the cache. I think we can live without these cached partials for now. The "Processing..." images should no longer stick around.
