### ISSUE TITLE
Add an "Are you sure?" warning when flagging a user as spam

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3903]
From https://forum.inaturalist.org/t/create-an-are-you-sure-popup-when-suspending-a-user-for-spam/45978

For curators, it's easy to accidentally select the "flag as spammer" option in the Admin Tools on a user's profile, so some user are getting flagged by mistake. Can we add a warning pop-up that says "Are you sure you want to flag this user as a spammer?" with buttons that say "Yes" and "No"?

I think the "Flag as spammer" option should be above the line as well, in the same section as "Suspend user".

**Comment by Maxhou00** [comment]
Hello, 

I made the changes and created a [PR](https://github.com/inaturalist/inaturalist/pull/3925) for this issue.

It will need translation for different languages.

Note: I didn't change the position of the option since it was your personal suggestion and not an issue talk on the initial topic. I can make the change if needed.
