### ISSUE TITLE
Flaggers should be subscribed to the flags they create

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3954]
See: https://forum.inaturalist.org/t/no-notification-of-resolved-flags/29974

When someone makes a flag, we're not auto-subscribing them to the flag itself, meaning they won't be notified of any comments on the flag or when it's resolved. We should subscribe an account to any flag that it creates, and retroactively subscribe flaggers to their flags (if they're not already subscribed manually or having made a comment).

**Comment by pleary** [comment]
It turns out there was no issue with subscriptions - users that create flags are implicitly subscribed and should get notifications on their flags. There was however a bug with notifications where users that had blocked other users or had been blocked by users would not get notifications on flags they create, even if the blocking was not related to the flag. That bug should be fixed and blocking should only affect notifications when the blocks are relevant
