### ISSUE TITLE
Explore search circle changes to rectangle when radius is unspecified

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4166]
Report is from https://forum.inaturalist.org/t/explore-search-circle-changes-to-rectangle-when-radius-is-unspecified/52561 I can replicate.  

Explore is happy to take a lat/lng search without an explicit radius param, defaulting to a radius of 10, e.g. https://www.inaturalist.org/observations?lat=40.78094676128634&lng=-73.96688431611243 is equivalent to https://www.inaturalist.org/observations?lat=40.78094676128634&lng=-73.96688431611243&radius=10. But if you do this and then try to move or resize the circle, it's converted to a rectangle.

Step 1: Run lat/lng based search, e.g. https://www.inaturalist.org/observations?lat=40.78094676128634&lng=-73.96688431611243

Step 2: try to resize or move the circle

Step 3: now you have a rectangle 

If you instead have an explicit radius param, e.g. https://www.inaturalist.org/observations?lat=40.78094676128634&lng=-73.96688431611243&radius=10, then it works as expected.

I will also note that observations on one's dashboard offer a quick and easy way to accidentally get to this state because the link from the place description is a lat/lng Explore search without a specified radius.

![image](https://github.com/user-attachments/assets/4883c5a3-2ea4-4a35-8f23-47b1542c235b)

**Comment by jordannb** [comment]
Fwiw, I looked into this a little but don't have Google Maps setup to make/test a PR with.

Browser dev tools console shows that `angular.element("#observations-map").scope().drawing.currentShape` is `null` before the shape is moved. If, before moving the shape, I execute `angular.element("#observations-map").scope().drawing.currentShape = "circle"` in browser dev tools, then the shape maintains its circular nature after dragging.

This happens because the default shape is a rectangle when refreshing the selected place on the map: https://github.com/inaturalist/inaturalist/blob/e3ef1d96cb03ef8bd8fc10d2fb24c6054eec408c/app/assets/javascripts/ang/controllers/observation_search.js.erb#L2091-L2095 (this refresh is triggered on `dragend` [here](https://github.com/inaturalist/inaturalist/blob/e3ef1d96cb03ef8bd8fc10d2fb24c6054eec408c/app/assets/javascripts/ang/controllers/observation_search.js.erb#L2120-L2126)). So I believe a fix to this could be to detect that coordinates are being used when the map is initialized and then to set `$scope.drawing.currentShape = "circle"`.

**Comment by pleary** [comment]
Thanks @jordannb! I believe you have the correct root cause. I [made an update here](https://github.com/inaturalist/inaturalist/commit/d42e0cfac20ad1e781893edec8340a9a97bba270#diff-50f223da923c48f8c5ee406dcb7a5659db7c242e6431285961ad45679667161cL510) that should set the correct share and fix this bug. We will deploy the change early next week
