### ISSUE TITLE
In 'Your Observations', inconsistent timezone between Grid View, List View 'Observed' column, and List View 'Added' column

### ISSUE THREAD

**Issue by Shot2** [inaturalist/inaturalist#4197]
[//]: # (For feature requests and bug reports not specifically concerning code, please use https://forum.inaturalist.org/c/feature-requests/16. iNat staff will make github issues if/when an actionable solution emerges)

**Describe the bug**
Observation observed, added, and viewed from within the same timezone.
However, the timezone used for the 'Your Observations' page is not the same:

1. whether it is viewed as Grid, or as List
2. when viewed as List, between 'Observed' and 'Added' columns. 

**To Reproduce**
1. Go to 'Your Observations' to view any obs (in the example below, made, added, and viewed from within the same timezone at the same time of year, in the example below 'CEST' = 'UTC+02:00')
2. Click on 'Grid'
3. Note the timezone used when hovering over the 'am-time-ago' text for that obs, e.g. "Observed on 2024-07-22T10:14:00+02:00" (which is correct)
4. Click on 'List'
5. Note the timezone used in the 'Observed' column, e.g. "Jul 22, 2024 9:14 AM CET" (which is wrong, cf. point 3)
6. Note the timezone used in the 'Added' column, e.g. "Today 12:00 PM WAT" (which is wrong, cf. point 1)

**Expected behavior**
Everything should be reported consistently: either in agreement with the one timezone chosen by the user in their 'Settings' page; or in agreement with the timezones (occasionally different) in effect respectively during the observation, during the addition, and during viewing for an obs.

**Context**
 - OS: Windows 11
 - Browser: MS Edge
 - Version: 128.0.2739.42 (Official build) (64-bit)

**Additional context**
Logged in user, viewing a proper observation created from a photo (a) taken from within CEST/UTC+2 zone with a functioning and properly-configured camera (b) added from within CEST/UTC+2 zone with a notebook computer (c) viewed from within CEST/UTC+2 zone with that same notebook.

**Edit**
Example URL: https://www.inaturalist.org/observations?order_by=observed_on&place_id=6753&subview=table&taxon_id=56154&verifiable=any

**Comment by pleary** [comment]
Could you please provide a URL to an explore search demonstrating the problem? The expected behavior after releasing a [fix for this issue](https://github.com/inaturalist/inaturalist/issues/4170) is that the time observed should be in the observers time zone and the time added should be in the viewers time zone, the same as is shown on the observation details page. If they are the same time zone, then indeed they should be presented the same.

We prefer users post to the [iNaturalist Forum](https://forum.inaturalist.org/t/about-the-bug-reports-category-please-read-before-posting/60). There is a bug report template there that asks for things like screenshots and URLs, and that venue is better for other community members to offer their experiences on the issue, all of which help us investigate the problem efficiently. When a staff member confirms the issue, they will make a Github issue linking to the discussion in the Forum.

**Comment by Shot2** [comment]
Oh ok, sorry for the noise, forget about it.

**Comment by Shot2** [comment]
Ok, sorry for the noise.
