### ISSUE TITLE
[Feature request] Add Spoiler settings

### ISSUE THREAD

**Issue by FirePowi** [inaturalist/inaturalist#4270]
I’d like to propose a way to spoiler some images based on taxa, death status or so. I know we may encounter dead animals and stuff on our naturalist journey, but I have to admit that sometimes, iNaturalist images are especially hard to see.

Here’s my proposition to add settings like that:
![Screenshot: settings to spoil dead animals and pick taxa to spoiler](https://github.com/user-attachments/assets/12bbb74a-a3ab-451f-a572-41f7877b7b36)

This is very much an exemple and absolutely not the way I want it to look in the end. It’s just to "give the idea".

The idea would be, in the end,
I think we can blur it like in Telegram:
![A blurred Vanessa Atalanta butterfly](https://github.com/user-attachments/assets/0ce3d187-9feb-4030-8e3d-63bc95c150a3)
Or like in discord:
![Same Vanessa Atalanta blurred differently](https://github.com/user-attachments/assets/88f73195-ebaa-490b-9e9c-48774c1e2b9d)

Discord uses the css property [firter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) set to "blur(44px)"
Tho I’m unsure this is doable given my lack of skills in CSS and all.

**Comment by pleary** [comment]
Hi @FirePowi. Thanks for your interest in improving the iNaturalist website. As we say in our [contributing guide](https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md), we would prefer if feature requests be proposed through the [iNaturalist Forum](https://forum.inaturalist.org/t/implement-photo-blur-on-observations-annotated-as-dead/21214) instead of this Github repo. That way the community can have a chance to discuss the proposal. If we decide we would then like to implement the feature, a member of iNaturalist staff will turn it into a Github issue with a specification and requirements based on the results of the community discussion.

There have been extensive discussions on the forum already about features similar to this, e.g. [this thread](https://forum.inaturalist.org/t/implement-photo-blur-on-observations-annotated-as-dead/21214), a [similar thread](https://forum.inaturalist.org/t/is-a-photo-of-entrails-too-offensive-for-inaturalist/5465), and [another one](https://forum.inaturalist.org/t/caution-dead-animal-image-in-observation/14574) with a related theme. So far we have not decided to implement ant such features.

I am going to close this ticket. Feel free to post to the iNaturalist forum in one of the existing threads or an a new thread of your own to discuss your proposal with the community. If the we decide to implement the feature, someone on the iNaturalist staff will create Github tickets for it in the relevant repos, as a feature like this would affect not only the website but also all mobile applications. Thanks!
