### ISSUE TITLE
upgrade to rails 4 and get it to start up

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#442]
- [x] make a branch for rails4
- [x] upgrade to ruby 2.0
- [x] upgrade to rails 4.2.0
- [x] get the app to boot

**Comment by md5** [comment]
I'm curious why Ruby 2.0 instead of 2.1 or 2.2? Or did you just mean 2.x?

**Comment by kueda** [comment]
No strong feeling on our part, just going from the line in http://guides.rubyonrails.org/upgrading_ruby_on_rails.html that says "Rails 4 prefers Ruby 2.0 and requires 1.9.3 or newer." Have you done any 3-to-4 upgrades and were there any ruby version issues?

**Comment by md5** [comment]
I haven't done any 3-to-4 upgrades in a while, but I think any issues you'd run into would be 1.9-to-2.x issues. I suspect most of those would have been worked out in the upstream gems by now, but this codebase has quite a few old or forked gems.

As for doing 1.9-to-2.2 instead of 1.9-to-2.0, I don't think involves substantially more work or risk and it gets you onto a version that will be supported further out than if you just move to 2.0.

**Comment by kueda** [comment]
@pleary, I didn't get it to boot, but it's on its way. I'm trying Ruby 2.2.0 and I don't think it's causing any problems. ThinkingSphinx seems like it's undergone a major overhaul, so that's going to take a bit of fussing. In order to get it to stop complaining I had to upgrade to the latest Sphinx... which will *not* work with the older TS 2.x we were using, so upgrade with care. I just blithely run `brew uninstall sphinx` and reinstalled it, which seemed to require an openssl upgrade, which broke a lot of things.
