### ISSUE TITLE
service from EOL, identifying iNat records from which images have been sent to EOL

### ISSUE THREAD

**Issue by jhammock** [inaturalist/inaturalist#486]
Sorry, Ken-ichi; this probably does not belong back in https://github.com/jhpoelen/eol-globi-data/issues/115

@kueda Just checking: the images on EOL currently carry source links back to the photo page on iNat, eg: http://www.inaturalist.org/photos/1234032. You'd rather have a list of observation IDs to post these links on, not photo IDs? I can imagine, now that I think about it, you getting a stack of records for an observation which bears 6 photos, all sent to EOL. Would you rather have that, or would you prefer to post these to the photo pages? Or should we hold off on doing this? Thanks!

please forgive my complete ignorance of github etiquette. :)

**Comment by kueda** [comment]
No worries, the important thing is communicating, but I'm guessing this would be a more appropriate issue for an EOL repo, since providing this service is something you guys would be doing (integrating it on our end might be a separate issue). Yes, my preference would be for a mapping from iNat observation IDs to EOL data object ids, so we can do the reverse of the iNat link you have on http://eol.org/data_objects/29805632 and link back to you guys. I could also use the iNat photo URLs too if that's easier for you.

Frankly an API endpoint might be more generally useful, e.g.

http://eol.org/api/pages/1.0/data_objects?provider=iNaturalist&page=12

and the response would be a bunch of data object records like you have in the pages api response. Or you could just publish a giant file, but that might be even more cumbersome.

**Comment by jhammock** [comment]
Thanks for feedback; will probably try just generating a single mapping file for now. photo urls are likely to be easier but I will ask about both. Will start a new issue when I have something for you to review.
