### ISSUE TITLE
Wikipedia descriptions on taxon pages broken

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#500]
Taxon/show attempts to load a wikipedia page but something goes wrong and defaults to the EOL page. Seems to be effecting all taxon pages.

Issue first raised here: https://groups.google.com/forum/#!topic/inaturalist/5tMvpsXUwV0

**Comment by pleary** [comment]
They're back! The problem was were getting suffled off to a very slow queue on the Wikipedia end, causing these requests to take 1 minute or more, and thus timing out. We implemented a caching system and were restored to the fast lane on Wikipedia's end. See 875e60cdeab46cc60473a42ce837ae7f6652847b for the ApiEndpointCache logic
