### ISSUE TITLE
attribution of photo added as taxa photo, from EOL, not displaying properly.

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#516]
I added a photo from EOL as the taxa photo for Schistidium rivulare.

The photo was originally taken by Chris Tracey on iNaturalist, Then it was sent to EOL. Then I added it as the default photo for the species.

It displays the photo as "Photo: (c) inaturalist, some rights reserved (CC BY-NC-SA)" rather than crediting Chris. If you click on it you see the correct attribution on iNat. 

Certainly it is a it odd and roundabout to add an eol observation from inaturalist through the EOL page but it would still be better if it credited Chris properly on the photo.

www.inaturalist.org/taxa/168584-Schistidium-rivulare

**Comment by naturalistcharlie** [comment]
![image](https://cloud.githubusercontent.com/assets/7171475/6991153/a7358900-da51-11e4-8063-55c84aefe2c6.png)

**Comment by ChristopherTracey** [comment]
I'll just agree. ;)

It does look like something weird is going on here.

**Comment by kueda** [comment]
I fixed this particular problem which I suspect was due to EOL not correctly filling in the data on their end, which I think they've since fixed. I also added a "Repair broken URLs" link to the EOL photo pages, which behaves like other links like that in that it will reset the URLs, but it will also reset the attribution if it's changed on EOL.
