### ISSUE TITLE
out of range - bug

### ISSUE THREAD

**Issue by zooga1961** [inaturalist/inaturalist#522]
Last year I added locations to Black Chinned Hummingbird's range    (Cedar Hill, TX,  Dallas County, TX, and Cedar Ridge Preserve in Dallas TX)     New observations entered this year for this species are still marked as Out of Range.   

When you go to the range list  for the species the locations when searched are listed.   Of course there is always the possibility I didn't add the additional locations correctly.          

 see this observation   http://www.inaturalist.org/observations/1379204

**Comment by loarie** [comment]
that flag means out of range according to the pink range map iNat shows which is almost always the IUCN RedList range. More often than not, it signifies an issue with the range map than the observation - but thats still kind of interesting... One could propose the removal this alert since its kind of dumb, but since this isn't a bug per se, I'm closing this issue

**Comment by zooga1961** [comment]
okay  Thank you
