### ISSUE TITLE
Allow date filtering on the map of all observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#541]
For the Great Nature Project's upcoming global snapshot of biodiversity, I'd like to be able to take the awesome iNat mega-map and apply a date range query, such as this:
http://www.inaturalist.org/observations/map?d1=2015-04-22&d2=2015-04-23#2/0/0 

Currently, that map just displays all observations. It would be super cool to be able to watch the map fill in with observations during just those dates.

Filtering by project ID and user ID is enabled, but since the global snapshot is effectively a bioblitz, the project id query is pretty useless. Thanks!

**Comment by pleary** [comment]
We have some plans to synchronize the observations JSON and map APIs, which would allow you to use any of the same parameters for maps, like projectIDs and date ranges. I can't say for sure when something might be ready, but I think it's feasible we could have date ranges working before the global snapshot.

**Comment by carrieseltzer** [comment]
Great! That would be ENORMOUSLY helpful. Thanks!



—

**Comment by carrieseltzer** [comment]
I just wanted to give this a nudge again because it would be IMMENSELY useful for both the upcoming Hawaii Volcanoes BioBlitz as well as the global snapshot. Any estimate on when these changes might be possible, Patrick?

**Comment by pleary** [comment]
Could you let me know which parameters you will be interested in filtering on? It sounds like date range (d1 and d2), project_id, and user_id? I am creating an entirely new system, so not all of the old parameters will work out of the box and I want to make sure everything you're looking for is covered.

What I am thinking is, based on the parameters sent to observations/map, I'll swap out the back end mapserver used for generating maps for that page. It would only be visible on observations/map for now because it won't be too highly polished yet. The new map server also doesn't really do grids. It can render points at every zoom level, and/or render heatmaps like:

![screen shot 2015-05-08 at 4 09 35 pm](https://cloud.githubusercontent.com/assets/48566/7544619/a491f664-f59c-11e4-96ed-efda86e99150.png)

Would you be OK with just having the map render points for zooms, and no grids? Depending on the answers to the above, I can possibly have something tonight, more likely by Sunday night, and almost certainly by Monday. A fully-robust solution will take a bit more time because it is such a new system and we'll need to run it through its paces some more.

**Comment by carrieseltzer** [comment]
For my immediate purposes, I'm only interested in date range (d1 and d2, preferably without needing to specify a time zone) and project id. User id is cool to have but not essential. I want to be able to embed from observations/map on greatnatureproject.org, so that's fine if it's only viewable there. 

I'm not sure what you mean by "render points for zooms". If you zoom in on the heat map far enough, do you see clickable points? I'm not attached to grids. I just want to be able to display all the observations coming in for a certain date range.

**Comment by pleary** [comment]
great. I just mean there would be no grids at all. When you're zoomed all the way out looking at the world then all you'll see is clickable points, the same as when you zoom in on our maps now. That sounds like what you want anyway.

**Comment by carrieseltzer** [comment]
That sounds fine. Thanks Patrick! I'll check it out as soon as it's ready. 



—

**Comment by pleary** [comment]
OK I have a version up that we can try out:
http://www.inaturalist.org/observations/map?d1=2015-04-22&d2=2015-4-23

You can also view that data as a heatmap if you want:
http://www.inaturalist.org/observations/map?d1=2015-04-22&d2=2015-4-23&heatmap

To be sure you are using the new mapserver you'll have to specify that, as there are some parameters the old server handled that the new sever can handle as well:
http://www.inaturalist.org/observations/map?elastic=true

This new mapserver can handle the following parameters: user_id, project_id, place_id, taxon_id, and d1 and/or d2 for date filtering. Any set of parameters can be turned into a heatmap by adding the heatmap parameter. I'd be interested to know if this will work for you. Also if you notice anything strange or wrong (I would not be surprised because this is all new stuff) let me know and I'll fix it as soon as I can.

**Comment by carrieseltzer** [comment]
Thanks, Patrick! I think this will work, but I seem to be having trouble getting the map to show points (as points or heat map) when I change the parameters. For example, right now, this loads a blank map:
http://www.inaturalist.org/observations/map?place_id=7222#10/19.303/-155.408

But here you can see that it should be showing observations:
http://www.inaturalist.org/observations/map#10/19.35/-155.408

Is this due to a lag in the time it takes to load a new map that's being requested for the first time? Or is this a bug?

**Comment by pleary** [comment]
The new tileserver is based on Elasticsearch which cannot index some polygons for some reason, and Hawaii Volcanoes is one. It was also causing the server to crash, which I fixed. So we cannot directly filter on that place right now, but we can render that place on the map like:
http://www.inaturalist.org/observations/map?elastic=true&render_place_id=7222

Will that work?

**Comment by carrieseltzer** [comment]
That works just fine now that the date filtering is working properly. You can see here where I've embedded test versions of the maps on the test version of the GNP site.

This: http://greatnature.test.education.nationalgeographic.com/events/hawaii-volcanoes-national-park-bioblitz-2015/map/
Uses this: http://www.inaturalist.org/observations/map?elastic=true&render_place_id=7222&d1=2015-04-01&d2=2015-05-16#10/19.303/-155.408

And this one: http://greatnature.test.education.nationalgeographic.com/events/global-snapshot-2015/map/
Uses this: http://www.inaturalist.org/observations/map?elastic=true&d1=2015-05-01&d2=2015-05-25#2/11.523/-5.361
And this: http://www.inaturalist.org/observations/map?elastic=true&d1=2015-05-01&d2=2015-05-25&heatmap#2/11.523/-5.361

As long as this keeps working through Memorial Day weekend, I think we're good on the maps. Thanks, Patrick!

**Comment by carrieseltzer** [comment]
I think this can be closed, but I'll let one of you do it since it was just referenced in another issue. The map we're using for the Great Nature Project is still working fine (http://www.inaturalist.org/observations/map?elastic=true&d1=2015-05-15&d2=2015-05-25&heatmap#2/0/0).
