### ISSUE TITLE
Tag uploader for Guides

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#543]
Kew is interested in using tags in guides as keys and one of the things they've requested is a way to import/export character matrixes to a guide like the following as CSV and maybe the standard SDD format
![screen shot 2015-04-30 at 11 49 36 am](https://cloud.githubusercontent.com/assets/598026/7420152/019ee016-ef2f-11e4-9d59-07a37ff938ed.png)

**Comment by kueda** [comment]
To be clear, in your diagram "key" means "couplet" or "trait," and SDD refers to the [TDWG Structure of Descriptive Data](http://wiki.tdwg.org/twiki/bin/view/SDD/WebHome) XML schema, correct? I'd be ok with the CSV approach. SDD looks like a hot mess, so if the Kew folks can provide some example SDD docs and links to sensible documentation that would be helpful.

**Comment by stevenpbachman** [comment]
Yes, I think the terminology varies, sometimes 'character' and 'state' = Leaf position - alternate. CSV would be fine for me. SDD seems to be an emerging standard, but maybe it is not quite there yet. If there is one thing we could drop, this would be it. If you can import csv matrix, as in Scott's diagram, that would be a great start and then we can come back to SDD later.

**Comment by kueda** [comment]
Ok, this should now be working. When editing a guide, open the "Edit" menu and choose "Import tags from CSV." I altered the proposed format for the CSV file a bit. The format should be something like this:

Name | color | Number of hands |     |
---- | ----- | --------------- | --- |
Homo sapiens | | 2 | bipedal
Canis familiaris | white | 0 | quadripedal
Canis familiaris | brown | 0 | quadripedal
Vulpes vulpes | red\|black | 0 | quadripedal
This will add the following tags:

* Homo sapiens: `Number of hands=2`, `bipedal`
* Canis familiaris: `color=white`, `color=brown`, `Number of hands=0`, `quadripedal`
* Vulpes vulpes: `color=red`, `color=gray`, `Number of hands=0`, `quadripedal`

So each row is for a single species and set of tag predicates/categories. You can add multiple lines per species to add multiple tags, or you can specify multiple tag values per cell using the pipe ("|") character. Blank cells will be ignored. The `Name` column should correspond exactly with the `Name` attribute of the relevant guide taxon. Values in columns without headers will just be added as plain tags without predicates/categories.

I also added a button to the "Import tags from CSV" dialog that will let you download a CSV of all the existing tags in your guide, which should help to get the upload format right.

@stevenpbachman, let me know if this meets your requirements.

**Comment by stevenpbachman** [comment]
This looks great! The format is fine and I think suitably generic that many can work with this. I had to do a bit of wrangling from the format I had from a pre-existing ID key, but considering the time this will save in tagging, well worth it. The option to have multiple lines per species or multiple 'states' per category should cover the way people are likely to code up species identification features. 

A couple of quick things when I tried it out for this guide (http://www.inaturalist.org/guides/2164):
1) After uploading the csv and clicking 'import tags..' it bailed out after a few seconds and gave me a timeout page. However, opening up the guide page showed that it had worked.
2) When the guide only has names in it and you download the csv template it is blank. It would be good if the names could be added at this point. - even better would be for the names to be added to a blank guide from the csv import.

Otherwise this is looking great. Thanks.

**Comment by kueda** [comment]
Steven, could you post the CSV you tried to upload to that guide, or email it to help@inaturalist.org? I'll work on that recommendation about the template.

**Comment by kueda** [comment]
Thanks, Steven. Regarding the timeout, I tried that CSV you emailed me and it uploaded ok. I can imagine there could be performance issues for really big lists and really big CSV files, so if this becomes a recurring problem for you please let me know, along with guide URLs and tag CSV files and I'll come up with a better solution. I'm going to close this for now b/c as far as I can tell it's working.

**Comment by loarie** [comment]
I'm getting the failwhale on 'import tags from CSV' if no file chosen
<img width="661" alt="screen shot 2015-08-25 at 3 54 29 pm" src="https://cloud.githubusercontent.com/assets/598026/9481742/a724c352-4b41-11e5-9f9b-ee2577145bd5.png">

**Comment by kueda** [comment]
I think cf0cc265ba22b4db0721cd7befca5149fc9f4430 should fix that.
