### ISSUE TITLE
Project header leaderboard display/link discrepancy

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#555]
project header leaderboard shows count based on hrank=species
e.g. http://www.inaturalist.org/projects/coyote-point-bioblitz-2015

this should be rank=species to match link, e.g. 
http://www.inaturalist.org/observations/taxa?d1=2015-04-25T06%3A00%3A00-07%3A00&d2=2015-04-25T20%3A00%3A00-07%3A00&place_id=77154&rank=species

**Comment by kueda** [comment]
This is going to mean taxa that are represented only as infraspecies will not get counted, e.g. if someone observed *Crotalus oreganus* ssp. *oreganus* and not *Crotalus oreganus*, nothing will be counted. Is that what you want? That almost seems like it will cause even more confusion.

**Comment by loarie** [comment]
The immediate goal is for consistency
The longer term goal is for a good counting statistic. I'm going to lobby for leaves as the longer term best counting statistic.

As for the immediate goal of consistency, what statistic would you prefer among our short term options: species, species, ssp. & var., & all taxa. I think species is the least confusing of these three

**Comment by kueda** [comment]
I sort of feel like species-and-lower (i.e. `hrank=species`) is the least confusing, which is how the "Total" species works now on projects/show. That way you err on the side of too many taxa than on not enough, so no one can complain about their contribution not getting counted at all. Complaining about a species getting counted twice b/c a subspecies was observed seems like a lesser problem, no?

**Comment by loarie** [comment]
I'm not sure I agree, but I don't feel strongly about the choice given this set of options (I do feel strongly about implementing a consistent leaf count soon ;) 
If you want to make everything count species-and-lower now thats fine with me, but can you also identify these locations to make what changes where from the existing issues?

**Comment by kueda** [comment]
I don't feel terribly strongly about it, and I'm happy to take your lead here since I feel like this is a temporary fix in advance of HAVO, but don't you think it's harder to explain to people why their contribution *doesn't* contribute to a count vs why it seems to count twice? Is it because you usually have to explain these counts to park managers who don't actually do much to contribute to the count themselves?

**Comment by loarie** [comment]
I thought going with species would be (1) an easier change to make and (2) easier to explain. But if you want to go with species-or-lower, thats fine with me. Can you pick one and make the changes?

**Comment by loarie** [comment]
Still a problem here, perhaps unrelated, but '298'
![screen shot 2015-06-02 at 2 27 11 pm](https://cloud.githubusercontent.com/assets/598026/7947691/9640842c-0933-11e5-8e2e-26fad8689101.png)
http://www.inaturalist.org/projects/hawai-i-volcanoes-national-park-bioblitz-2015
is not matching '287' showed on the subsequent link
![screen shot 2015-06-02 at 2 28 37 pm](https://cloud.githubusercontent.com/assets/598026/7947712/b05d9ed0-0933-11e5-9ff0-372f5bc39a55.png)
http://www.inaturalist.org/observations/taxa?d1=2015-05-15T13%3A00%3A00-06%3A00&d2=2015-05-16T17%3A00%3A00-06%3A00&place_id=7222&hrank=species

**Comment by pleary** [comment]
The projects/show page was showing a number that was incorrectly high, due to how Elasticsearch has implemented counting https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate . I raised the `precision_threshold` for the counts in 558c480 , and the numbers now seem to be the same in both places.

There is other discussion here about what the count should actually represent, but the differences in counts should no longer happen. Should we close this and move the discussion about species vs leaves to another ticket?
