### ISSUE TITLE
taxon_ids[] param not properly filtering observations

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#563]
noticed issue in this year long plant bioblitz http://www.inaturalist.org/projects/joshua-tree-national-park-wildflower-watch/
'all observations' uses this param which is not restricting obs to plants (taxon_id 47126)
http://www.inaturalist.org/observations?d1=2015-01-01T01%3A00%3A00-07%3A00&d2=2015-07-31T02%3A00%3A00-06%3A00&place_id=3680&taxon_ids%5B%5D=47126

**Comment by kueda** [comment]
The underlying issue here is that Joshua Tree's place boundary can't be indexed by elasticsearch for some reason, so these queries are going straight to the database, and there we're not filtering by `taxon_ids[]` b/c that could doing an arbitrary number of taxon descendant clauses could potentially be horrible (that's one the advantages of using ES). I can fake this kind of behavior by looking for single rules or rules involving iconic taxa, which will solve this particular problem, but it won't solve it for a project that has more than 1 taxon rule including non-iconic taxa.

**Comment by loarie** [comment]
got it - this must be the ),( vs )),(( kml upload issue we found with HAVO. I'll make a separate issue for that

**Comment by pleary** [comment]
I think this is resolved now that we're no using the elasticsearch geospatial queries. Scott, can you confirm?

**Comment by pleary** [comment]
Sorry - already closed. My bad
