### ISSUE TITLE
Private coords for obs without proper permissions in project all csv export

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#568]
Private coordinates showing up in AllCSV export from projects where project curators don't have proper permissions

**Comment by kueda** [comment]
Can you test this when you get a chance?

**Comment by zooga1961** [comment]
Hi   I do know that the coral root orchids still are not obscured for Cedar Ridge Preserve.    Then I thought well maybe because I am a project curator…that is why I still see them?

 

Thank you for the opportunity to be of service to you.

 

Deborah Nelson 

principal

 

Deborah Nelson & Associates LLC

3824 Cedar Springs Rd.,  Ste. 538

Dallas, TX  75219

 

e: deborah@dn-assoc.com <mailto:deborah@dn-assoc.com> 

p: 469.583.7781

 

Representing Architectural Design Products in Texas, Oklahoma, & Louisiana

 

Jockimo - Advanced Architectural Products: Specialty Glass Flooring, LiquidLava, ImagenGlass & More 

OKITE - Visions Made Real: Natural Quartz Surfacing 

O_KERA - by OKITE.  Large format (10’ long x ¼” thick) Ceramic Slab

Seeyond - Imagination Delivered: Walls, Facings, Clouds, Enclosures, Columns

**Comment by kueda** [comment]
Deborah, that doesn't sound like it's related to this issue. Please use the Google Group for reporting problems like that, and please make sure you include the URL of the observation and/or taxon in question, otherwise it's really hard to know what you're talking about.

**Comment by loarie** [comment]
Seems to be fixed
