### ISSUE TITLE
Store on observations updated_at and updated_by for changes to taxon_id

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#574]
Calculating 'novel' observations (e.g. 'first tiger beetle from Oaklahoma' or 'first Mandrill on iNat') require that we know not just when an obs was created, but specifically when the taxon_id changed

Likewise, this when and who the taxon_id changed was raised as a stat that might be useful to track

Seems like both would require adding two columns to the observations table, maybe taxon_id_updated_by and taxon_id_updated at?

**Comment by kueda** [comment]
So that would basically be the same as `observation.identifications.where(taxon_id: observation.taxon_id).order("id ASC").first.created_at` and `observation.identifications.where(taxon_id: observation.taxon_id).order("id ASC").first.user`, or you also want to track when and who for *any* identification that alters the observation's taxon, not just ones exactly matching the observation's taxon?

**Comment by loarie** [comment]
sounds like @pleary found a way to implement Globally New Observations without needing this https://github.com/inaturalist/inaturalist/issues/630
