### ISSUE TITLE
Translated variable in fr.yml

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#584]
month changed to mois causing this 500 error:

I18n::MissingInterpolationArgument: missing interpolation argument :mois in "vos observations de %{mois}" ({:month=>"Juin"} given)

**Comment by kueda** [comment]
Please also let the translatewiki folks know that they should not translate variable names. Not sure what the best way to do that is.

**Comment by loarie** [comment]
I can contact the guy who translated that string - but I think thats the best I can do

**Comment by kueda** [comment]
@siebrand, any recommendations for preventing this kind of problem in the future? The issue was that a translatewiki translator translated a variable.

**Comment by siebrand** [comment]
Can't really be avoided. We have so called checkers in place, that warn translators about (not) using variables. In those cases, translations will be marked as fuzzy until that's fixed. For iNaturalist, this checker has only been in place for new translations since May 25[1], so it's possible that before that date errors were introduced that went unnoticed.

[1] https://gerrit.wikimedia.org/r/#/c/213538/
