### ISSUE TITLE
Wikipedia articles not loading on taxon pages

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#603]
For example, http://www.inaturalist.org/taxa/143539-Anchomanes not loading https://en.wikipedia.org/wiki/Anchomanes

**Comment by pleary** [comment]
OK this should be fixed in production now. Wikipedia I guess stopped allowing http requests, and is redirecting them to https requests. I updated the MetaService code so we're now doing both of those. I also deleted any cached API calls that looked like they failed, so hopefully the articles are showing up now.
