### ISSUE TITLE
Ability to mark observations as 'Reviewed by you' to exclude them from searches

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#611]
One of the requests that have come up by people asking for better tools for finding observations that Need ID (#576) is the ability to mark observations as 'Reviewed by you' and to be able to easily exclude them from searches.

One potential way for this to work would be to build something similar to 'Subscribing' to observations. Like Subscriptions, any ID added to an observation would automatically mark it as reviewed. But the user would also be able to manually add or remove the marking:
![screen shot 2015-06-19 at 6 49 02 pm](https://cloud.githubusercontent.com/assets/598026/8265598/38bdaabc-16b4-11e5-9207-a2648b7e3dc8.png)

The results of these markings would need to be easily incorporated into the search, and I imagine there are some constraints/ways of doing this that would make this easy or hard. How does the above rank along those lines @pleary?

**Comment by tnywlls** [comment]
Sounds good to me, I often find myself re-looking at observations that I've already 'processed'.

**Comment by naturalistcharlie** [comment]
I'd use it.

On Monday, June 22, 2015, tnywlls <notifications@github.com> wrote:

> Sounds good to me, I often find myself re-looking at observations that
> I've already 'processed'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/611#issuecomment-114009985>
> .
>


-- 
Sent from Gmail Mobile

**Comment by naturalistcharlie** [comment]
I think it would go well with a "random" sort or something like that.

On Monday, June 22, 2015, Charlie Hohn <naturalist.charlie@gmail.com> wrote:

> I'd use it.
>
> On Monday, June 22, 2015, tnywlls <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Sounds good to me, I often find myself re-looking at observations that
>> I've already 'processed'.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/611#issuecomment-114009985>
>> .
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by kueda** [comment]
I'm not sure I see the reason to record that someone has reviewed an observation, especially if we're going to pursue a "needs ID" state as described in #576. Presumably if we are going to develop tools for identifiers and we don't want to show them things multiple times, we can just show them observations that "need ID" and that they have not identified, and the only additional thing we need to record is that they explicitly chose not to add an ID, right? Are there really situations where recording "reviewed" is superior to recording "can't ID"?

Also, what happens when the community ID shifts and the observation may need additional review by past identifiers? Do we rely on the notification system to alert them to this, or do we remove "reviewed" status?

**Comment by naturalistcharlie** [comment]
I do think 'can't ID' is different from 'reviewed' though maybe they can be
covered by the same label.

My understanding was 'can't ID' was for something that the reviewer
believed was not possible to discern based on the photo... whereas
'reviewed' just means the reviewer can['t personally ID it.  IE I might be
reviewing plants in California, and come across an observation with good
photos of something I have no clue about. Perhaps I'd want to label it so
it didn't come in my ID stream again... but I don't want to label it
somehow unidentifiable because it is my lack of knowledge not the quality
of the photo that means i can't id it.

Did that make sense? Sorry if it didn't

On Mon, Jun 22, 2015 at 2:46 PM, Ken-ichi <notifications@github.com> wrote:

> I'm not sure I see the reason to record that someone has reviewed an
> observation, especially if we're going to pursue a "needs ID" state as
> described in #576 <https://github.com/inaturalist/inaturalist/issues/576>.
> Presumably if we are going to develop tools for identifiers and we don't
> want to show them things multiple times, we can just show them observations
> that "need ID" and that they have not identified, and the only additional
> thing we need to record is that they explicitly chose not to add an ID,
> right? Are there really situations where recording "reviewed" is superior
> to recording "can't ID"?
>
> Also, what happens when the community ID shifts and the observation may
> need additional review by past identifiers? Do we rely on the notification
> system to alert them to this, or do we remove "reviewed" status?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/611#issuecomment-114215873>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by loarie** [comment]
> I'm not sure I see the reason to record that someone has reviewed an observation, especially if we're going to pursue a "needs ID" state as described in #576.

Are you saying only to record 'can't ID' (ie marking something to indicate I looked at this and have no comment but don't want to see it again) rather than mixing 'can't ID' with things someone has already ID'd (and presumably gleaning that information from data already recorded in Identifications)? Or is there some other difference in what you have in mind from what's scoped here.

> Also, what happens when the community ID shifts and the observation may need additional review by past identifiers? Do we rely on the notification system to alert them to this, or do we remove "reviewed" status?

Could do the 'remove review status' but IMO I'm going to mainly use these reviewed markings on obs that I don't have the expertise to resolve further but I think someone else might, e.g.
http://www.inaturalist.org/observations/563612
or
http://www.inaturalist.org/observations/1641263
So I don't think the community ID is going to change on these obs in such a way that's going to make it so that I have more to add (the former will prob go from genus to species or maybe back up to suborder but in both cases I won't have much to add, and the latter will prob go from Order to Family but not to some other order and in that case I won't have much to add). For me, the main reason I would want to go back and give another shot at these would be if I learned a bunch about track or tadpole ID respectively which the altering community ID won't capture.

**Comment by kueda** [comment]
I guess I just want to know if there are situations when you *can* add an ID but still don't want to see the observation again. The only one I can think of is when there's already a community ID I agree with. All other situations seem to be one in which I can't add an ID.

If there are situations when you *can* add an ID but still don't want to see the observation again, then storing "reviewed" makes more sense than storing "can't" ID, but if not, then I don't see the need for storing duplicate data (i.e. "reviewed" records for every identification).

**Comment by naturalistcharlie** [comment]
if they aren't separate, than 'can't ID' can not really be used as a
mechanism to globally filter observations out that may not be identifiable.
Because there are lots of things that someone else could ID that I can't.
If that makes sense at all

On Tue, Jun 23, 2015 at 6:57 PM, Ken-ichi <notifications@github.com> wrote:

> I guess I just want to know if there are situations when you *can* add an
> ID but still don't want to see the observation again. The only one I can
> think of is when there's already a community ID I agree with. All other
> situations seem to be one in which I can't add an ID.
>
> If there are situations when you *can* add an ID but still don't want to
> see the observation again, then storing "reviewed" makes more sense than
> storing "can't" ID, but if not, then I don't see the need for storing
> duplicate data (i.e. "reviewed" records for every identification).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/611#issuecomment-114666955>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by tnywlls** [comment]
I see this as totally independant of any identification status for the observation. As loarie suggested it could perhaps be implimented like subscribing to an observation, but I would not see it as something set for every observation automatically, just a flag that can be placed manually on an observation so that it can be easily excluded.  Perhaps sort of like a list of observations to ignore.

I often trawl through old observation using different search criteria to find things that I can identify/add fields to/or otherwise comment on.  It would save a lot of time if I could automatically exclude things already considered.  I suppose I could achieve the same thing by creating a private project and adding the observations there, and then using not_in_project searches.

**Comment by loarie** [comment]
>I guess I just want to know if there are situations when you can add an ID but still don't want to see the observation again.
For me thats kind of the standard use case. For example, I ID'd this to superfamily:
http://www.inaturalist.org/observations/903552
And I could imagine trying to take on reviewing all US crustaceans to get them ID'd to something like superfamily/family. But currently I don't have the skills to ID these further than superfamily, so I'd like to be able to not keep clicking on it only to find that I've already ID'd it. I don't really care whether thats by being able to just filter out things I've already ID'd + can't ID or combining those into a 'reviewed' metric.

**Comment by naturalistcharlie** [comment]
When we strive to get everything reviewed, I think ultimately having 2
additional IDs rather than 1 would be optimal.  Not that the benchmarks for
research grade should be changed, but we don't want to steer people away
from things with just the observer and 1 other ID when we create this
stream for people to ID.  Two reasons:

-People make mistakes. I have ID'ed things wrong on accident and found them
when someone else also reviewed. I think it's rare overall, but it does
happen.

-For many 'research grade', there is really only one ID. For example: When
in Costa Rica I put a moth into iNaturalist. I don't have a clue what it
is, I don't know that many moths and I am 4000 miles from home where I do
know some.. Someone who knows Costa Rica IDs it and i agree because the ID
looks right... but I don't really know much about it.  it would really be
best with another ID.

So I guess what I am saying is if we have a stream that feeds people to
things that need verification, I'm not sure it should steer people away
from things with just 2 IDs. I guess this is lower priority than getting to
the things without any verification, and maybe harder to implement. But
just a thought.

On Wed, Jun 24, 2015 at 12:40 AM, Scott Loarie <notifications@github.com>
wrote:

> I guess I just want to know if there are situations when you can add an ID
> but still don't want to see the observation again.
> For me thats kind of the standard use case. For example, I ID'd this to
> superfamily:
> http://www.inaturalist.org/observations/903552
> And I could imagine trying to take on reviewing all US crustaceans to get
> them ID'd to something like superfamily/family. But currently I don't have
> the skills to ID these further than superfamily, so I'd like to be able to
> not keep clicking on it only to find that I've already ID'd it. I don't
> really care whether thats by being able to just filter out things I've
> already ID'd + can't ID or combining those into a 'reviewed' metric.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/611#issuecomment-114725428>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
After discussing this with the team I think we're going with the "reviewed" model Scott proposed here (the idea of "can't ID" will presumably be encapsulated in voting off "needs ID" from #576).
