### ISSUE TITLE
can the project aggregator be opened up to curators?

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#615]
Currently the project observation aggregator can only be turned on for "trusted" projects, and projects can only be trusted by site admins. We did this because we want to make sure people aren't just turning it on for no reason, and to restrict usage to projects that actually intend to use the data they're collecting. Some partners would like to extend the ability to turn it on to site curators, though.

- [x] Estimate how many projects would get the aggregator as a result, list some of their search parameters (places, taxa, etc), and estimate how many new project observations this might generate per day (@loarie, I think this is on you since you know what kind of projects this would apply to)
- [x] confirm that the project aggregator is using elasticsearch and not the database for its searches (@pleary)
- [x] if this seems like its going to create load we can support, make it so any site curator can turn on the project aggregator for any project they can edit

**Comment by loarie** [comment]
I think the biggest load will come from protected area projects with the NPS centennial collaboration and CONABIO is doing a similar thing creating Mexican protected area projects. So these are all place parameters only. So maybe ~300 such projects, maybe generating an average of 0.5 obs each day which would be something like 150 project obs per day. This is all a very rough guess

**Comment by kueda** [comment]
150 per day doesn't sound horrible, I guess. Does that sound feasible, @pleary?

**Comment by pleary** [comment]
I made some performance improvements in f008f19 which should allow us to do a lot more aggregation. The main changes were applying the date limitation to DB queries, not counting the DB results with each iteration (meaning if there are 200 pages of results for a project's aggregation query, we just fetch the total once and not 200 times - each total count could cost up to 10 seconds), and making sure we use ES all the times we can.

There was one project (647) which had a list filter which wasn't getting used, and the date filter wasn't being used for the DB, so it was just paging through all observations in Mexico in the DB. Locally it's looking like around 10 seconds per page (on the count mostly) so that would put that in at about 10.25 hours assuming it didn't get slower as would usually happen paging through large sets. Now, with all these changes, aggregating all projects locally takes less than 10 seconds.

So I say let's open it up wider and address any further performance issues as they come up.

**Comment by loarie** [comment]
great - thank patrick - I'll assign this to Ken-ichi then to make the minor UI change of displaying it to curators
