### ISSUE TITLE
discrepancy between db and es user stats

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#625]
http://www.inaturalist.org/people/leaderboard/2015/1 and http://www.inaturalist.org/observations/user_stats?on=2015-01&hrank=species should theoretically show the same numbers, but they don't. The former hits the database, while the latter uses elasticsearch. Not a super high priority, but it would be nice for these to match, and to fix any bugs in calculation that might be happening.

**Comment by pleary** [comment]
This should be fixed in 24aab27 . The leaderboard will use the same ES querying methods as Observations::user_stats, and those methods have been moved from ObservationsController to the shared ObservationSearch library.

Identifications are still being counted through the DB, and that is by far the slowest part of these pages. I was holding off putting IDs in ES until we decide the various ways we'll want to count IDs (see Issue #530, inaturalist/design#25), since we'll have to reindex all observations to begin using the data. But we could pull the trigger anytime
