### ISSUE TITLE
Incorrect mime type in response when 'Accept' header used and extension omitted

### ISSUE THREAD

**Issue by premasagar** [inaturalist/inaturalist#644]
Omitting the `.json` extension in uris and passing a header of `Accept: application/json` correctly gives a JSON response. So, these give identical responses:

    $ curl -H 'Accept: application/json' -X GET https://www.inaturalist.org/taxa/48599.json -L
    {"id":48599,"name":"Phytolacca americana","rank":"species","parent_id":48601, ...

    $ curl -H 'Accept: application/json' -X GET https://www.inaturalist.org/taxa/48599 -L
    {"id":48599,"name":"Phytolacca americana","rank":"species","parent_id":48601, ...

However, the mime type for the second resource is incorrect; it is `text/html` instead of `application/json`:

    $ curl -H 'Accept: application/json' -X GET https://www.inaturalist.org/taxa/48599.json -L -I
    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    ...

    $ curl -H 'Accept: application/json' -X GET https://www.inaturalist.org/taxa/48599 -L -I
    HTTP/1.1 200 OK
    Content-Type: text/html; charset=utf-8
    ...

Is it supported to call endpoints without the file extension, instead using the `Accept` headers? (related #400)

**Comment by pleary** [comment]
This was ultimately a problem with the Actionpack Page Caching gem for Rails 4 https://github.com/rails/actionpack-page_caching . Apparently it can't properly return the mime type unless explicitly defined in the route (we accept multiple extensions for this method so I don't think that's possible), or explicitly declared in the request URL. After checking how many requests we got for this JSON API, I decided it was safe to just not page cache the results which seems to have fixed the problem.

The fix was in commit 95581d3 . Note though that this was a one-off fix for the Taxa JSON API requests. Any other place we're using caches_page or caches_action could very well be suffering from the same problem.

An interesting case indeed. Thanks for bringing this to our attention, and please let us know if you encounter anything else like this.
