### ISSUE TITLE
Change algorithm for how public coords for obscured obs are calculated

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#649]
Currently when an observation is obscured (via geoprivacy setting or via associated threatened taxa) we pick a uniformly distributed random cardinal direction from the true point and pick a point a uniformly distributed random distance from 0 to 10km in that direction to calculate a position to display the public location  https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L1797

Unfortunately, when there are many many obscured observations on the same location (e.g. someone's house) its easy to estimate the private location as the center of the circle made up of public locations.

This proposal is to change to the following algorithm to avoid this problem:
1) Calculate the floor of the latitude and longitude rounded to some significant figure (e.g. y = 0.1 degrees) to represent the lower left hand corner of a y-by-y degree cell that contains the private location
2) Add a uniformly distributed random lat and lon offset for this lower left hand corner between 0 and y
3) Calculate the public coordinate as private_lat+lat_offset and private_lon+lon_offset.

The disadvantages of this approach are that the size area from which the private location is drawn will change from consistently 314km^2 to some value at the equator that approaches 0 at the poles since the distance of one degree of longitude varies with latitude.

For simplicity and since the existing 10km offset was pretty arbitrarily chosen, I suggest we pick a value of y=0.1 for the cell size which will vary from an obscured area of 11x11=121km^2 at the equator, to 9x11=99km^2 at the latitude of San Francisco to 5x11=55km^2 at the latitude of Anchorage. Thoughts?

(here's a nice lat/lon to km converter http://www.nhc.noaa.gov/gccalc.shtml)

**Comment by kueda** [comment]
Cell size sounds fine to me. Let's see what it looks like.

**Comment by naturalistcharlie** [comment]
sounds great, i'd be able to fix all of my observations from home that i
used a really weird self-obscuring thing on.

On Mon, Jul 27, 2015 at 8:19 PM, Ken-ichi <notifications@github.com> wrote:

> Cell size sounds fine to me. Let's see what it looks like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/649#issuecomment-125384578>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by pleary** [comment]
here's an example of exactly what Scott described:

<img width="278" alt="screen shot 2015-07-28 at 3 08 05 pm" src="https://cloud.githubusercontent.com/assets/48566/8940905/8a8c5d3a-353a-11e5-8fe0-0f141f2ec5c8.png"> <img width="282" alt="screen shot 2015-07-28 at 3 08 00 pm" src="https://cloud.githubusercontent.com/assets/48566/8940910/8d4a6c2e-353a-11e5-9cee-02f70a04f5ca.png">

**Comment by loarie** [comment]
that looks good to me - maybe I did my math wrong if thats a 0.1 degree grid, the areas look about the same

**Comment by pleary** [comment]
oh, sorry you're right - not exactly what you said. Instead of:
> 2) Add a uniformly distributed random lat and lon offset for this lower left hand corner between 0 and y

I did between -y and y, effectively quadrupling the areas you suggested. Here is what it looks like between 0 and y
<img width="278" alt="screen shot 2015-07-28 at 3 08 05 pm" src="https://cloud.githubusercontent.com/assets/48566/8941483/d4b1a4b2-353d-11e5-8df1-852c5942a9b7.png"> <img width="283" alt="screen shot 2015-07-28 at 3 31 23 pm" src="https://cloud.githubusercontent.com/assets/48566/8941479/c912e328-353d-11e5-81af-346a8a2779da.png">

Maybe the larger area (-y to y) will work and isn't too large?

**Comment by loarie** [comment]
Sounds great to me

**Comment by pleary** [comment]
I put the new algorithm on Staging and re-computed all obscured obs coordinates http://staging.inaturalist.org/observations/map?type=map&color=grey#10/40.545/-77.275 . I did end up making one change, which is instead of using a floor function I ended up rounding, which was needed when using -y to y instead of 0 to y. The obscured area remains the same 4x Scott's original calculation.

The Staging tileserver is a little slow, but it's worth checking out the Bay Area which is now a little blocky, but I think that's fine. The other thing we could do if that's a problem is combine this approach with the original and first round the coordinates then do the circular obscuring. The main original problem was the origin of obscuring was the original observation location. Scott's idea is a great one because it changes this origin, which I think is the key. Whatever shape we use to obscure the coordinates from there is pretty much irrelevant. For what it's worth the rectangles are easier to compute, but the different is probably negligible.

**Comment by pleary** [comment]
this is finished, deployed, and all observations with obscured coords have been updated. Just waiting on the needs_id release and then we'll be ready to get back to the obscured observations in map tiles

**Comment by kueda** [comment]
According to https://github.com/inaturalist/inaturalist/blob/23e6388fa0da1fd45da038f4978a8e8316a9ea0f/app/models/observation.rb#L2311, an observation is not mappable if it's `public_positional_accuracy` exceeds `M_TO_OBSCURE_THREATENED_TAXA`, and according to https://github.com/inaturalist/inaturalist/blob/23e6388fa0da1fd45da038f4978a8e8316a9ea0f/app/models/observation.rb#L2291, the public_positional_accuracy is defined as the `positional_accuracy` or `M_TO_OBSCURE_THREATENED_TAXA`, which means that if you create an observation with greater than 10,000 m `positional_accuracy`, it never gets shown on a map. Was that intentional, i.e. did you guys want to not map anything that had a `positional_accuracy` greater than that we automatically applied for coordinate obscuration?

I ask because we are still using `M_TO_OBSCURE_THREATENED_TAXA` to determine `public_positional_accuracy` and thereby its `mappable` state, even though this issue made it so we don't even use that for coordinate obscuration anymore. I have a fix that's a part of #865, but I wanted to clarify this point with you guys before committing it.
