### ISSUE TITLE
Taxon name not updated after identification

### ISSUE THREAD

**Issue by premasagar** [inaturalist/inaturalist#651]
For this observation: https://www.inaturalist.org/observations/1806922
The a genus identification was given by another user, which I agreed with. I then added a species identification, after a comment from another user. However, the page still gives the genus name.

Data resources that contain the observation, e.g. https://www.inaturalist.org/observations/project/serra-do-acor.json have the `taxon_id` for the genus not the species, with a `species_guess` of the correct species but no taxon_id for it, so I cannot get at the information, without performing an additional search on the `species_name`.

**Comment by kueda** [comment]
The community is of the genus, so that's the "official" taxon associated with that observation. You can see why the community ID is of the genus by clicking the "About" link below the community ID. If you want the observation associated with the taxon from *your* identification and not that of the community, click "Reject" below the community ID. If you never want the community's opinion to override your own for your observations, you can specify this in your settings: http://www.inaturalist.org/users/edit

**Comment by premasagar** [comment]
Thanks for the explanation. I hadn't seen that "About" link before. It is useful information - I was unclear on how the community ID process works.
