### ISSUE TITLE
taxon autocomplete / chooser should show the name matched

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#656]
If I search for Животные I currently see 

Animals
Kingdom Animalia

as a result, but I'd prefer to see

Животные
Kingdom Animalia

When I search for アユ I see 

Plecoglossus altivelis
Species

as a result, but I expect to see

アユ
Plecoglossus altivelis

UPDATE

After some discussion we decided that we wanted to show something like

Animals (aka Животные)
Kingdom Animalia

because "Animals" is going to be the name shown if your locale is "en" no matter what you searched for, but we still want to show the text that matched your query.

**Comment by joellebel** [comment]
Here's a mock of the external search icon and alternative name treatment...

![image](https://cloud.githubusercontent.com/assets/11527994/9145197/726c6798-3d07-11e5-98b1-8ffe83f7ade9.png)


We could also put a title above the search results and below the search filters that says something like... Search results for "blue belly" AKA "Western Fence Lizard" 

However, at this point the user has clicked on the item already containing the alternative name, so they should be aware of what they are looking at. 

Am I leaving any states or scenarios out?

**Comment by pleary** [comment]
I just want to make sure some cases of extreme string length are considered. I can type in "play" and get the result for "Gulls, Button-Quails, Plovers and Allies" because it matched the Spanish string "Playeros, playeritos, ostreros, chorlitos, gaviotas y gallitos de mar", or vice versa depending on my language. Right now we're fading out text longer than one line, so we'd likely fade out the matching term. Is that OK, or are you still working on a version with wrapping?

**Comment by joellebel** [comment]
oh right, wrapping. uno secondo...

**Comment by joellebel** [comment]
I didn't specify a line height yet on the text because I'd first like to see where it's at naturally before creating more CSS.

Also the hover state for the cell is #3366CC at 15% opacity. Please also give the same hover state for the "View" button

![image](https://cloud.githubusercontent.com/assets/11527994/9145896/f448c266-3d0c-11e5-92ec-84dfe0a75a16.png)

**Comment by kueda** [comment]
ac97af14cd37b75c976c0e11a398f1f44443de16 adds @joellebel's solution and is in prod. Thanks, folks.
