### ISSUE TITLE
In one observation, community ID (or ID tagging) not working

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#665]
http://www.inaturalist.org/observations/823
This user did not opt for full control over their observation. They tagged it as a beaver as did three others. Yet it still says 'something' and does not tag as a beaver.
Maybe I am just missing something but it looks like a bug.

**Comment by kueda** [comment]
Hah, way to find a really obscure one. The underlying problem is that the observation has an invalid date, but I think it was added before we started checking for that particular problem, so when it was added it was fine, but now it's invalid and attempts to save it (e.g. when adding an identification) are failing. I know this user so I'll take the liberty of updating it.

**Comment by naturalistcharlie** [comment]
Aha! That makes sense. I am using the new ID please system and going
through old obs, all kinds of neat stuff back then that I never saw.

On Fri, Aug 14, 2015 at 6:47 PM, Ken-ichi <notifications@github.com> wrote:

> Closed #665 <https://github.com/inaturalist/inaturalist/issues/665>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/665#event-383052760>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
