### ISSUE TITLE
Add observations' taxon threatened status and establishment means to ES index

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#693]
We want to be able to query for observations that are threatened in their location context, as well as introduced, native, and endemic. Use the centroid of the observations uncertainty region as a starting point.

Related discussion in https://github.com/inaturalist/design/issues/20

**Comment by pleary** [comment]
I found an interesting case in http://www.inaturalist.org/observations/1000148 , which is introduced to its region and endemic to its country. Looking at https://github.com/inaturalist/inaturalist/blob/master/app/models/listed_taxon.rb#L378 I wonder if what we want to record is
 - introduced = true if the observation is introduced in ANY place it exists, otherwise native = true if it is set as native or endemic in any place (otherwise introduced and native are false) (i.e. introduced trumps all), OR
 - grab the first establishment means if the place with the highest admin_level or lowest place_type and is that most specific value only, OR
 - have it returned in searches for both observations of endemic and introduced taxa?

In the first two options introduced and native can never both be true, whereas they can in the 3rd.

Finally - any need to distinguish native and endemic, or do we just need `introduced?` and `native?`?

**Comment by kueda** [comment]
I think introduced and native should never both be true. On observations/show we choose the listed taxon with the smallest `bbox_area` that has `establishment_means` set to `endemic` or `introduced`, and I think that's the strategy we should use here.

Regarding endemism, this is a situation in which we overloaded the establishment_means field when we probably shouldn't have. I think ideally the ES index should have have a separate field for endemic: true | false, since a taxon can be native AND endemic, but also native and NOT endemic.

**Comment by pleary** [comment]
So we'll grab the first listed_taxon sorted by bbox area with an establishment_means. If the means is `introduced` then `obs.taxon.introduced` = true, of the means is `native` or `endemic` we'll set `obs.taxon.native` = true

Additionally we'll set `obs.taxon.endemic` = true if it has an establishment_means of exactly `endemic`. One last weird case - in the example I gave it is technically `endemic` to New Zealand, but I suspect if `obs.taxon.introduced` = true then endemic should never be true, but endemic can be true if `obs.taxon.native` = true

**Comment by kueda** [comment]
I think that's right. There are always going to be some weird edge cases like that, I'm afraid, since so much of this depends on the context of the search. So with the current strategy, people searching for observations of endemic species in New Zealand are not going to see http://www.inaturalist.org/observations/1000148, even though it's an observation of a species that's endemic to New Zealand (sort of, at least for wild populations).
