### ISSUE TITLE
Add setting for who can add observations to a project

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#727]
Two reasons for this feature:

1. We'd like to start running observation of the day through a project since people have been requesting views to see this collection. But its important that only observations that we've selected are added (e.g. only project curators can add observations)

2. Texas Parks and Wildlife needs to ensure that the only observations in their projects are those that they have access to the private coords of (since thats their whole economy). So they need to control who can add observations to the project based on how these permissions are authorized.

To make this happen:
a. Add a setting to projects/new
```
Who can add observations to the project?
* Any project member
* Project curators only
* Those with permission to add observations with private coordinates that project curators can view
```
where:
*  'Any project member' is how it currently works
* 'Project curators only' is what we'd use for Obs of the Day
* 'Those with permission to add observations with private coordinates that project curators can view' is what Texas Parks and Wildlife would use and would be Observation.user only if the ProjectUser settings were 'You' for  'Allow project curators to view...' on Project#join, and Observation.user and also project curators if if the ProjectUser settings were 'Project Curators' for  'Allow project curators to view...' on Project#join

Based on these settings, the 'Add to Project' button on observation/show would display accordingly

**Comment by kueda** [comment]
A slightly modified proposal and implementation spec:

- [ ] add `observations_added_by` preference to project, default value `any`, alt value `project_curators`
- [ ] add validation to project observation that checks `project.preferred_observations_added_by` against the project observations `user_id`
- [ ] add  a new `coordinates_viewable_by_project_curators?` project observation rule. Should be true if the project curators have permission to view the private coordinates of the associated observation, false if not
- [ ] modify the project aggregator so it creates ProjectObservations with `user` set to the project admin

Pros:

* this makes #728 unnecessary since it will allow project owners to require that they can see the private coordinates of all contributions
* it makes #729 unnecessary because the aggregator will fail to add any observations that won't allow curators to see the coordinates
* I think articulating the coordinate visibility requirement as a project observation rule is a little more clear

Cons:

* this will make the aggregator slower because we'll either have to leave it as it is and over-select all the candidate observations that don't allow curator coordinate access, or we'll have to include project users in a database-based query, or we'll have to modify the elastic index to include project user data... which might not be possible
* if the project aggregator sets user on the new ProjectObservations, we may run into a problem with project admins being confused about why the site says they added an observation to a project when in fact, the aggregator added it to the project on their behalf
* it makes the validation error people will receive when trying to add observations to the project more confusing, especially in mobile where they won't have the chance to change their settings  

Pros outweigh cons? @pleary, any thoughts on whether the impact on project aggregator performance would be a killer?

**Comment by loarie** [comment]
if its feasible/performative this would achieve the same ends as this and #728 and #729

**Comment by loarie** [comment]
Ok this looks good - but two weird things are happening. There are currently two UI elements which would allow a user to revoke sharing coord permissions (retroactively, not just moving forward) on obs where they were previously enabled. They are:
1. unchecking this on the project component on an individual obs:
<img width="442" alt="screen shot 2015-10-30 at 12 46 14 pm" src="https://cloud.githubusercontent.com/assets/598026/10856916/2d6e11bc-7f08-11e5-9ec5-b31126feed51.png">
2. choosing the middle option when leaving a project
<img width="811" alt="screen shot 2015-10-30 at 1 13 36 pm" src="https://cloud.githubusercontent.com/assets/598026/10856918/2ec17fd6-7f08-11e5-87d4-6e653899951d.png">
These work fine without the project rule  `coordinates_viewable_by_project_curators?` (ie (1) revokes permissions on that obs and the box get unchecked and (2) revokes permissions on all obs and the boxes get unchecked)

But with the new `coordinates_viewable_by_project_curators?`, these UI elements are still available but they fail (ie they both seem to work, but (1) on refresh the box is still checked and permissions are still granted and (2) boxes still checked and permissions still granted).

I propose graying-out these UI elements (the checkbox on 1 and the middle radio on 2) for projects with the `coordinates_viewable_by_project_curators?` rule in place. Is that feasible?
