### ISSUE TITLE
iconic taxon images not loading for obs updates in daily email

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#741]
![screen shot 2015-10-16 at 11 57 33 am](https://cloud.githubusercontent.com/assets/22691/10550704/3ad04aa2-73fd-11e5-88f0-1a6d66bb22ca.png)

And the place icon isn't loading. Also see https://groups.google.com/d/topic/inaturalist/EOTJ1hv4spE/discussion

Tags have src attributes like `http://www.inaturalist.org/iconic_taxa/mollusca-75px.png` so I think the asset paths just aren't being used correctly.

**Comment by pleary** [comment]
Pretty sure these emails issues have been resolved for several months (another was #752). The root of the problem was, at one point I changed the capistrano deploy script such that taricha didn't precompile assets, to speed up deploys. But, taricha sends out the emails and needed the precompiled assets. Updating the deploy script fixed it.
