### ISSUE TITLE
taxon chooser not always showing iconic taxon icon

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#776]
<img width="599" alt="screen shot 2015-11-04 at 10 09 58 pm" src="https://cloud.githubusercontent.com/assets/22691/10959663/ed9e1b4e-8340-11e5-9b8e-662f0e8f204f.png">

Was trying to add an ID of http://www.inaturalist.org/taxa/296913-Hamataliwa-grisea on http://www.inaturalist.org/observations/2350417

**Comment by kueda** [comment]
Another example: searching for "Hamadryas" on http://www.inaturalist.org/observations/2458757

**Comment by pleary** [comment]
The first one seems fixed now, was likely an out of sync taxon record in elasticsearch. The second one seems to be a taxonomic homonym http://www.inaturalist.org/taxa/186624 . Have you seen other cases like this? Since that first case seemed legitimate there's probably some action that is failing to update elasticsearch, but it doesn't seem to be all that widespread

**Comment by kueda** [comment]
Haven't seen any recently, but will keep an eye out.
