### ISSUE TITLE
Display (but not search) of obs with dates only (no times) wrong in Obs Search

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#828]
Obs search is filtering on d1 & d2 in a defensibly reasonable way 
ie it is returning all obs with dates and times between the dates and times of d1 & d2 
AND all obs with only dates between the dates of d1 & d2

But the display of these obs with only dates is wrong. These obs should display without times, but instead, at time of 00:00:00 in their time zone is being added https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L722
and then rendered into the viewer's time zone (which seems to be the viewer's computers timezone, not the viewer's inat user account time zone, which is fine with me but perhaps confusing)

For example, the first 7 obs shown here should all read Jan 3, 2016, but instead they have 00:00:00 in their time zone added and then rendered in PST:
<img width="323" alt="screen shot 2016-01-19 at 10 46 17 pm" src="https://cloud.githubusercontent.com/assets/598026/12441690/875b6888-befe-11e5-97ea-2462b4fe63c7.png">
http://www.inaturalist.org/observations?d1=2016-01-03T01:00:00-05:00&d2=2016-01-09&order=asc&order_by=observed_on&subview=table&taxon_id=71268&verifiable=true

**Comment by carrieseltzer** [comment]
I thought a lot about this exact issue for the global snapshot last year and there was a thread about it in the google group (https://groups.google.com/forum/#!searchin/inaturalist/date$20queries/inaturalist/UWQDeOoO8eQ/r84jQdjMMzgJ).

In short, this could be resolved if it were possible to make d1&d2 queries without timezones use "observed_on" instead of "time_observed_at". That field seems like the most reliable, static, timezone-independent date to work with in that scenario. I imagine it's tricky to use the same parameter to query two different fields. What about this? (originally proposed in the google group thread)
d1 & d2 query observed_on and are used only for dates without times. If someone specifies a time or time zone, it would be ignored, or recognize that and default instead to...
t1 & t2 (new parameters that would have to be created) query time_observed_at and require a time zone specification.

**Comment by carrieseltzer** [comment]
Ok, I misread this earlier. Not the exact issue (sorry!), but related to queries and time zones.

**Comment by loarie** [comment]
Ok, now I'm no longer convinced this is just a display issue, Obs #2558313 is not returned in 
```
Observation.page_of_results(d1: '2016-01-03T00:00:00-00:00', d2: '2016-01-09T23:59:59-00:00', taxon_id: 71268, verifiable: 'true').total_entries
```
Since its observed_on was Jan 3 (no time), it should if it was just a display issue. I think what's happening is that first we're using datetime to add a bogus time of 00:00:00 in the time zone (+0100) and then we're using the UTC date to say this is in Jan 3 (not Jan 2). 
```Observation.find_by_id(2558313).observed_on
 => Sun, 03 Jan 2016 
2.2.0 :071 > Observation.find_by_id(2558313).datetime
 => 2016-01-03 00:00:00 +0100 
2.2.0 :072 > Observation.find_by_id(2558313).datetime.in_time_zone("UTC")
 => Sat, 02 Jan 2016 23:00:00 UTC +00:00```
We should consider dates without times regardless of timezone (ie Jan 3 not Jan 2)

**Comment by carrieseltzer** [comment]
Scott do you think that searching observed_on would resolve this? Observed_on never has a time stamp, only a date. 



—

**Comment by loarie** [comment]
looks fixed
