### ISSUE TITLE
Observation search pagination (was: enable back button from infinite scroll)

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#830]
I know we've talked about several solutions, so I'm not sure what the best approach would be. One might be to only update the URL hash before the user leaves for the new page. That doesn't seem to be how Flickr is doing it, though. That would also necessitate adding an observation ID and maybe scroll position  to the hash and then the api would need to accommodate showing observations around a certain observation, which may or may not be reasonable. It also gets us into bothersome sorting issues when we're not just sorting by ID.

**Comment by pleary** [comment]
We're thinking of doing something pretty simple. Currently we load 12 observations per "page" with the infinite scrolling, and we can keep loading pages of 12 forever. We can make infinite scroll stop once we've loaded, say, 96 observations and then present the user with a "Next Page" option. Clicking that will reload the browser page (or minimally change the URL) to show the page # in the URL, and the user will see the first 12 observations starting after # 96. Then can then scroll down and we'll load sub-pages of 12 results until # 192, and then we'll present "Next Page" they can use to go to "Page 3".

We could also show other pagination UI if we want (previous page, etc.). @joellebel can chime in on that. This will only affect the observation views (map, grid, list) and not the other major tabs.

We'll also need to accept a page parameter on new request and present the proper results matching the page number. Pagination will only affect observations pages, not the other content (species, observers, identifiers) which are still fixed to the top 500 results each. If users continue to report slow browser or crashing, we may want to lower that 500.

**Comment by joellebel** [comment]
All the logic sounds good to me. Here's my ideas on the two views.


# Grid View

96 obs per page sounds good to me. A number around that for the Species tab view. (There's 5 in a row on the Species tab) Can we do a pagination like this at the bottom for the grid view. This is the standard bootstrap pagination. 

![image](https://cloud.githubusercontent.com/assets/11527994/12563599/e622610e-c35f-11e5-9ee6-6effc8b783a4.png)


Or is it too much load to calculate out all the pages. I'm assuming for over a million it gets kinda hairy. However, we only have to show a max of 10 page links at a time similar to...


![image](https://cloud.githubusercontent.com/assets/11527994/12566363/218fdbc8-c36e-11e5-9b7d-35f328afe382.png)

# Map View

I think prev. and next links are sufficient for the map view. I threw together a design because the bootstrap prev and next buttons weren't a good fit for this design. 

![image](https://cloud.githubusercontent.com/assets/11527994/12567461/10c8463a-c374-11e5-88fe-c2c63d42ed5b.png)


I can do hover and inactive states if we're all good to go here.

**Comment by pleary** [comment]
I have a first pass on staging now http://staging.inaturalist.org/observations?place_id=any&subview=grid&taxon_id=3&page=75

**Comment by joellebel** [comment]
# Disabled and Hover States for the Prev/Next Buttons

### Disabled 

![image](https://cloud.githubusercontent.com/assets/11527994/12690185/8ebc4364-c696-11e5-945e-4dceb21940d0.png)


* Text is at 50% transparency

## Hover

![image](https://cloud.githubusercontent.com/assets/11527994/12690162/721fb5f6-c696-11e5-859e-7f005ee92a5d.png)

* Button bg is #74ac00 at 30%

**Comment by pleary** [comment]
These changes are now on Staging

**Comment by joellebel** [comment]
Shall we close this one, guys?
