### ISSUE TITLE
Add ability to easily switch locales

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#924]
Mentioned in Google Groups (last comments) https://groups.google.com/forum/#!topic/inaturalist/o2tEjxFAIY8

This has been brought up before. I threw together a super simple switcher that's on Staging right now http://staging.inaturalist.org/observations (just noticed that the dashboard is cached so the switcher isn't working there). Maybe we should show the language in the current language and the language itself (e.g. if viewing in English, a listing would be "Spanish, Español")?

Clearly this can be improved - any suggestions?

**Comment by pleary** [comment]
<img width="229" alt="screen shot 2016-03-11 at 8 40 07 pm" src="https://cloud.githubusercontent.com/assets/48566/13719805/795258c0-e7c9-11e5-8b5d-560c2264fe55.png">

Screenshot of the super quick version. How do we make this awesome?

**Comment by kueda** [comment]
IMO, as was suggested in slack, placement in the footer and/or auto-detection based on browser language would be preferable to me. Putting it in the header seems extreme since no one is going to use it more than once, so for everyone who is using iNat for the nth time, it's annoying, and that includes the non-English speakers who actually did use it on their first visit.

**Comment by loarie** [comment]
I don't really object to the header placement of this, but if thats whats holding this up, how about something like this with the menu expanding up
<img width="849" alt="screen shot 2016-04-06 at 3 07 34 pm" src="https://cloud.githubusercontent.com/assets/598026/14334459/69655c7e-fc09-11e5-9795-b8acec3b67f0.png">
thoughts @joellebel ?

I don't think I have enough info about how non-english speakers use the internet - do they mostly just set their browser and assume websites will translate?

**Comment by loarie** [comment]
On twitter, the language chooser only displays when I've set my browser language to something other than English. That might be a good approach since (a) those with their browsers set to English probably won't want to see the site in another language, and (b) those with their browsers set to another language (e.g. French) might still want to see iNat in English if the iNat translation is crappy and they also speak English. If the chooser only displayed when the browser langauge is not English (alla Twitter) any objections to it in the main menu?
<img width="889" alt="screen shot 2016-04-06 at 3 28 11 pm" src="https://cloud.githubusercontent.com/assets/598026/14334887/32f3851e-fc0c-11e5-9653-1f87255c8f7d.png">

**Comment by joellebel** [comment]
Hrmmm... I can't get that to work when I set my browser to another language, so I'll take your word for it. @loarie I don't have an objection to putting it in the the main nav for that scenario.

I am also ok with keeping the language dropdown in the very bottom footer as featured above.

**Comment by kueda** [comment]
Fixed in https://github.com/inaturalist/inaturalist/pull/1551
