### ISSUE TITLE
ES not indexing delayed job to set curator_id on project obs

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#936]
Resulting in Obs like these http://www.inaturalist.org/observations/2816506 where the ProjectObservation curator_identification_id is set, but they are not in ES

**Comment by pleary** [comment]
In add5171 I fixed a problem where observations were not getting reindexed after a new curator identification, thus not showing up in searches like these. That change is live, and I re-indexed all the project observations created or updated since the last big update. I can't promise there aren't more places that need indexing, but hopefully this will do it

**Comment by loarie** [comment]
looks good to me
