### ISSUE TITLE
observation search broken when place chosen

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#94]
Basically our search index doesn't include place IDs, because that would be a giant pain to calculate when indexing. However, another solution might be to cache place IDs in the observations table whenever the coordinates change or place boundaries change, and then index those as some kind of array attribute (pretty sure this can be done with Thinking Sphinx).

The other alternative would just be to disallow unsupported attribute filters like places when performing text searches.

**Comment by pleary** [comment]
We can now search most places in Elasticsearch, and fallback to querying the DB when a place is not in ES. I am also considering storing our cached observations_places as an array of place_ids in ES since it can't store all geometries, and is not 100% precise with the ones it can store. Regardless, we can search on places now
