### ISSUE TITLE
support for a/b testing features for mobile users

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#960]
We'd like to a/b test a user onboarding feature in iOS, and in order to measure the success or failure of the onboarding, we'd like the a/b sorting to be reflected in the inat user database.

**Comment by kueda** [comment]
Ok, so some questions:

1. Can one user be in multiple test groups at once?
1. Does the user's test group(s) ever change?
1. Is it ok to assign the user to a test group after creation?

3 is important because there are at least two ways to create a user, normally and via facebook / google. To assign arbitrary extra parameters via the latter route is doable on the server, but possibly harder for you on the client since you're using a stock OAuth package that probably doesn't support tacking on extra parameters to that access token request.

**Comment by alexshepard** [comment]
1. It would probably be best to support multiple test groups, assuming we want to do more of this.
2. No, users shouldn't change test groups.
3. Yep, that would be best for me on mobile. I have to assign the user to a local test group _before_ login happens anyways.

**Comment by kueda** [comment]
Done in 1e6f97b8d84607e865801768b711242e93edb5b9, I think.
