### ISSUE TITLE
Notification in App when someone id a record

### ISSUE THREAD

**Issue by vijaybarve** [inaturalist/inaturalist#978]
It will will be great opportunity to encourage interactions by raising a notification in the App when an id or comment is received on a record.

Ref: @rdmpage https://twitter.com/rdmpage/status/729201546089631744
Thing which bugs me about @inaturalist app, no notifications when someone ids one of my photos. Missed opportunity to encourage interactions

https://twitter.com/rdmpage/status/729201546089631744

**Comment by kueda** [comment]
I assume you mean push notifications, since both the apps already show an indicator when you have new comments or IDs. We might consider implementing push notifications if we decide to get pushy. Personally not a fan, but it might benefit new users. Either way, probably a more appropriate subject for the Google Group.
